### ISSUE TITLE
Unable to query metric 7dayUsers with date dimension

### ISSUE THREAD

**Issue by kennyengci** [MarkEdmondson1234/googleAnalyticsR#100]
Can't seem to query the metric **ga:7dayUsers** with dimension **ga:date**.

Even though this can be achieved in GA's query explorer.

```
data <- google_analytics_4(
    ga_id,
    date_range = c("2017-08-28", "2017-08-28"),
    metrics = c("7dayUsers"),
    dimensions = c("date"),
)
```
The code above returns error

> Error in `[.data.frame`(out, , met_names) : undefined columns selected
> API Data failed to parse.  Returning parsed from JSON content.
>                     Use this to test against your data_parse_function.2017-08-30 10:27:35> Downloaded [0] rows from a total of [].

**Comment by MarkEdmondson1234** [comment]
Thanks for the report!

It seems to be the result of an R gotcha - can't start column names with numbers:

```r
out_names
#[1] "date"      "7dayUsers"
make.names(out_names)
#[1] "date"       "X7dayUsers"
```

I will implement a hack around it :)

**Comment by MarkEdmondson1234** [comment]
Ok could you try the GitHub version?  It should work now.

```r
devtools::install_github("MarkEdmondson1234/googleAnalyticsR")
library(googleAnalyticsR)
ga_auth()
ga_id <- 12312323
data <- google_analytics_4(
    ga_id,
    date_range = c("2017-08-28", "2017-08-28"),
    metrics = c("7dayUsers"),
    dimensions = c("date"),
)
```

**Comment by kennyengci** [comment]
Working good now, thank you Mark
