### ISSUE TITLE
authDropdownUI  contains NA NA

### ISSUE THREAD

**Issue by sdhaus** [MarkEdmondson1234/googleAnalyticsR#104]
The authDropdownUI contains NA NA per account, which contains: `character(0)`

Is there a way to remove this?

**Comment by MarkEdmondson1234** [comment]
Sounds like a tweak to the code here https://github.com/MarkEdmondson1234/googleAnalyticsR/blob/master/R/shiny-modules.R#L84 to remove empty rows in the data.frame.

**Comment by MarkEdmondson1234** [comment]
I wasn't sure if this may break some rows so I made it an option set to TRUE by default:

Allow all rows by the below
```
callModule(authDropdown, "your_id", ga_table(), rmNA=FALSE)
```
