### ISSUE TITLE
Raise warning if anti sampling fails

### ISSUE THREAD

**Issue by sdhaus** [MarkEdmondson1234/googleAnalyticsR#105]
One problem I often find is that using googleAnalyticsR with Shiny, its difficult to determine if the anti sampling worked. 

It would be good if a warning was raised, so that it can be caught and displayed to the user using showNotification.

**Comment by MarkEdmondson1234** [comment]
A R warning may be a bit over the top, but you should be able to see if a dataset is sampled by looking at the `data.frame`'s attributes.  It should have an `attr(out, "antiSampleWorked")` is `TRUE`, so if thats not there or `FALSE` you can raise a message in your shiny code.
