### ISSUE TITLE
Setup filters

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAnalyticsR#108]
Add function to setup filters

**Comment by MarkEdmondson1234** [comment]
Hi @zselinger tracking the management filter changes here

**Comment by MarkEdmondson1234** [comment]
Pull https://github.com/MarkEdmondson1234/googleAnalyticsR/pull/141

**Comment by MarkEdmondson1234** [comment]
This is all passing the tests now, looking good!  I added lots of examples to the function help, check it out - they mostly copy what are in the tests.

**Comment by zselinger** [comment]
Will do.  Thanks a million. 

I will keep an eye on any issues.

**Comment by MarkEdmondson1234** [comment]
@zselinger could you add your details to the `DESCRIPTION` file?

**Comment by zselinger** [comment]
Sure thing

**Comment by MarkEdmondson1234** [comment]
Thanks for your help with this!  Will be in version 0.5.0 on CRAN.
