### ISSUE TITLE
Can't pull LTV data (cohortRevenuePerUser)

### ISSUE THREAD

**Issue by ericbrownaustin** [MarkEdmondson1234/googleAnalyticsR#109]
I'm trying to pull LIfetime Value data, but I'm not able to get the cohortRevenuePerUser metric to work.  I've used multiple packages and have ended up with the same error, so I think I'm not correctly querying the API.  

`ltv_data <- google_analytics_4(profile, date_range = c('2017-08-22', '2017-08-23'),
                               metrics = "ga:cohortRevenuePerUser")`

![ltv2](https://user-images.githubusercontent.com/11723172/30971444-8315516a-a42d-11e7-8766-26ed4d97d4d4.JPG)

**Comment by justinjm** [comment]
Hi @ericbrownaustin, thought I'd chime in since I've run into a similar hurdle in the past! Have you built your cohort group first before calling the API? Check out the `Cohort reports` section in `googleAnalyticsR` package website here:
http://code.markedmondson.me/googleAnalyticsR/v4.html

Just ran this code to test (swapped out the `ga_id`) and it worked for me :)

```r
## load package to extract experiment data from GA
library(googleAnalyticsR)

## authenticate (via OAuth with your user credentials)
googleAuthR::gar_auth()

## Set parameters for GA API
ga_id <- 123456789

## first make a cohort group
cohort4 <- make_cohort_group(list("Jan2016" = c("2016-01-01", "2016-01-31"), 
                                  "Feb2016" = c("2016-02-01","2016-02-28")))

## then call cohort report.  No date_range and must include metrics and dimensions
##  from the cohort list
cohort_example <- google_analytics_4(ga_id, 
                                     dimensions=c('cohort'), 
                                     cohort = cohort4, 
                                     metrics = c('cohortTotalUsers'))
```

**Comment by MarkEdmondson1234** [comment]
Thanks Justin!  @ericbrownaustin does this help your issue?

**Comment by ericbrownaustin** [comment]
@MarkEdmondson1234,

That worked perfect.  Thanks @justinjm
