### ISSUE TITLE
Documentation: max with anti_sample in google_analytics_4()

### ISSUE THREAD

**Issue by gilliganondata** [MarkEdmondson1234/googleAnalyticsR#111]
I was scratching my head that the `max` argument didn't seem to be doing anything in `google_analytics_4()`. It finally dawned on me that `anti_sample = TRUE` was the culprit.

It makes sense that just grabbing the `max` number of queries in each anti-sampling queries wouldn't work, as it may be different for each one. So, either anti-sampling with `max` needs to pull _all_ results and then post-process to the max value (which seems messy), or (recommended) it would be useful to update the function documentation to note that max has no effect if `anti_sample = TRUE`.

**Comment by MarkEdmondson1234** [comment]
Yea `order` and `max_results` don't make much sense.  I think its worth putting up in R messages when using anti_sample as there are quite a few gotchas, for instance requesting user metrics.
