### ISSUE TITLE
Support 'today' and 'yesterday' date values in anti_sample. 

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAnalyticsR#112]
As per https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/110#issuecomment-332924999

**Comment by j450h1** [comment]
This one seems pretty straightforward. I can take this one. Should I create a new branch on my fork since I'm working on a different issue as well or wait until the previous issue is resolved?

**Comment by MarkEdmondson1234** [comment]
Whatever is easiest for you, thanks!

**Comment by j450h1** [comment]
Sounds good. Thanks for the input!

**Comment by MarkEdmondson1234** [comment]
Closed in https://github.com/MarkEdmondson1234/googleAnalyticsR/pull/121
