### ISSUE TITLE
cohortRevenuePerUser metric incorrect

### ISSUE THREAD

**Issue by ericbrownaustin** [MarkEdmondson1234/googleAnalyticsR#113]
I've run the following script:
```
cohort4 <- make_cohort_group(list("Jul2017" = c("2017-07-01", "2017-07-31"), 
                                   "Aug2017" = c("2017-08-01","2017-08-31")))

cohort_example <- google_analytics_4(ga_id, 
                                      dimensions=c('cohort','acquisitionTrafficChannel'), 
                                      cohort = cohort4, 
                                      metrics = c('cohortTotalUsers','cohortRevenuePerUser'))
```

The user count matches the total given in the Lifetime Value report, however, the Revenue Per User metric is multiple factors too low.  Also, I can only get the total number of users, not the breakdown by channel.  This looks like an issue with the API to me.  Is there an issue with my query.  If not, is there a way to query for the Total Revenue metric so I can calculate myself?

**Comment by MarkEdmondson1234** [comment]
My guess is this is something to do with attribution on cohort days vs return visits via direct etc. but I'm not a big user of cohorts so a more general Google Analytics forum may give you more help.  I guess its not the library doing anything with the results here, but the API like you say.

Just to be sure you could run the same JSON query here https://developers.google.com/apis-explorer/#p/analyticsreporting/v4/analyticsreporting.reports.batchGet

If you set `options(googleAuthR.verbose = 0)` then it will write out the JSON that is passed to the API in a local file that you can paste in.

**Comment by MarkEdmondson1234** [comment]
Closing this as I reckon its an API issue rather than the library, feel free to reopen if that is not the case.
