### ISSUE TITLE
Error in checkGoogleAPIError(req): JSON fetch error: The service is currently unavailable.

### ISSUE THREAD

**Issue by TimDA-DS** [MarkEdmondson1234/googleAnalyticsR#125]
Hello Mark,

I am using the Google APi for about 4 month now and it was working very well all the time. Since last week I get the following response when trying to download a data set via the api: 

> Request Status Code: 503
Trying again: 1 of 5
Trying again: 2 of 5
Trying again: 3 of 5
Trying again: 4 of 5
Trying again: 5 of 5
All attempts failed.
Error in checkGoogleAPIError(req) : 
  JSON fetch error: The service is currently unavailable.
Error in error_check(out) : 
  JSON fetch error: The service is currently unavailable.

Can you help me on this? Authentication and everything else seems to be fine...

**Comment by MarkEdmondson1234** [comment]
Hmm 503 indicates a malformed response or a problem Google's end, but you say this happens more than once?

There have been some updates recently, so I recommend downloading the newest versions of `googleAuthR` (v0.6.0) and `googleAnalyticsR` (v0.4.2), reauthenticate again (e.g. delete the `.httr-oauth` token and try again.  If that doesn't help, please report back here with your `sessionInfo()` and the code you used to reproduce the error.

**Comment by TimDA-DS** [comment]
Thanks for the hint.

The code is still not working but after diving deeper into the error request 503, I reduced the date range from a quarterly to a monthly based date range. The API request is now working and - on a first glance -  the date seems to be accurate.

**Comment by MarkEdmondson1234** [comment]
That sounds like you are using anti sampling?  If so, for big complicated queries try putting the `slow_fetch` flag on, which slows it down so 503 errors are rarer.

**Comment by TimDA-DS** [comment]
Yes, I do.
Using `slow_fetch` solved this issue. 
Thanks a lot for your quick replies.
