### ISSUE TITLE
Authentication options didn't match existing session token and not interactive session so unable to manually authenticate

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAnalyticsR#126]
This occurs in RMarkdown documents using `ga_auth` that have updated to `googleAuthR` 0.6.0

Due to dropped support for options = `httr_oauth_cache = TRUE` somewhere this is set in RMarkdown, when it is set instead to `httr_oauth_cache = ".httr-oauth"` 

For now the fix is to instead use `googleAuthr::gar_cache(".httr-oauth")`, assuming `.httr-oauth` if your cache token file.

**Comment by DChen721** [comment]
Hi, I've been encountering this issue as well when attempting to run my googleAnalyticsR script automatically via taskscheduleR.  Do you know how to do a workaround for taskscheduleR, or would the above suggestion be ubiquitous?  Thanks!

**Comment by MarkEdmondson1234** [comment]
From now on GitHub it also works via ga_auth(".httr-oauth") or any other name you want to call the cache file. This makes it much easier to swap to other authentication accounts.

**Comment by RonGuymon** [comment]
Thanks, Mark. I just built a docker image that uses googleAnalyticsR from GitHub, and I verified that your solution works. Namely, ga_auth(".httr-oauth") makes it possible to authenticate in a non-interactive session.

**Comment by MarkEdmondson1234** [comment]
Thanks a lot @RonGuymon - so this is now in `googleAuthR 0.6.2` 

Say you have for some reason two emails associated with two different GA accounts, maybe different client Ids.  You can now create a cache token for both via:

```r
ga_auth("token1.oauth")

...do stuff with account 1...

ga_auth"token2.oauth")

..do stuff with account 2..
```

Before now this would have involved a bit more hassle setting client ids etc.

**Comment by DChen721** [comment]
I'm still encountering issues...When I try running the task using Windows Task Scheduler I get this error:

> 2017-11-16 09:23:06> No httr_oauth_cache file found at .httr-oauth - creating new file.
> Error: Authentication options didn't match existing session token and not interactive session
>            so unable to manually reauthenticate

Here's the setup options I'm using in my code:

```
options(httr_oauth_cache = TRUE)
gar_auth(token = ".httr-oauth")
```

What am I doing wrong?

**Comment by MarkEdmondson1234** [comment]
Don't set `options(httr_oauth_cache = TRUE)`

**Comment by MarkEdmondson1234** [comment]
Also make sure you have latest `googleAuthR` and the `googleAnalyticsR`

**Comment by DChen721** [comment]
Okay, here are the setup options I'm using now:
```
options(httr_oauth_cache = FALSE)
gar_auth(token = ".httr-oauth")
```
I'm still getting this error though:
>2017-11-16 09:42:10> No httr_oauth_cache file found at .httr-oauth - creating new file.
>Error: Authentication options didn't match existing session token and not interactive session
>          so unable to manually reauthenticate

I'm using `googleAuthR` v. 0.6.2 and `googleAnalyticsR` v. 0.4.2

**Comment by MarkEdmondson1234** [comment]
I would reauthenticate, delete any tokens you have, restart R then:

```
library(googleAnalyticsR)
ga_auth("myfile.oauth")
```

That should create your auth file ok, at "myfile.oauth" - then within your scheduled script have the same two lines for authentication.  Make sure the file location is recognised from where the script is running, e.g. you may want to use an absolute file path "C://gggg/sdsdsd.oauth"

**Comment by thibSEO** [comment]
Hi Mark,

My Shiny Application didin't work. 
There are my logs error.
No auto-refresh of token due to differing options, manual re-authentication required
Warning: Error in : Authentication options didn't match existing session token and not interactive session
 so unable to manually reauthenticate
Stack trace (innermost first):
80:make_new_token
79: googleAuthR::gar_auth
78: scr_auth

I don't have new window to login me with my account. 

How to use that ?

Thanks

**Comment by MarkEdmondson1234** [comment]
I need to see the code you are using really, is it a multi-user app or a single user one?

I guess you need to just make sure you have latest `googleAuthR` and then issue `scr_auth("sc.auth")` instead locally, generating the `sc.auth` file, then upload that with your Shiny app.

**Comment by thibSEO** [comment]
It's for a single user app. 

I'm using googleAuthR v. 0.6.2 and googleAnalyticsR v. 0.4.2.

Where can i send you my code ? Here ? It's a little big :)

**Comment by MarkEdmondson1234** [comment]
Just the authentication part is needed, but it sounds like the solution above will do it, although I don't know why you are using `scr_auth()` if its a googleAnalyticsR API request, it should be `ga_auth()`

**Comment by thibSEO** [comment]
ga_auth function doesn't work to. To connect on my account, I use this code 
    gar_auth()
    account_list <- google_analytics_account_list()
    print(account_list)
If you want, I can send all my code.
