### ISSUE TITLE
(non-auto) batching?

### ISSUE THREAD

**Issue by gdoteof** [MarkEdmondson1234/googleAnalyticsR#128]
Sometimes we need to run the same pull on several different segments; which can end up being hundreds of individual pulls.

Is there, given a list of `google_analytics_4` calls, a way to combine them into a multi-query batchGet with this library?

**Comment by MarkEdmondson1234** [comment]
There is a limitation in the API v4 that only lets you batch requests that have the same segment, viewId or dateRange, so unfortunately not your use case. 

The v3 API (`google_analytics`) is more flexible in batching so for example you can use the `multi_account_batching` to pull 10 viewIds at once, but multi-segments are supported in the library.  However, in theory you should be able to use the same batch functions from `googleAuthR` to build your request and send them.

The relevant code is:

```r
  # all_data <- list()
  ga <- gar_api_generator(paste0("https://www.googleapis.com/analytics/v3/data/",
                                 type),
                          "GET",
                          pars_args = ga_pars,
                          data_parse_function = parse_google_analytics)
  
  if(multi_account_batching){
    myMessage("Fetching all ids at same time (max 10 per API call)", level = 3)
    all_data <- googleAuthR::gar_batch_walk(ga,
                                            walk_vector = id,
                                            gar_pars = ga_pars,
                                            pars_walk = 'ids',
                                            data_frame_output = FALSE,
                                            batch_size = 10)
    all_data <- unlist(all_data, recursive = FALSE, use.names = FALSE)
    names(all_data) <- id
    
```

You could adapt the `gar_batch_walk` to walk through a vector of segment definitions instead, but would require you to fork the repo and change the code, if you are up for it :)

The only other option may be to use something like [`futures`](https://cran.r-project.org/web/packages/future/index.html) to multi-thread your code and send many requests at once in separate R processes.  Make sure to keep below the concurrent GA API limits though, which is 10.

**Comment by gdoteof** [comment]
Thanks @MarkEdmondson1234 this is extremely helpful; it looks like `gar_batch_walk` approach may be the best for our case.
