### ISSUE TITLE
Add more management API features

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAnalyticsR#135]
Things like help to setup filters, etc. 

https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/

**Comment by alistairjohnstone** [comment]
It would be great to see more management API features added. I dream about running R scripts to update settings across large GA implementations :)

**Comment by MarkEdmondson1234** [comment]
Remaining management API additions to be feature complete are:

* create/update/delete of custom variables (still not in as quite complicated)
* create/update/delete of user access
* create/update of experiments

I may even advance the version of the library to `1.0` once these get in ;)

**Comment by MarkEdmondson1234** [comment]
User management in now including batching http://code.markedmondson.me/googleAnalyticsR/reference/index.html#section-user-management

**Comment by MarkEdmondson1234** [comment]
Custom dimension creation and patching is now in via https://github.com/MarkEdmondson1234/googleAnalyticsR/commit/8343a995328969ae8610e6c5533b837362864910 - documentation on the [website for ga_custom_vars_create() etc.](http://code.markedmondson.me/googleAnalyticsR/reference/ga_custom_vars_create.html)

**Comment by MarkEdmondson1234** [comment]
AS experiments are
