### ISSUE TITLE
Authentication options didn't match existing session token and not interactive session so unable to manually authenticate

### ISSUE THREAD

**Issue by aleDsz** [MarkEdmondson1234/googleAnalyticsR#137]
Had some days that I started to have authentication problems with Google Analytics and I decided to change the way I perform the authentication in R.

I assumed that by passing in the options, the **client_id** and the **client_secret**, this problem would be solved.

In fact, when I run the script, it works perfectly. But when I program cronR to run this script, it returns me the error: **Authentication options did not match existing session token and not interactive session so can not manually authenticate**

That's my code and where the error happens:

```R
# Options
options(googleAuthR.client_id = "XXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com")
options(googleAuthR.client_secret = "XXXXXXXXXXXXXXXXXXXXX")

# Load libs
library("plyr")
library("dplyr")
library("slackr")
library("methods")
library("lubridate")
library("googleAnalyticsR")

# some code

# I created a class that performs GA extraction and when trying, it generates an error in my tryCatch
google_analytics_data <- google_analytics_service$get_data(accounts$analytics_id, analytics_dimensions, analytics_metrics, first_date, final_date, 10)
```

Any idea?

**Comment by MarkEdmondson1234** [comment]
If it works locally but not in cron, the first suspect is that the authentication file is not found form the location the scheduled script is running.  

Are you using auto-authentication? (e.g. a token pointed at in a `GA_AUTH_FILE` environment argument)

It may be clearer if you explicitly set the location using `ga_auth("full/path/to/your/token.oauth")`

Also nowadays there is only need to set the client id/secret options the first time you authenticate - on token refreshes it will set them to the same as the token itself.

**Comment by aleDsz** [comment]
I'm setting the working dir with `setwd()` which my script can find my classes, my other files and the **.httr-oauth**

Also, I'm using the 0.4.2 version from CRAN, so I don't have the **token** argument in `ga_auth` function.

And, also I will try to use the `GA_AUTH_FILE` environment argument.

**Comment by MarkEdmondson1234** [comment]
Ah ok, yes I would try the GA_AUTH_FILE first - one other thing to try is that for newest versions the `getOption("googleAuthR.httr_oauth_cache")` changed from `TRUE` to `.httr-oauth` so that may be the difference detected.  Try setting it explicitly (although this is what `ga_auth("filename")` will do for you too. )

**Comment by aleDsz** [comment]
I updated to the version that is in github and, in order not to break my applications, I used `Sys.setenv ()` to set `GA_AUTH_FILE` and solved my problem.

Do you know when it will be possible to update CRAN with this new version?

**Comment by MarkEdmondson1234** [comment]
> Sys.setenv() to set GA_AUTH_FILE

That should work with the CRAN version 0.4.2

The GitHub version has the `ga_auth()` accepting token, it'll probably be a couple of months before its on CRAN (need to build up a list of changes for non-critical updates before submission)

**Comment by aleDsz** [comment]
Anyway, thank you very much for the help.
