### ISSUE TITLE
google_analytics_4() is still used when anti_sample = true in google_analytics()

### ISSUE THREAD

**Issue by madsthom** [MarkEdmondson1234/googleAnalyticsR#140]
In anti_sample(), the google_analytics_4() is still used is there a reason for that? - I get depricated warnings when anti_sample = true in google_analytics().

**Comment by madsthom** [comment]
Changed it in my fork and it works for me, but I'm not sure about the consequences of it.

**Comment by MarkEdmondson1234** [comment]
It should be fine, it’s a bit in flux at the moment but only the warning showing should be on dev version on GitHub
