### ISSUE TITLE
gl_speech error:Invalid Token

### ISSUE THREAD

**Issue by Punitha89** [MarkEdmondson1234/googleAnalyticsR#144]
Hi,

I am trying to convert the wav file to text, i.e. audio to text. Where i am using googleLanguageR package to convert the data, for this i am using gl_speech(test_audio) method, its throwing an error saying **"2018-01-17 20:22:02> No authorization yet in this session!
2018-01-17 20:22:02> No  .httr-oauth  file exists in current working directory.  Do library authentication steps to provide credentials.
Error: Invalid token**

Please can anyone help me in debugging this issue.

**Comment by MarkEdmondson1234** [comment]
Wrong repo, issue is followed here https://github.com/ropensci/googleLanguageR/issues/27
