### ISSUE TITLE
Support 100k rows per API call up from 10k

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAnalyticsR#145]
As per https://developers.google.com/analytics/devguides/reporting/core/v3/changelog

**Comment by MarkEdmondson1234** [comment]
`Error in seq.default(from = api_max_rows * 5, to = all_rows, by = reqRowLimit) : wrong sign in 'by' argument` from https://github.com/MarkEdmondson1234/googleAnalyticsR/blob/master/R/ga_v4_get.R#L382 when fetching:

```r
gadata <- google_analytics(view_id,
                              date_range = c(sdate, edate),
                              metrics = c("pageviews"),
                              dimensions = c("pagePath"),
                              anti_sample=TRUE,
                              anti_sample_batches = 1)
```

**Comment by benkates** [comment]
Alright, it looks like when a response is sampled and over 100k rows, I'm getting this:
`2018-01-26 14:43:57> Downloaded [100000] rows from a total of [142672].
Error in value[[3L]](cond) : Sequence batch error: 
 api_max_rows: 100000
 all_rows:142672
 reqRowLimit:100000`
