### ISSUE TITLE
Anti-sampling throws error if using segment and no dimension is defined

### ISSUE THREAD

**Issue by smach** [MarkEdmondson1234/googleAnalyticsR#149]
Per discussion in Slack channel:

    metricsdf <- google_analytics_4(theID,
                                  date_range = c(start_date, end_date),
                                  metrics = “sessions”,
                                  segments = myseg,
                                  anti_sample = TRUE
     )

Returns an error: 

    Error in left_join_impl(x, y, by$x, by$y, suffix$x, suffix$y, check_na_matches(na_matches)) :
     `by` must specify variables to join by

There is no error if I add a dimension

**Comment by MarkEdmondson1234** [comment]
@smach I think this will fix it - turns out its having the segment that is throwing the error, since it adds a "segment" column that was unexpected.  Could you confirm its ok?

**Comment by smach** [comment]
@MarkEdmondson1234 Happy to test. Do you want me to check with no dimension or segment? Or install a branch version to check with dimension or segment?

**Comment by smach** [comment]
@MarkEdmondson1234 Tried all combinations of with & without segment and dimensions and anti_sample worked fine! Thanks! (I did get a warning that google_analytics_4 was deprecated and I should use google_analytics, though)

**Comment by MarkEdmondson1234** [comment]
@smach great, thank you for report and test!  Will be in next CRAN release
