### ISSUE TITLE
2018-02-07 17:25:51> No environment argument found, looked in GA_AUTH_FILE Warning message: package 'googleAnalyticsR' was built under R version 3.4.3 2018-02-07 17:25:51> No environment argument found, looked in GAR_AUTH_FILE Warning message: package 'googleAuthR' was built under R version 3.4.3 Erro: Authentication options didn't match existing session token and not interactive session            so unable to manually reauthenticate Execução interrompida  C:\Program Files\R\R-3.4.2\bin\x64>

### ISSUE THREAD

**Issue by piruvari** [MarkEdmondson1234/googleAnalyticsR#150]
Hi how are you? Please i have a problem with my automation of one script with
R
I apply the following code

library(googleAnalyticsR)
library(googleAuthR)

setwd("path where i have the .httr-oauth")
## Authenticate with an email that has access to the Google Analytics View you want to use.
options(googleAuthR.client_id = "xxxxxxx")
options(googleAuthR.client_secret = "xxxxxx")
ga_auth(new_user=FALSE)

In Rstudio is ok but when i try run in CMD of windows i have the following problem

2018-02-07 17:25:51> No environment argument found, looked in GA_AUTH_FILE
Warning message:
package 'googleAnalyticsR' was built under R version 3.4.3
2018-02-07 17:25:51> No environment argument found, looked in GAR_AUTH_FILE
Warning message:
package 'googleAuthR' was built under R version 3.4.3
Erro: Authentication options didn't match existing session token and not interactive session
           so unable to manually reauthenticate
Execução interrompida

Help please

**Comment by MarkEdmondson1234** [comment]
I would avoid using `setwd()` in your script.  Instead pass in the absolute filepath of your existing token to `ga_auth` e.g. something like

```r
library(googleAnalyticsR)
library(googleAuthR)

ga_auth("C://full_location/.httr-oauth)
```

**Comment by piruvari** [comment]
Yes. i tried it but appear this message

Error in if (any(no_auto, new_user)) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In any(no_auto, new_user) :
  coercing argument of type 'character' to logical

**Comment by MarkEdmondson1234** [comment]
Ah ok that requires the latest version on GitHub:

`remotes::install_github("MarkEdmondson1234/googleAnalyticsR")`

or install latest version of `googleAuthR` and authenticate using

`googleAuthR::gar_auth("C://full_location/.httr-oauth")

**Comment by piruvari** [comment]
Great!!!! Thanks!!!

**Comment by martin151190** [comment]
Hi, Mark, sorry for the trouble but I have a problem.

I'm working on an app that connects to the google API using the packages "googleAnalyticsR" and "RGA". The app works perfectly on my desktop, but when trying to deploy it in my local server I get the following error:

> Error : Authentication options didn't match existing session token and not interactive session
> so unable to manually reauthenticate
> Warning: Error in error_check: Authentication options didn't match existing session token and not intera
> ctive session
> so unable to manually reauthenticate
> 59: stop
> 58: error_check
> 57: fetch_google_analytics_4
> 56: google_analytics
> 52: server [/opt/shiny-server/apps/Aplicativo_Google_Analytics/server.R#20]
> Error in error_check(out) :
> Authentication options didn't match existing session token and not interactive session
> so unable to manually reauthenticate

I already tried using this (which works on my desktop):

```
ga_auth(".httr-oauth") #For Google_analytics
token<-readRDS(".ga-token.rds") #Token for Get real time
```

How can I correct this error???

Martín

**Comment by MarkEdmondson1234** [comment]
It looks like the clientID options are not the same as you have via desktop, the scopes and clientID/secret need to be the same.  What version are you running though because this should be less likely to happen in recent versions of the library. (can you run `sessionInfo()` and `getOption("googleAuthR.client_id")`  locally and on the server just before authentication to compare them?)
