### ISSUE TITLE
"googleAuthUI()" Function

### ISSUE THREAD

**Issue by Sathurraman** [MarkEdmondson1234/googleAnalyticsR#156]
## What goes wrong
I used this "googleAuthUI" function before to get authentication with google account for R Shiny web app. But nowadays I couldn't find this function.

Will you help me how can I get a google account authentication for google analytics in R shiny web app

## Actual output

Before you run your code, please run:

`options(googleAuthR.verbose=2)` and copy-paste the console output here.  
Check it doesn't include any sensitive info like auth tokens or accountIds - you can usually just edit those out manually and replace with say `XXX`

## Session Info

Please run `sessionInfo()` so we can check what versions of packages you have installed

**Comment by MarkEdmondson1234** [comment]
Its still there, have you followed this [example](http://code.markedmondson.me/googleAnalyticsR/shiny.html)?  Perhaps you can't find it as it lies in the `googleAuthR`package.

**Comment by Sathurraman** [comment]
Thank you @MarkEdmondson1234  I got it. 👍
