### ISSUE TITLE
i have a problem with my code in rscript.exe but in my Rstudio is ok. What happen?

### ISSUE THREAD

**Issue by piruvari** [MarkEdmondson1234/googleAnalyticsR#158]
## What goes wrong

2018-02-21 17:36:29> Default Google Project for googleAnalyticsR is now set.
 This is shared with all googleAnalyticsR users.
 If making a lot of API calls, please:
 1) create your own Google Project at https://console.developers.google.com
 2) Activate the Google Analytics Reporting API
 3) set options(googleAuthR.client_id) and options(googleAuthR.client_secret)
 4) Reload the package.
2018-02-21 17:36:29> Set API cache
2018-02-21 17:36:29> No environment argument found, looked in GA_AUTH_FILE
2018-02-21 17:36:29> No environment argument found, looked in GAR_AUTH_FILE
Erro: Authentication options didn't match existing session token and not interac
tive session
           so unable to manually reauthenticate
Execução interrompida

## Actual output

Before you run your code, please run:

`options(googleAuthR.verbose=2)` and copy-paste the console output here.  
Check it doesn't include any sensitive info like auth tokens or accountIds - you can usually just edit those out manually and replace with say `XXX`

## Session Info

Please run `sessionInfo()` so we can check what versions of packages you have installed

**Comment by MarkEdmondson1234** [comment]
I need some more information to help, I guess the Rscript is running in a different folder that when in RStudio, I suggest generating a authentication cache file (via `ga_auth()`) then setting it to the environment arguments `GA_AUTH_FILE` will ensure that wherever you run your script from, authentication will be performed.  Also see website on authentication and setup http://code.markedmondson.me/googleAnalyticsR/setup.html

**Comment by piruvari** [comment]
Yes I wrote gar_auth("path") but I have one error like error: unexpected
símbolo "c:\U"
I ran this code in studio I don't have any problem in another computer too.

The problem is no server I installed rstudio e r 3.4.3. the version maybe
is the problem??

Please help

Em 21 de fev de 2018 6:54 PM, "Mark" <notifications@github.com> escreveu:

I need some more information to help, I guess the Rscript is running in a
different folder that when in RStudio, I suggest generating a
authentication cache file (via ga_auth()) then setting it to the
environment arguments GA_AUTH_FILE will ensure that wherever you run your
script from, authentication will be performed. Also see website on
authentication and setup http://code.markedmondson.me/
googleAnalyticsR/setup.html

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/158#issuecomment-367487080>,
or mute the thread

**Comment by MarkEdmondson1234** [comment]
I need the code you used to generate the token, the error `unexpected símbolo "c:\U"` suggests the windows path you specified was not correct.  In R you have to replace all `\` with `\\` in Windows file paths, according to [this SO answer](https://stackoverflow.com/questions/8425409/file-path-issues-in-r-using-windows-hex-digits-in-character-string-error)
