### ISSUE TITLE
Cohort example ignores first cohort

### ISSUE THREAD

**Issue by biologicaldynamics** [MarkEdmondson1234/googleAnalyticsR#16]
Dear Mark,

First of all, thank you for writing this great R package! I am delighted to be able to use the API v4 directly from R.

I tried out the cohort example from the vignette, but it didn't behave the way I expected.

```
## first make a cohort group
cohort4 <- make_cohort_group(list("cohort 1" = c("2015-08-01", "2015-08-01"), 
                                "cohort 2" = c("2015-07-01","2015-07-01")))

## then call cohort report.  No date_range and must include metrics and dimensions
##   from the cohort list
cohort_example <- google_analytics_4(ga_id, 
                                     dimensions=c('cohort'), 
                                     cohort = cohort4, 
                                     metrics = c('cohortTotalUsers'))
```

This only returns a value for ```cohort 2```. My first thought was that we didn't have data for cohort 1, but if I swapped the date ranges, I got only data for 2015-08-01. In fact, if I added a third row, I get the last two:

```
## first make a cohort group
cohort4 <- make_cohort_group(list("cohort 1" = c("2015-08-01", "2015-08-01"), 
                                "cohort 2" = c("2015-07-01","2015-07-01"),
                                "cohort 3" = c("2015-08-01", "2015-08-01")))

## then call cohort report.  No date_range and must include metrics and dimensions
##   from the cohort list
cohort_example <- google_analytics_4(ga_id, 
                                     dimensions=c('cohort'), 
                                     cohort = cohort4, 
                                     metrics = c('cohortTotalUsers'))
```

The above returns cohorts 2 and 3. Seems to be a simple off-by-one. I am using R 3.2.4 and I installed via ```install.packages``` today.

**Comment by biologicaldynamics** [comment]
As an update, the following works correctly:

```
cohort4 <- make_cohort_group(list("August 2015" = c("2015-08-01", "2015-08-31"), 
                                  "July 2015" = c("2015-07-01","2015-07-31")))

## then call cohort report.  No date_range and must include metrics and dimensions
##   from the cohort list
cohort_example <- google_analytics_4(ga_id, 
                                     dimensions=c('cohort', "ga:cohortNthMonth"), 
                                     cohort = cohort4, 
                                     metrics = c('cohortTotalUsers', "ga:cohortRetentionRate"))
```

However, if I leave out the second dimension, I get the off-by-one effect described above. That is, the above returns a 7x4 table, but without the second metric, it's 1x3.

**Comment by MarkEdmondson1234** [comment]
Thanks very much for this and detective work, definitely a bug that I will look to fix ASAP.

**Comment by MarkEdmondson1234** [comment]
Well good news is that this is now fixed, bad news is that it was affecting all v4 calls, missing out the  first row.  This was due to batching add the pageToken and in my R-brain I indexed it from 1, whereas it should have been from 0.  I will submit this as a patch to the CRAN version ASAP. 

Thanks very much for the report!

**Comment by biologicaldynamics** [comment]
Thank you for developing the package!

**Comment by MarkEdmondson1234** [comment]
This is now on CRAN, version 0.1.1. 






On Tue, May 24, 2016 at 5:57 PM -0700, "David Bruce Borenstein" <notifications@github.com> wrote:










Thank you for developing the package!
