### ISSUE TITLE
Add lifetime value

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAnalyticsR#160]
https://developers.google.com/analytics/devguides/reporting/core/v4/advanced#ltv

Missed this one, for cohorts

**Comment by zselinger** [comment]
Hi, this is just a case of adding ltv metrics to the cohorts_metric_check() right? I tried this with a couple of ltv metrics and it worked. Got the same numbers as from the interface. 

I'm happy to work on this, just trying to see if I'm missing anything.
