### ISSUE TITLE
is there a function to create new remarketing audience in R

### ISSUE THREAD

**Issue by msheranga** [MarkEdmondson1234/googleAnalyticsR#161]
## What goes wrong
ga_remarketing_get() and ga_remarketing_list are exist but there is no function to create a new remarketing audience using R

**Comment by MarkEdmondson1234** [comment]
Not at the moment, but there is a general quest to add some more management API features https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/135  - it would involve implementing this guide https://developers.google.com/analytics/devguides/config/mgmt/v3/remarketing#insert

**Comment by msheranga** [comment]
Thanks. Is there way to execute R script in php file please help. then i am able to create a new remarketing audience. please help

**Comment by MarkEdmondson1234** [comment]
I don’t know how to execute R from PHP, sorry.

**Comment by msheranga** [comment]
ahh ok. can i know whether function for creating remarketing audience ongoing or not started yet?

**Comment by MarkEdmondson1234** [comment]
If you don’t mind doing some coding then the template function is here https://github.com/MarkEdmondson1234/autoGoogleAPI/blob/master/googleanalyticsv3.auto/R/analytics_functions.R - it should work under your authentication, but the returned call may need some parsing.

**Comment by MarkEdmondson1234** [comment]
How this could look:

```r
adword_list <- ga_adwords_list(123456, "UA-123456-1")
segment_list <- ga_segment_list()$items$definition

ga_remarketing_create(12345, "UA-123456-1", 
                     include = segment_list[1], exclude = segment_list[2],
                     membershipDurationDays = 100, daysToLookBack = 90)
```
