### ISSUE TITLE
segment_element object won't allow me to filter events

### ISSUE THREAD

**Issue by OscarLane** [MarkEdmondson1234/googleAnalyticsR#166]
First let me say, this is a terrific package and thank you so much for your hard work creating it. However, I'm having a little trouble achieving a certain task having followed what seems to me to be the most appropriate documentation.

I am attempting to extract information from Google Analytics on website activity for users who have triggered a custom event.

I have been using the documentation at http://code.markedmondson.me/googleAnalyticsR/v4.html (see the section called "Segments v4"). Following this, I have set up a segment_element object to filter the entries by the eventCategory name, which is "My Event Category Name" in the example below. In this example I have used an exact match, but have also tried regex to no avail.

```
se <- segment_element("ga:eventCategory",
                  operator = "EXACT",
                  type = "DIMENSION",
                  expressions = "My Event Category Name")

sv_simple <- segment_vector_simple(list(list(se)))

seg_defined <- segment_define(list(sv_simple))

segment4 <- segment_ga4("my_segment", user_segment = seg_defined)

segment_example <- google_analytics(my_id,
                                date_range = c("2018-01-01", "2018-03-15"),
                                dimensions = c("ga:eventCategory", "segment"),
                                segments = segment4,
                                metrics = c("pageViews"),
                                anti_sample = TRUE)
```

I have a list of event categories that show up in the table of results, which are not filtered to just the "My Event Category Name"  eventCategory object, rather they appear as:

```
segment     | eventCategory          | pageViews
------------------------------------------------
my_segment  | My Event Category Name | 2165817
my_segment  | Download               | 44872
my_segment  | External Links         | 1771636
etc...      | ...                    | ...
```

My understanding is that the segment_element object I have set up should filter the above table by the eventCategory column to those lines that only include My Event Category Name. So, in this case, that would be:

```
segment     | eventCategory          | pageViews
------------------------------------------------
my_segment  | My Event Category Name | 2165817
```

However, this is not the case. Does anyone have any advice as to how I should approach this to get the desired result?

**Comment by MarkEdmondson1234** [comment]
Thanks for using the package!

I think you are looking for dimension filters, and not segments for this use case.  

A filter takes an existing table, and narrows down to the rows that match your expression

e.g.

```r
dim_filter(dimension="eventCategory",operator="REGEXP",expressions="My event Category Name")
```

A segment finds all visits (or users) that had your segment element in their visit, but if a visit triggers more than one event category those will still be listed.

**Comment by OscarLane** [comment]
Hi Mark, yes that seems to have fixed things up for me! I think I was imagining the underlying table structure was something different to what it actually is, and that events were a special case (it appears that they are not).

Many thanks for your helpful suggestion!

**Comment by NateMietk** [comment]
@OscarLane Echoing Marks sentiments, this is an impressive package!  I was hoping to solicit some advice building off of Mark's question.  I have a current GA structure where there are many eventCategories with many nested eventActions and eventLabels within each.  I can access the highest level information of eventCategory as you suggested above but cannot access the nested dimensions.  As an example it looks something like:

eventCategory ('Download Data') > eventAction ('Execute Download') > eventLabel ('Data Product 1.a, Data Product 2.a, Data Product 3.a, .... Data Product 10.a')

Any suggestions on how to access those lower levels?  Thanks for any guidance!
