### ISSUE TITLE
Question: Ideal ga_auth() Setup for R Markdown website using googleAnalyticsR

### ISSUE THREAD

**Issue by gilliganondata** [MarkEdmondson1234/googleAnalyticsR#169]
## What goes wrong

I've got a website built with RMarkdown that uses `googleAnalyticsR` to pull updated data whenever I rebuild the site.

When I just run the code chunks manually, things seem to work fine.

However, when I try to knit the whole page (much less build the whole site), I get: `Error: Authentication options didn't match existing session token and not interactive session so unable to manually reauthenticate`.

I've reviewed both [#126](https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/126) and [#137](https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/137), but I'm still a little lost as to what the current and recommended approach for this is.

I feel like I'm still guessing a bit as to what the ideal/recommended setup is here:

* What to variables to include in `.Renviron`
* Best practice for generating / stashing the token (a kicker -- I've got a couple of different Google accounts I need to use, so I'm not always authenticating with the same one)
* What options -- if any -- to set (and where -- _before_ loading libraries or _after_?)
* What arguments to include in the `ga_auth()` call baked into the `.Rmd` file
* If there is a "one-time/first-time" step for running (e.g., to generate a token) and then a "every time after that"

## Steps to reproduce the problem

I've tried deleting `.httr-oauth` from my working directory, then calling `ga_auth(new_user = TRUE)` so that I get a new token, and the problem persists.

I've also tried (before and after the above) both `ga_auth()` and `ga_auth(token = ".httr-oauth")` with no luck.

I currently have the following in `.Renviron`:

`GA_CLIENT_ID = "XXXXXXXXXX-XXXXXXXXXXmp4g.apps.googleusercontent.com"`
`GA_CLIENT_SECRET = "XXXXXXXXXXXXXX4ciG"

I'm not setting _any_ options for `googleAuthR` in the RMarkdown file.

## Expected output

I expect the file to not crater when it gets to the `google_analytics()` call.

## Actual output

With `options(googleAuthR.verbose=2)` run, below is the console output when I try to knit. Is the `GA_AUTH_FILE` -- the fact that I don't have one -- the issue?

```
2018-04-14 19:46:52> Set API cache
2018-04-14 19:46:52> No environment argument found, looked in GA_AUTH_FILE
── Attaching packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 2.2.1     ✔ purrr   0.2.4
✔ tibble  1.4.2     ✔ dplyr   0.7.4
✔ tidyr   0.8.0     ✔ stringr 1.3.0
✔ readr   1.1.1     ✔ forcats 0.3.0
── Conflicts ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Creating a generic function for 'toJSON' from package 'jsonlite' in package 'googleVis'

Welcome to googleVis version 0.6.2

Please read Google's Terms of Use
before you start using the package:
https://developers.google.com/terms/

Note, the plot method of googleVis will by default use
the standard browser to display its output.

See the googleVis package vignettes for more details,
or visit http://github.com/mages/googleVis.

To suppress this message use:
suppressPackageStartupMessages(library(googleVis))


Attaching package: 'scales'

The following object is masked from 'package:purrr':

    discard

The following object is masked from 'package:readr':

    col_factor

2018-04-14 19:46:54> No local token found in session
2018-04-14 19:46:54> Auto-refresh of token not possible, manual re-authentication required
Quitting from lines 16-37 (z_setup_8_weeks.Rmd) 
Error: Authentication options didn't match existing session token and not interactive session
           so unable to manually reauthenticate
Execution halted
```

## Session Info

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16     digest_0.6.15    rprojroot_1.3-2  grid_3.4.3       plyr_1.8.4       backports_1.1.2  gtable_0.2.0     magrittr_1.5     evaluate_0.10.1  scales_0.5.0    
[11] ggplot2_2.2.1    pillar_1.2.1     stringi_1.1.7    rlang_0.2.0      lazyeval_0.2.1   rmarkdown_1.9    tools_3.4.3      stringr_1.3.0    munsell_0.4.3    yaml_2.1.18     
[21] compiler_3.4.3   colorspace_1.3-2 htmltools_0.3.6  knitr_1.20       tibble_1.4.2    
```

**Comment by MarkEdmondson1234** [comment]
Can I see what you have in the `z_setup_8_weeks.Rmd` markdown? (Or if I have access, point me at it  :) )

But first impressions if that it will be sorted if you use a custom auth cache file i.e. `ga_auth("my_token_name.oauth")` rather than rely on the default of `ga_auth()`

These lines..

```
2018-04-14 19:46:54> No local token found in session
2018-04-14 19:46:54> Auto-refresh of token not possible, manual re-authentication required
Quitting from lines 16-37 (z_setup_8_weeks.Rmd) 
Error: Authentication options didn't match existing session token and not interactive session
           so unable to manually reauthenticate
Execution halted
```

...indicate the token was not found or had different client Id/secret settings than the one found.  

A recent update made `googleAuthR` take the client id/secret from the stored cache token instead of any options set.  I guess the website may have other libraries using `.httr-oauth` (RSiteCatalyst?) that may be causing the incompatibility, so naming the cache file via `ga_auth("my_auth_file.oauth")` forces it to be a unique file.

**Comment by gilliganondata** [comment]
Interesting. It took a little doing, but what I did:

1. Deleted the token file
2. Ran `ga_auth(new_user = TRUE)` in the console
3. `.httr-oauth` got generated and plopped into my working directory.
4. The included file was actually in a subdirectory, so I renamed the token file to `.ga-httr-oauth` and moved it into that subdirectory.
5. I updated the auth call to `ga_auth(token = ".ga-httr-oauth")`

That now seems to work. I'm going to shuffle some things out of the subdirectory, though, as part of some other updates.

Would it make sense that part of the issue was my token file was getting dropped in a spot that, when I actually went to knit, it couldn't be found? <sigh>

**Comment by MarkEdmondson1234** [comment]
For the above, it should be easier to do 

1. Delete the existing token file (`.httr-oauth` I guess)
2. Run `ga_auth(token = ".ga-httr-oauth")` or the equivalent, `ga_auth(".ga-httr-oauth")`.  The latest version's default should be `ga.oauth`

Putting a . in front though you may have trouble finding it again as the file system treats them as hidden files. 

Yes running `knitr` can be weird knowing which folder it actually runs the R session that generates the HTML, enough that I tend to always run them in the root, working directory to avoid a headache.

**Comment by MarkEdmondson1234** [comment]
Sorted then?

**Comment by gilliganondata** [comment]
Oops. Yeah. Sorry about not closing.

**Comment by xslates** [comment]
@gilliganondata is this still the accepted answer? I'm having trouble figuring out how to knit a PDF document using authentication without browsers.

**Comment by MarkEdmondson1234** [comment]
Preauthenticate before knitting, then make sure to specify the token in the `ga_auth()` command e.g. in your Rmarkdown chunk near the top, have `ga_auth("ga.oauth")` that is pointing at the file "ga.oauth" file location, relative to the RMarkdown Rmd doc.

**Comment by xslates** [comment]
Thanks, for posterity, I actually managed to do this using the `ga_auth(email = "myemail@gmail.com")` after downloading a GCP service account and referencing it in the .Renviron file as explained in some documentation section that I now don't recall where it is.

- Downloaded service account JSON file
- Created .Renviron file in my home directory and added this line `GCS_AUTH_FILE="~/gpc-service.json"`
- Used the `ga_auth(email = "myemail@gmail.com")` line in the chunk

It seems to work so far, fingers crossed!

**Comment by MarkEdmondson1234** [comment]
This is using very cutting edge googleAuthR only on github but it is the future :)


________________________________
