### ISSUE TITLE
ga_v4_objects.R / order_type

### ISSUE THREAD

**Issue by incrediblemolk** [MarkEdmondson1234/googleAnalyticsR#18]
In the order_type function should this line

testthat::expect_type(field, character)

be

testthat::expect_type(field, "character")

Can't seem to get a query with this option to work.

**Comment by MarkEdmondson1234** [comment]
Ahh, I forgot to include this in my tests so it got missed ;( its an older version of the API call so wouldn't work with your fix either, but I have added it to the tests, and fixed it on the Github version coming very soon.  Thanks again for finding it.
