### ISSUE TITLE
facebook analytics connect to R

### ISSUE THREAD

**Issue by msheranga** [MarkEdmondson1234/googleAnalyticsR#184]
## What goes wrong
Hi, i am trying to connect **facebook analytics** to R like google analytics using googleAnalyticsR. is there a way to connect facebook analytics to R. 

## Actual output

Before you run your code, please run:

`options(googleAuthR.verbose=2)` and copy-paste the console output here.  
Check it doesn't include any sensitive info like auth tokens or accountIds - you can usually just edit those out manually and replace with say `XXX`

## Session Info

Please run `sessionInfo()` so we can check what versions of packages you have installed

**Comment by MarkEdmondson1234** [comment]
I think there are some insights reports using the package https://github.com/pablobarbera/Rfacebook or for Facebook ads there is https://github.com/daroczig/fbRads
