### ISSUE TITLE
Retry on 400 is not a good idea

### ISSUE THREAD

**Issue by byapparov** [MarkEdmondson1234/googleAnalyticsR#185]
## What goes wrong

400 responses are retried several times

## Steps to reproduce the problem

I am using googleAnalyticsR with DoubleClick conversions API which returns 400 if one of the transactions in the list is wrong.

You probably can write a mock that returns `400` on function call (function is created with `gar_api_generator`).

## Expected output

I would expect no retry attempts on 400 errors.

**Comment by MarkEdmondson1234** [comment]
Hi, is this actually with `googleAuthR` ?  There are no DoubleClick functions in this repo in  particular.

**Comment by MarkEdmondson1234** [comment]
It should only retry on 500 or 429 error codes 

```r
    if(grepl("^5|429",status_code)){
      try_attempts <- getOption("googleAuthR.tryAttempts")
      for(i in 1:try_attempts){
```

...but please raise an issue on `googleAuthR` https://github.com/MarkEdmondson1234/googleAuthR/issues with what you see and an example if this is not the case
