### ISSUE TITLE
Can't find image family to launch vm

### ISSUE THREAD

**Issue by taylorwhitten** [MarkEdmondson1234/googleAnalyticsR#190]
## Steps to reproduce the problem
library(googleComputeEngineR)
GCE_AUTH_FILE="/Users/taylorbrown/Google\ Cloud/<filename>.json"
GCE_DEFAULT_PROJECT_ID="<project-id>"
GCE_DEFAULT_ZONE="europe-west1-a"
vm <- gce_vm(template = "rstudio",
             name = "my-rstudio",
             username = "tay", password = "<password>",
             predefined_type = "n1-highmem-2")

## Expected output
Launched vm.

## Actual output
Token exists.
Request: https://www.googleapis.com/compute/v1/projects/rstudio-cool/zones/europe-west3-b/instances/?filter=status eq TERMINATED
Creating template VM
Token exists.
Request: https://www.googleapis.com/compute/v1/projects/google-containers/global/images/family/gci-stable/
Request Status Code: 404
JSON fetch error: The resource 'projects/google-containers/global/images/family/gci-stable' was not found
No retry attempted: The resource 'projects/google-containers/global/images/family/gci-stable' was not found
Error in checkGoogleAPIError(req) : 
  JSON fetch error: The resource 'projects/google-containers/global/images/family/gci-stable' was not found

## Session Info

Please run `sessionInfo()` so we can check what versions of packages you have installed

**Comment by MarkEdmondson1234** [comment]
Would you mind raising this on googleComputeEngine repo? And also are you defining the environment arguments in an .Renviron or just in the R Console?
