### ISSUE TITLE
Anti-sample fails in all requests due to the daily session limit is exceeded

### ISSUE THREAD

**Issue by DavidGarciaEstaun** [MarkEdmondson1234/googleAnalyticsR#196]
## What goes wrong
Anti-sampling fails in all requests. Anti-sampling fails in all requests. The problem is that on a daily basis the 500.000 sessions limit are exceeded. I understand that you can not go down to the intra-day level.

Maybe a solution for 360 accounts would be to combine antisampling with the userResourceQutoas. I think the package does not allow it right now. If you use useResourceQuotas, the anti-sample does not apply. I do not know if I am explaining correctly.
Would there be any way to solve this problem for 360 accounts in which many daily sessions are handled?

**Comment by MarkEdmondson1234** [comment]
I don’t think anti_sample should be used with useResourceQuotas, as the sampling should be gone using the quotas. Do you have a use case where you need both? What are you trying to do?

**Comment by DavidGarciaEstaun** [comment]
Hi Mark,

First of all, thanks for your quickly answer.
I am trying to export data from a GA view that has aprox. 2 million sessions per day, that produce that the anti-sample fails every day and exported data is sampled in all days.
How can I export the data without sampling? Is there any way?

Thanks in advance.

**Comment by MarkEdmondson1234** [comment]
Yes, use the `useResourceQuotas` flag, but do it with your own Google project authenticated.  Some details are [here](https://developers.google.com/analytics/devguides/reporting/core/v4/resource-based-quota) - it samples over 100M sessions rather than the standard 1M.

**Comment by DavidGarciaEstaun** [comment]
Yes, this works fine for the actual year, but if you try to extract data from more than 1 year does not work. Correct?
This is something usual to compare with de previous year for some period.

**Comment by MarkEdmondson1234** [comment]
That is true, its only available for a limited time period.  Other than that you could try setting up a [custom table](https://support.google.com/analytics/answer/2774517?hl=en) and query the exact same dimensions/metrics or if you have it BigQuery exports.  Also see [`ga_unsampled_download()`](https://github.com/MarkEdmondson1234/googleAnalyticsR/pull/139/files) that downloads the unsampled reports you make in the Web UI

**Comment by DavidGarciaEstaun** [comment]
Thanks Mark.
I think that the problem of custom tables is this:

> Analytics also adds historical data for the 30 days prior to the creation date of the table. Under normal circumstances, that historical data is available when the new unsampled data is available (in approximately 2 days).

The problem for the unsampled reports is that I can't create new one by R. 
Probably, my only solution in this case is to do it in BQ.

I do not want to waste you more time. I will update my reports to do it in BQ.

Thanks another time :)
