### ISSUE TITLE
byBatch Error

### ISSUE THREAD

**Issue by DanielLearner** [MarkEdmondson1234/googleAnalyticsR#197]
## What goes wrong
When I query with search_analytics() byBatch with a rowLimit that exceeds my actual number of rows (i.e. rowLimit=20000 when I only have 11000 rows of data) I get an error and no output: Error in rbind(deparse.level, ...) : numbers of columns of arguments do not match

## Steps to reproduce the problem
run search_analytics() byBatch with a rowLimit that exceeds my actual number of rows

## Expected output
the 11000 rows of data that do exist

## Actual output
Nothing

Before you run your code, please run:

`options(googleAuthR.verbose=2)` and copy-paste the console output here.  
Check it doesn't include any sensitive info like auth tokens or accountIds - you can usually just edit those out manually and replace with say `XXX`

Fetching search analytics for url: https://www.XXX.com/ dates: 2018-09-27 2018-09-28 dimensions: date device query page country dimensionFilterExp: device==DESKTOP page~~XXX country==usa searchType: web aggregationType: auto
Batching data via method: byBatch
With rowLimit set to 20000 will need up to [5] API calls
2018-10-01 13:19:07> Request #: 0 : 5000 : 10000
2018-10-01 13:19:14> Request #: 15000 : 20000
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
In addition: Warning messages:
1: No data found for supplied dates - returning NA 
2: No data found for supplied dates - returning NA 

## Session Info

Please run `sessionInfo()` so we can check what versions of packages you have installed

**Comment by MarkEdmondson1234** [comment]
Would you mind moving this over to the right repo?  This should be for `googleAnalyticsR` issues only.  Here is the link: https://github.com/MarkEdmondson1234/searchConsoleR/issues
