### ISSUE TITLE
Connecting R to Google analytics 

### ISSUE THREAD

**Issue by satr87** [MarkEdmondson1234/googleAnalyticsR#198]
Hi, Apologies if this isn't the correct forum to ask this question! 

I've installed googleanlyticsr and I'm now trying to run the ga_auth() to connect to my google analytics.

When I run the code, it opens up the browser with the permissions and to authorise R access to my GA account, once I select allow I then get a screen which has the message **"Please copy this code, switch to your application and paste it there"**

Once I get to this, I've no idea where in R I need to paste the generated code which has come from Google Analytics, any ideas of what I need to do?

Any help would be much appreciated, thanks in advance!

**Comment by MarkEdmondson1234** [comment]
Are you running this on a server or locally? Perhaps the video [here](http://code.markedmondson.me/googleAnalyticsR/v4.html) will help you get through the first steps.

**Comment by satr87** [comment]
Thanks for the quick response! It is being run locally, I went through the video and got up to 4 mins 20(ish), the ga_auth took me through to my google analytics and once I'd accepted all permissions, the attached page pops up with a long code. 
![image](https://user-images.githubusercontent.com/44061344/46866773-9b9c8d80-ce1a-11e8-8459-c719062eea6c.png)

I carried on to  the "account_list <- ga_account_list()" element and the error says:

Error in oauth2.0_access_token(endpoint, app, code = code, user_params = user_params,  : 
  Bad Request (HTTP 400). Failed to get an access token.

I'm assuming the code google is providing is the access token? although I'm not sure and I'm not sure where I'd paste the code in to

Thanks again!

**Comment by MarkEdmondson1234** [comment]
Something weird is going on as you should only get that if you are on a server, or perhaps you have some options of `httr`set already?  Could you report your `sessionInfo()` - also are you behind a work proxy or similar?

But if you have to use this method (which is oob authentication for your reference) then in R you should have a message "Please post in the token you get" or similar - when you get the token, go back to your R session after viewing the browser, and paste it into the R console and then authentication will complete.

But as I said above, you shouldn't need to copy-paste tokens at all normally.

**Comment by satr87** [comment]
Ah, there was an existing httr file on the laptop, I deleted this and repeated the process, all now seems to be working, really sorry for that! Thanks again for your help :)

**Comment by MarkEdmondson1234** [comment]
Nice, I would advise using RStudio projects or set your working directory at the top of the script to avoid clashes like taht, or do it on purpose using auto-authentication :)
