### ISSUE TITLE
Only returning 10,000 rows when samplingLevel is set to "WALK" and only 1,000 rows when segment used

### ISSUE THREAD

**Issue by ericbrownaustin** [MarkEdmondson1234/googleAnalyticsR#20]
When trying to use the walk option for samplingLevel, only 10,000 rows are returned for each api call.

`full <- google_analytics(profile, start = singleStart ,end = singleEnd, 
                                    metrics= "ga:sessions,ga:itemRevenue",
                                    dimensions = "ga:date,ga:dimension14,ga:dimension16,ga:medium,ga:source,ga:userType",
                                    samplingLevel = "WALK",
                                    max_results = 100000)`

![image](https://cloud.githubusercontent.com/assets/11723172/15691111/a57a7802-274c-11e6-823b-bc0b5e2f188d.png)

When adding a segment, the total drops to 1,000 per api call.

`segment <- google_analytics(profile, start = singleStart ,end = singleEnd, 
                                    metrics= "ga:sessions,ga:itemRevenue",
                                    dimensions = "ga:date,ga:dimension14,ga:dimension16,ga:medium,ga:source,ga:userType",
                                    segment = "sessions::condition::!ga:eventAction=@Create Account",
                                    samplingLevel = "WALK",
                                    max_results = 100000)`

![image](https://cloud.githubusercontent.com/assets/11723172/15691153/dba80822-274c-11e6-8ed0-fb7edca3ede6.png)

Is my script correct or is there another way to walk through the results?

**Comment by MarkEdmondson1234** [comment]
Hi @ericbrownaustin :)

First I'm surprised the calls worked as you have the `metrics` and `dimensions` in a different form to expected format, but that is good to know :)  But it possibly did affect the walk as it uses `date` as a key.

Also for now `max_results` are ignored in the walks as it downloads everything for each day.  I figured you can always subset the data afterwards.

That said, there could still be an issue when batching so could I just check with you if this still has problems:

```r
## remove max_results, put dims and metrics in expected format
full <- google_analytics(profile, 
                         start = singleStart , end = singleEnd, 
                         metrics= c("sessions","itemRevenue"), 
                         dimensions = c("date","dimension14","dimension16","medium","source","userType"), 
                         samplingLevel = "WALK")
```

The segment drop is a bit more mysterious, I will check if this is a coincidence or not.  

In that case, the segment parameter is in the expected format, but segments over WALK may not perform as expected as it will be only operating over each API call and not everything.  For this particular case it may be better to use filter instead, as from what I see it should give similar results?

```r
## remove max_results, put dims and metrics in expected format
full <- google_analytics(profile, 
                         start = singleStart , end = singleEnd, 
                         metrics= c("sessions","itemRevenue"), 
                         dimensions = c("date","dimension14","dimension16","medium","source","userType"), 
                         samplingLevel = "WALK",
                         filters = "ga:eventAction=@Create Account")
```

**Comment by ericbrownaustin** [comment]
Still getting the same results with the update string without segmentation:

![image](https://cloud.githubusercontent.com/assets/11723172/15716272/3ba6bc1a-27e7-11e6-9f77-93a0a40a7a1a.png)

The string with segmentation seems to be working past 1,000 results, but I'm not sure about past 10,000:

![image](https://cloud.githubusercontent.com/assets/11723172/15716620/a7c0942e-27e8-11e6-8150-3ad7553aa1de.png)

![image](https://cloud.githubusercontent.com/assets/11723172/15716637/bda29d1e-27e8-11e6-9973-ce340ad69207.png)

**Comment by MarkEdmondson1234** [comment]
Ah, the first is only one days worth of data.  WALK splits up the API calls per day, so only getting one call its the same as a normal fetch.  It should still then batch results then though, so I'll look at that.  

But if you want all data for that day, removing the samplingLevel = "WALK" line should do it. 

From what I see then, it should work past 10000.  It looks like its the interplay between when you are WALKing, but each WALK also batches and has more than 10000 results I need to look at.

**Comment by MarkEdmondson1234** [comment]
Its a similar principle for WALKing as this Search Console issue we talked about https://github.com/MarkEdmondson1234/searchConsoleR/issues/11

**Comment by ericbrownaustin** [comment]
Also, I"m only receiving 100 rows when using "HIGHER_PRECISION"

![image](https://cloud.githubusercontent.com/assets/11723172/15723219/18c91aba-2807-11e6-8ced-bb9a23bbc017.png)

**Comment by MarkEdmondson1234** [comment]
When not batching, set max_rows as the default is 100. 






On Wed, Jun 1, 2016 at 12:42 PM -0700, "ericbrownaustin" <notifications@github.com> wrote:












Also, I"m only receiving 100 rows when using "HIGHER_PRECISION"

**Comment by ericbrownaustin** [comment]
Is this something based on the API that can't be dealt with?  The updated script you've provided still gives the same results.

Thanks again!

**Comment by MarkEdmondson1234** [comment]
The examples above work as expected or known issues so I'm just keeping the issue list organised :)

In summary: if the date range is only 1 day then don't use samplingLevel='WALK', but do use max_results=999999 or similar to get all the results.  

If 1 day is sampled then the WALking won't help, as WALking just splits a fetch into multiple days.  In the future I may look at adding walking by hour of the day.

**Comment by ericbrownaustin** [comment]
I understand, however, the behavior is the same on my end whether I select one day or multiple days (the script selects 10k rows each day).  I was wondering if this is the expected behavior or if this something that can be changed?

Thanks

**Comment by MarkEdmondson1234** [comment]
Right, this is my existing issue here: https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/6

If a WALK day fetch is over 10000 it doesn't batch it as well.  This is what I need to fix :)

The other examples above are more just getting the right systax, e.g. use max_results = 999999 when not WALKing to activate batch, so I'm afraid for your example fetch it won't work to WALK. 

You could get around it by perhaps fetching in two separate calls, and merging the results yourself, on perhaps date.

**Comment by MarkEdmondson1234** [comment]
@ericbrownaustin This is now handled in the v4 data fetches, which will unsample very large batches now problem.  It is also implemented in a manner which sends less API hits so should be a lot quicker.  Check it ooout.

**Comment by ericbrownaustin** [comment]
I'll try it today.

Thanks for responding!

EB
