### ISSUE TITLE
Is it possible to suppress start messages?

### ISSUE THREAD

**Issue by laresbernardo** [MarkEdmondson1234/googleAnalyticsR#205]
When loading `googleAnalyticsR` I get these whole bunch of codes every time:
```
2018-10-30 23:26:37> Default Google Project for googleAnalyticsR is now set.  
 This is shared with all googleAnalyticsR users. 
 If making a lot of API calls, please: 
 1) create your own Google Project at https://console.developers.google.com 
 2) Activate the Google Analytics Reporting API 
 3) set options(googleAuthR.client_id) and options(googleAuthR.client_secret) 
 4) Reload the package.
```
Is it possible to stop that? It is quite annoying because it runs every time I load my own personal library as well. 
Hope you can help me! Thanks :)

**Comment by laresbernardo** [comment]
Screenshot... It even happens twice!
<img width="890" alt="captura de pantalla 2018-10-30 a la s 11 30 09 p m" src="https://user-images.githubusercontent.com/25909073/47766247-c51f3b00-dc9b-11e8-98d5-aa3a372bfedc.png">

**Comment by MarkEdmondson1234** [comment]
Well yes, follow the instructions in the message and it won’t appear :) there is a video guide on the website for using your own Google Cloud project.

**Comment by MarkEdmondson1234** [comment]
If you are depending on it for your package, then you can add your client-id and client-secret to the options to overwrite these.  See this code for how it is done:

 https://github.com/MarkEdmondson1234/googleAnalyticsR/blob/b7d77f5c680039ebc45e6f67f8eb85e7f58cc447/R/options.R#L4-L16

**Comment by laresbernardo** [comment]
Ok I get it. The thing here is that I am using a YML file with all credentials which are called when needed. In there I have my `ga_id`, `client_id` and `client_secret` values. I am not a security expert but I think it is not the best practice to keep those creds hardcoded. Am I right? So, back to the original question, is there a way to skip this messages?
Thanks for your super fast reply @MarkEdmondson1234

**Comment by MarkEdmondson1234** [comment]
The best way would be to use `gar_set_client()` from googleAuthR, as that should load before googleAnalyticsR loads.  

Otherwise you can set via environment arguments the client ID.  They are run before the message is created:

https://github.com/MarkEdmondson1234/googleAnalyticsR/blob/b7d77f5c680039ebc45e6f67f8eb85e7f58cc447/R/options.R#L28-L44

**Comment by MarkEdmondson1234** [comment]
Did this work?  Will close issue if so.
