### ISSUE TITLE
Include Empty Rows

### ISSUE THREAD

**Issue by NaokiOhno** [MarkEdmondson1234/googleAnalyticsR#206]
Is there an equivalent of the "include-empty-rows" feature of Core Reporting API in this package? I couldn't find it in the documentation. It would be very helpful when working with datasets with small values.

Thanks

**Comment by MarkEdmondson1234** [comment]
It is, its using the core reporting API, and its left on since I reckoned it better to be consistent and R can take care of duplicates itself.  See the code here: https://github.com/MarkEdmondson1234/googleAnalyticsR/blob/master/R/ga_v4_get.R#L200
