### ISSUE TITLE
ga_unsampled_download throws an error

### ISSUE THREAD

**Issue by paulchertov** [MarkEdmondson1234/googleAnalyticsR#208]
## What goes wrong
ga_unsampled_download throws:

Error in if (report$downloadType != "GOOGLE_DRIVE") { : 
  argument is of length zero

## Steps to reproduce the problem

account <- "smth"
property <- "smth"
view <- "smth"

df <- ga_unsampled_list(account, property, view)
\# some filtering here a <- Title of needed report
ga_unsampled_download(
  a,
  account, property, view
)
## Actual output

2018-11-08 11:52:08> Skipping token checks as using cache
2018-11-08 11:52:08> Request: https://www.googleapis.com/analytics/v3/management/accounts/XXXXXXXX/webproperties/UA-XXXXXX-X/profiles/XXXXXXX/unsampledReports/
2018-11-08 11:52:08> Making new cache
2018-11-08 11:52:08> Forgetting cache
Error in if (report$downloadType != "GOOGLE_DRIVE") { : 
  argument is of length zero

## Session Info

R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250    LC_MONETARY=Polish_Poland.1250
[4] LC_NUMERIC=C                   LC_TIME=Polish_Poland.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] httr_1.3.1             googleAuthR_0.6.3      googleAnalyticsR_0.5.0 RevoUtils_11.0.1      
[5] RevoUtilsMath_11.0.0  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18     bindr_0.1.1      magrittr_1.5     tidyselect_0.2.4 R6_2.2.2         rlang_0.2.1     
 [7] dplyr_0.7.6      tools_3.5.1      openssl_1.0.2    assertthat_0.2.0 digest_0.6.15    tibble_1.4.2    
[13] crayon_1.3.4     bindrcpp_0.2.2   purrr_0.2.5      tidyr_0.8.1      curl_3.2         memoise_1.1.0   
[19] glue_1.3.0       compiler_3.5.1   pillar_1.3.0     jsonlite_1.5     pkgconfig_2.0.1

**Comment by MarkEdmondson1234** [comment]
@j450h1 would you know the issue here?

**Comment by paulchertov** [comment]
I think the problem is
ga_unsampled_list returns df with following columns:
id, title, accountId, webPropertyId, profileId, status,  created, updated

So it definetely lacks of columns downloadType and driveDownloadDetails which are used in ga_unsampled_download

But maybe I am wrong - I am newbie in R

**Comment by MarkEdmondson1234** [comment]
No that sounds about right :) @j450h1 created the function so I will just check with him first.

**Comment by j450h1** [comment]
Sure, I can look into this one. @MarkEdmondson1234 I don't recall did you work on the ga_unsampled_list function? I'm not getting back any results currently, to try to look into this issue. Can you try with an account you have access to? Perhaps it has to do with the GA view I'm trying to pull from?

See:

https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/210

**Comment by j450h1** [comment]
> So it definetely lacks of columns downloadType and driveDownloadDetails which are used in ga_unsampled_download

I can look more into this. From what I recall, I believe these columns only appear if you have at least 1  unsampled report setup in the view you have chosen. I will look into it once I can get a list of unsampled reports as listed above. I will try to throw an error if that is the case.

**Comment by paulchertov** [comment]
I suppose I have found out reason of this problem.
I tested it through Python.
All reports that are done through interface have empty fields that connected to download. I suppose that my task (getting HUGE amount of unsampled data with 6 dimensions) can be done only through interface and can not be done through API - which is sad.

**Comment by MarkEdmondson1234** [comment]
Can you demo the problem a bit more? Where are the empty fields?  If it can export still to Google drive there is still hope :)

**Comment by MarkEdmondson1234** [comment]
As an alternative also consider the BigQuery exports or custom tables.

**Comment by paulchertov** [comment]
Thank you
I thought of much simpler workaround - just to bring some naming convention and then just get reports files from drive filtering by name template and then getting the max date value (Google creates them like: "ReportName 20181101", "ReportName 20181102").

But using BigQuery can be much more elegant way

**Comment by MarkEdmondson1234** [comment]
This is hanging around as I want a good error message to appear if the response is empty like above.

**Comment by j450h1** [comment]
Sure, I’ll work on something to tackle this scenario.

**Comment by j450h1** [comment]
@MarkEdmondson1234 The issue I'm having is all the unsampled reports I have created always return the columns - downloadType and driveDownloadDetails.

@paulchertov I'm trying to reproduce a similar report to the one you created. Could you explain how you were able to generate a report with 6 dimensions or even empty fields? 

This is the process I follow to generate an unsampled report:

1. Create a custom report as such: (as you can see I'm limited to 5 dimensions)
![image](https://user-images.githubusercontent.com/7351530/51097599-31c5b400-177a-11e9-9db7-99c0a9403a4d.png)

2. Set up this custom report to export as an unsampled report

Maybe there is another way I'm unaware of?

**Comment by j450h1** [comment]
this should be good to go now
