### ISSUE TITLE
ga_unsampled_list - not listing unsampled reports

### ISSUE THREAD

**Issue by j450h1** [MarkEdmondson1234/googleAnalyticsR#210]
## What goes wrong

Can't see list of unsampled downloads

## Steps to reproduce the problem
```
library(googleAnalyticsR)
ga_auth(new_user = TRUE)
unsampled <- ga_unsampled_list(accountId = Sys.getenv("ACCOUNTID"), 
                  webPropertyId = Sys.getenv("WEBPROPERTYID"), 
                  profileId = Sys.getenv("PROFILEID")) 
```

## Expected output
List of unsampled reports

## Actual output
```
2018-11-09 17:24:58> Skipping token checks as using cache
2018-11-09 17:24:58> Request: https://www.googleapis.com/analytics/v3/management/accounts/41810877/webproperties/UA-41810877-5/profiles/76665397/unsampledReports/
2018-11-09 17:24:58> Making new cache
2018-11-09 17:24:59> Forgetting cache
Error in o[, setdiff(names(o), c("selfLink", "kind"))] : 
  incorrect number of dimensions
Warning message:
In unsampled() :
  API Data failed to parse.  Returning parsed from JSON content.
                    Use this to test against your data_parse_function.
```

Before you run your code, please run:

`options(googleAuthR.verbose=2)` and copy-paste the console output here.  
Check it doesn't include any sensitive info like auth tokens or accountIds - you can usually just edit those out manually and replace with say `XXX`

## Session Info

Please run `sessionInfo()` so we can check what versions of packages you have installed

**Comment by MarkEdmondson1234** [comment]
404 errors are simply that the resource doesn't exist, so its suggesting the account authenticated but nothing was there when it looked.

**Comment by MarkEdmondson1234** [comment]
Is this fixed now do we think?

**Comment by j450h1** [comment]
I'm not sure. I haven't had much time to review. I should have some time later in December. Can we leave it open until then and then I can give an update?

**Comment by MarkEdmondson1234** [comment]
Sure, I'm just angling for a new CRAN release so would like this tied up before doing so.

**Comment by j450h1** [comment]
Okay, found some time today to look into this while waiting for my car in the shop on my day off : ) Anyways, looking at the particular view I'm currently pulling from looks like there are no unsampled reports currently setup. My current hypothesis is the error message is due to the fact that an empty object is returned. I just setup an unsampled report and will report back soon if this is indeed the case.

**Comment by j450h1** [comment]
Bingo! That's what it was. Now when there is at least 1 unsampled report, this error message is gone and the dataframe with the list of unsampled reports is returned. Can you incorporate some sort of check in this function to account for that case?

**Comment by MarkEdmondson1234** [comment]
I think this is fixed now, try it out.

**Comment by j450h1** [comment]
Yes, it's fixed now. Thanks!

```
unsampled <- ga_unsampled_list(accountId = Sys.getenv("ACCOUNTID"), 
                               webPropertyId = Sys.getenv("WEBPROPERTYID"), 
                               profileId = Sys.getenv("PROFILEID")) 
```

This is what is returned:

2018-12-10 11:55:14> No results found for username: jsohi@cardinalpath.com

```
> unsampled
data frame with 0 columns and 0 rows
```

**Comment by MarkEdmondson1234** [comment]
Great :)
