### ISSUE TITLE
Uninformative error if ga_auth() not run

### ISSUE THREAD

**Issue by hadley** [MarkEdmondson1234/googleAnalyticsR#219]
```R
library(googleAnalyticsR)
#> 2019-01-06 08:47:55> Default Google Project for googleAnalyticsR is now set.  
#>  This is shared with all googleAnalyticsR users. 
#>  If making a lot of API calls, please: 
#>  visit: https://bit.ly/2Evk6hn 
#>  for instructions on setting your own Google Project 
#> 2019-01-06 08:47:55> Set API cache
#> 2019-01-06 08:47:55> No environment argument found, looked in GA_AUTH_FILE
ga_account_list()
#> Token cache file: .httr-oauth
#> Request failed [401]. Retrying in 1.2 seconds...
#> Request failed [401]. Retrying in 1 seconds...
#> 2019-01-06 08:47:58> Request Status Code: 401
#> Scopes: https://www.googleapis.com/auth/analytics https://www.googleapis.com/auth/analytics.readonly https://www#> .googleapis.com/auth/analytics.manage.users.readonly https://www.googleapis.com/auth/analytics.edit https://www#> .googleapis.com/auth/analytics.manage.users https://www.googleapis.com/auth/analytics.user.deletion
#> App key: 289759286325-da3fr5kq4nl4nkhmhs2uft776kdsggbo.apps.googleusercontent.com
#> Method: new_token
#> Error: API returned: Login Required
```

Is there some reason you can't just run `ga_auth()` automatically?

**Comment by MarkEdmondson1234** [comment]
Thanks for all the feedback :)

Yes, this I know is different from the behaviour of `googlesheets`etc.  

I found the management of working with lots of separate Google Analytics accounts very confusing for myself and others if all the API functions authenticate automatically, in particular as a very common workflow is to also be authenticated with BigQuery and Search Console etc.  In the long run it seemed better to make authentication explicit in the function, and to also remove the `cache=TRUE` option to only let named authentication cache files.

e.g. To switch from home to work accounts I have `ga_auth("home.oauth")` vs `ga_auth("work.oauth")`

The option to auto authenticate is there for less frictionless authentication - there the authentication is loaded on package load, by putting the cache file in a `GA_AUTH_FILE` environment argument.  That way the code above would work as expected. 

But I can definitely update the error to be more descriptive of what is expected, which is implemented for some of the other Google API libraries.

**Comment by hadley** [comment]
That will be remedied in gargle, which gives you much greater control over authentication. 

An error message would be a big improvement, but it would be great if you looked at gargle and gave us feedback on whether or not that met your needs.

**Comment by MarkEdmondson1234** [comment]
This is all sorted out now we are using `gargle` as the backend - it will trigger a flow if you are not authenticated already.
