### ISSUE TITLE
Only display project info when calling ga_auth()

### ISSUE THREAD

**Issue by hadley** [MarkEdmondson1234/googleAnalyticsR#224]
Currently you get a lot of information when loading the package:

```R
library(googleAnalyticsR)
#> 2019-01-06 11:54:32> Default Google Project for googleAnalyticsR is now set.  
#>  This is shared with all googleAnalyticsR users. 
#>  If making a lot of API calls, please: 
#>  visit: https://bit.ly/2Evk6hn 
#>  for instructions on setting your own Google Project
#> 2019-01-06 11:54:32> Set API cache
#> 2019-01-06 11:54:32> No environment argument found, looked in GA_AUTH_FILE
```

I think it would be more appropriate to display this when initiating auth, so that (e.g.) you don't trigger it when referring to package data:

``` r
nrow(googleAnalyticsR::meta)
#> 2019-01-06 11:56:59> Default Google Project for googleAnalyticsR is now set.  
#>  This is shared with all googleAnalyticsR users. 
#>  If making a lot of API calls, please: 
#>  visit: https://bit.ly/2Evk6hn 
#>  for instructions on setting your own Google Project
#> 2019-01-06 11:56:59> Set API cache
#> [1] 534
```

**Comment by MarkEdmondson1234** [comment]
Yes it could move there.  It is meant to be a bit annoying to nudge folks over to using their own Google Project as the quota on the shared project kept getting tripped, which although got increased is on track to happen again in the next couple of months.

**Comment by MarkEdmondson1234** [comment]
I think this is largely solved now, mostly through this commit of googleAuthR https://github.com/MarkEdmondson1234/googleAuthR/commit/24ea6c9dc034ab9041ae760627b87ef29c8aaf19
