### ISSUE TITLE
ga_custom_vars_list requires rights that seem to be unnecessary in the UI/ according to API reference

### ISSUE THREAD

**Issue by martijnvv** [MarkEdmondson1234/googleAnalyticsR#230]
## What goes wrong
ga_custom_vars_list requires rights that seem to be unnecessary in the UI/ according to API reference:
https://www.googleapis.com/auth/analytics.manage.users https://www.googleapis.com/auth/analytics.user.deletion

According to GA API reference this is not required:
https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/customDimensions/list

## Expected output
Would it be possible to run this query with these api access rights?

**Comment by MarkEdmondson1234** [comment]
Yes the scopes are set at the moment so all functions can be used in the package, but individual functions don't need them to be so broad. 

You can set the scopes yourself when using `googleAuthR::gar_set_client()` or setting directly via `options(googleAuthR.scopes.selected)` - it will require a re-authentication with a new cache file.  In that latter case it would be something like:

```r
library(googleAnalyticsR)
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/analytics.readonly")
ga_auth("readonly.oauth")
```

**Comment by MarkEdmondson1234** [comment]
This can be sorted via the new client setting scopes functions via `gargle`
