### ISSUE TITLE
Include data outcome functions

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAnalyticsR#234]
**Is your feature request related to a problem? Please describe.**
How do you do advanced analysis on GA data once you have it?  Perhaps we can offer a platform to provide data science action from the outputs of the data fetches

**Describe the solution you'd like**
A suite of functions that can call Tensorflow models, API endpoints etc with your data to output solutions such as attribution modelling, anomaly detection, content recommendations, etc.

**Describe alternatives you've considered**
Create a separate library with solutions that can come with pre-trained models, or keep relying on the existing help articles scattered through the web such as my blog and the links on the website homepage.

**Additional context**
Try and make it easy for others to add solutions, so we are talking about a framework that is easy to slot into - something like

```r
#' @param gadata The data from an API call
#' @param required_columns What dimensions and metrics are required
#' @param model An API endpoint or a model binary format, TBD
#' @param ... Other parameters passed to the model
ga_model <- function(gadata, required_columns, model, ...){}
```

**Comment by IronistM** [comment]
This is really interesting! I have some functions on [googleAnalyticsProphetR](https://github.com/IronistM/googleAnalyticsProphetR) based on Twitter's AnomalyDetection and Prophet that I could offer.

I'd go with a separate package (`googleAnalyticsModelleR`?) for better isolation and dependencies handling.

**Comment by MarkEdmondson1234** [comment]
Nice, I hadn't seen that before!  Will check it out. 

I think it would involve setting up a standard input/output in `googleAnalyticsR` but be able to call model functions from anywhere, so for instance:

```r
ga_model(gadata, c("date","metric"), model = googleAnalyticsProphetR::predict_me)
```

**Comment by MarkEdmondson1234** [comment]
Be nice if this created Shiny modules that you can use to build a custom Shiny dashboard easily.

**Comment by IronistM** [comment]
I think that something like the [exploratory.io's](https://github.com/exploratory-io/exploratory_func) function repo would be the best option to go : 

- people will contribute functions without going through package creation
- data preparation would undergo the function's requirements'this makes sense because which might not be in the end-user's knowledge in advance
- in that case tests would be easier to run and maintened; offering consistency to the user.

I will start a repo for the sake of testing and let's see how it goes.

**Comment by IronistM** [comment]
Let's go on it [here](https://github.com/IronistM/googleAnalyticsModelR/).

**Comment by MarkEdmondson1234** [comment]
Cool!  I have something started in [this branch](https://github.com/MarkEdmondson1234/googleAnalyticsR/tree/ga-platform), just testing it out

**Comment by MarkEdmondson1234** [comment]
I would love to just be able to plugin all of exploratory-io's premade functions if possible.

**Comment by IronistM** [comment]
I think that adding data preparation, reshaping and validation steps in these functions is all needed minus some logic addition in some points.

**Comment by MarkEdmondson1234** [comment]
Got something working, how does this look for an API?

```r
 get_model_data <- function(viewId, 
                           date_range = c(Sys.Date()- 300, Sys.Date()), 
                           ...){
   google_analytics(viewId, 
                    date_range = date_range, 
                    metrics = "sessions", 
                    dimensions = "date", 
                    max = -1)
 }

 decompose_sessions <- function(df, ...){
   web_data_ts <- ts(df$sessions, frequency = 7)
   d <- decompose(web_data_ts)
   list(decom = d, plot = plot(d))
 }
 
 decomp_ga <- ga_model_make(get_model_data,
                            required_columns = c("date", "sessions"),
                            model_f = decompose_sessions)
 
 # fetches data and outputs decomposition
 ga_model(81416156, decomp_ga)
 
 # save the model for later
 model_location <- "inst/models/decomp_ga.gamodel"
 ga_model_save(decomp_ga, filename = model_location)
 
 # can load model from file
 ga_model(81416156, model_location)
 
 # load model and use again
 model2 <- ga_model_load(model_location)
 
 ga_model(81416156, model2)
```

**Comment by IronistM** [comment]
Seems efficient to me; the in between function (`decompose_sessions`) can be something like `exploraratory::exploratory_function`.

**Comment by MarkEdmondson1234** [comment]
I'll put the platform stuff in this library, but the models themselves (aside some examples) will sit in the other
https://github.com/MarkEdmondson1234/googleAnalyticsR/commit/c03acd9fa9c9f83a6aa49bd20903991929ebfc01

**Comment by MarkEdmondson1234** [comment]
This is looking pretty sweet now, the model functiosn create Shiny modules for you:

```r
library(shiny)
library(googleAuthR)
library(googleAnalyticsR) 

gar_set_client(web_json = "ga-web-client.json",
               scopes = "https://www.googleapis.com/auth/analytics.readonly")

# loads a pre-existing model
model <- ga_model_example("decomp_ga.gamr", location = "googleAnalyticsR")

## ui.R
ui <- fluidPage(title = "googleAnalyticsR Test Deployment",
                
      authDropdownUI("auth_menu"),
      h2("Model Description"),
      textOutput("model_description"),
      h2("Model Output"),
      model$shiny_module$ui("model1")
      
)

## server.R
server <- function(input, output, session){

  gar_shiny_auth(session)
  
  al <- reactive(ga_account_list())
  view_id <- callModule(authDropdown, "auth_menu", ga.table = al)
  output$model_description <- renderText(model$description)
  callModule(model$shiny_module$server, "model1", view_id = view_id)

}

shinyApp(gar_shiny_ui(ui, login_ui = silent_auth), server)
```

**Comment by MarkEdmondson1234** [comment]
Got some docs up now - the format has changed a bit from a few weeks ago but I needed to do that to make the Shiny stuff work http://code.markedmondson.me/googleAnalyticsR/articles/models.html
