### ISSUE TITLE
Send userIP parameter in every API request

### ISSUE THREAD

**Issue by DavidGarciaEstaun** [MarkEdmondson1234/googleAnalyticsR#235]
Hi,

Is there any way to send the userIP  parameter in all API request via this package?

Google says that there is a limitation of 10 api request by IP fot the api:
https://developers.google.com/analytics/devguides/config/mgmt/v3/limits-quotas

In our company, on all monday morning different persons request to the API by the same IP. This is traduced in errors on the the query responses and also on the reports.

Thanks for your help.

**Comment by MarkEdmondson1234** [comment]
I have not seen this before so not yet, but this can be added.  But also make sure it is the ip limit you are triggering, as perhaps it could be the 10 API requests per sec per property, or something like that.

What functions in particular are triggering the quota, `google_analytics()` or one of the management API functions?

**Comment by DavidGarciaEstaun** [comment]
Hi Mark,

This is the only limitation that makes sense to me. I've been reviewing the other limitations and I think the IP limitation is the only one that may be affecting us.
No more people are accessing those properties.

The function that we are using is the google_analytics().

Thanks Mark.

**Comment by MarkEdmondson1234** [comment]
`userIP` is not available on v4 API calls but `quotaUser` is https://developers.google.com/analytics/devguides/reporting/core/v4/parameters

By default this will be the user's name as defined by `Sys.info()[["user"]]` which will suit for most purposes I think.  If you want to change it though you can do so via setting `options("googleAnalyticsR.quotaUser")` which will send a message on fetch eg.

```r
google_analytics(1234567, date_range = c("30daysAgo", "yesterday"), metrics = "sessions")
#2019-02-22 13:37:09> Downloaded [1] rows from a total of [1].
#  sessions
#1    35047
options("googleAnalyticsR.quotaUser" = "test_user")
google_analytics(1234567, date_range = c("30daysAgo", "yesterday"), metrics = "sessions")
#2019-02-22 13:37:44> Fetching API under quotaUser: test_user
#2019-02-22 13:37:44> Downloaded [1] rows from a total of [1].
#  sessions
#1    35047
```

**Comment by MarkEdmondson1234** [comment]
TODO: Implement it for management API functions
https://developers.google.com/analytics/devguides/config/mgmt/v3/parameters

**Comment by DavidGarciaEstaun** [comment]
Hi Mark and thanks for your quick answer.
If the "quotaUser" is already being sent in previous versions of the package and can be any text string unrelated to the Google account, I think there must be something else that may be affecting the quotas.
Some API requests fail on Monday from the first moment and, as commented, are the first that was made with my user.

**Comment by MarkEdmondson1234** [comment]
To be clear, the users will need to install the newest version of the library to see this new feature:

```
remotes::install_github("MarkEdmondson1234/googleAnalyticsR")
```

Is that the case?

**Comment by DavidGarciaEstaun** [comment]
Sorry Mark, I didn't understnad you. I am going to install the last version and try it for the next few days.

**Comment by DavidGarciaEstaun** [comment]
It seems that this new feature solve our problems. 
Thank you so much.

**Comment by MarkEdmondson1234** [comment]
Great!
