### ISSUE TITLE
Data downloads with 0 rows without sampling data

### ISSUE THREAD

**Issue by Alexander-Turubara** [MarkEdmondson1234/googleAnalyticsR#238]
## What goes wrong
In GA I've created a 4 segment with coditions and sequences. 3 of them download anti-sampling data for 3 months and one shows 0 rows, but in the GA interface I see all the stat. Also, when I choose one day, where I have the data in GA, R download to me without any problems. 

## Steps to reproduce the problem
sdate <- "2018-11-01"
fdate <- "2019-01-31"
sbatch <- 1

segment_for_call_1.1 <- "gaid::QtXC_vFbSSGafbRnc0DOzQ"

seg_obj_1.1 <- segment_ga4("product transfer / bulk search", segment_id = segment_for_call_1.1)

ga_auth()

gadata1.1 <- google_analytics(ga_id, date_range = c(sdate, fdate),
                              metrics = c("ga:itemQuantity", "ga:uniquePurchases", "ga:transactionRevenue"),
                              dimensions = c("ga:channelGrouping", "ga:fullReferrer", "ga:landingpagePath"),
                              #dim_filters = fc1,
                              #met_filters = fc2,
                              #order = my_order,
                              segments = seg_obj_1.1,
                              anti_sample = TRUE,
                              anti_sample_batch = sbatch)

## Expected output
Some rows)

## Actual output

2019-02-28 13:24:10> anti_sample set to TRUE. Mitigating sampling via multiple API calls.
2019-02-28 13:24:10> Finding how much sampling in data request...
2019-02-28 13:24:12> Downloaded [0] rows from a total of [].
2019-02-28 13:24:12> No sampling found, returning call
2019-02-28 13:24:16> Downloaded [0] rows from a total of [].

Before you run your code, please run:

`options(googleAuthR.verbose=2)` and copy-paste the console output here.  
Check it doesn't include any sensitive info like auth tokens or accountIds - you can usually just edit those out manually and replace with say `XXX`

## 'API Data failed to parse' diagnostics

If you have an error starting with:

`API Data failed to parse.`

* Please install googleAuthR >v0.7.9000:

```r
remotes::install_github("MarkEdmondson1234/googleAuthR")
```

* Restart the R session and run your bugged code.
* It should write a file called `gar_parse_error.rds` to your working directory.
* Run the below to output some diagnostic information and paste the response here.

```r
googleAuthR::gar_debug_parsing("gar_parse_error.rds")
```

## Session Info

Please run `sessionInfo()` so we can check what versions of packages you have installed

**Comment by MarkEdmondson1234** [comment]
My guess is the segments are user scoped - do the calls work without anti_sample? I don’t think the way anti_sanple breaks up calls into smaller date chunks will work with some segments, but can’t tell from your example what the segment definition is.

**Comment by MarkEdmondson1234** [comment]
Please reopen if the above doesn't solve your issue.
