### ISSUE TITLE
user activity api: Error in gar_api_page

### ISSUE THREAD

**Issue by papageorgiou** [MarkEdmondson1234/googleAnalyticsR#245]
This is likely a known issue as I can see a related note after giving the install_github("MarkEdmondson1234/googleAnalyticsR") command - but just in case.
This is indeed the error that appears when running the ga_clientid_activity function.
Error in gar_api_page(u, page_f = page_user_activity, page_method = "body",  : 
  unused argument (body_list = body). 
Not urgent issue by any means, I was just testing.

**Comment by MarkEdmondson1234** [comment]
I just ran into this myself, and its due to needing the latest version of `googleAuthR`.  I added it to the [docs](http://code.markedmondson.me/googleAnalyticsR/articles/user-activity.html) but see here too:

> At the moment it is available on the dev version of googleAnalyticsR >= 0.6.9000 and needs googleAuthR >= 0.7.0.9000 so install via:

```r
remotes::install_github("MarkEdmondson1234/googleAuthR")
remotes::install_github("MarkEdmondson1234/googleAnalyticsR") 
```
