### ISSUE TITLE
Error in as(segments, "segment_ga4") :  no method or default for coercing “list” to “segment_ga4”

### ISSUE THREAD

**Issue by jdeboer** [MarkEdmondson1234/googleAnalyticsR#253]
## What goes wrong
Previously users were able to create multiple segments using segment_ga4 then combine them using list(). But now this generates an error "Error in as(segments, "segment_ga4") : no method or default for coercing “list” to “segment_ga4”"

Running `class(segments) <- "segment_ga4"` immediately after creating the `segments` list is a workaround.

Ideas for resolution:
Should a list of 'segment_ga4' objects have its own class name separate from an atomic `segment_ga4` object? If so, is there a function in googleAnalyticsR to create such a list object rather than the user having to create one by using `y <- list(x)` and `class(y)<-'segment_ga4'`? Or should we modify googleAnalyticsR to examine the elements of a supplied list to determine whether all of the elements are of the class 'segment_ga4'?

**Comment by MarkEdmondson1234** [comment]
If I can get a reproducible example, I'll put a test in then try out different solutions.

**Comment by adamribaudo** [comment]
Here's an example that produces the error noted above. Both `segment1 `and `segment2 `work when placed in the `google_analytics` call individually. As a list, however, the error is returned:

```
se1 <- segment_element("source", operator = "REGEXP", type = "DIMENSION", expressions = "google")
sv1 <- segment_vector_simple(list(list(se1)))
seg_defined1  <- segment_define(sv1)
segment1 <- segment_ga4("Google Traffic", session_segment  = seg_defined1)

se2 <- segment_element("source", operator = "REGEXP", type = "DIMENSION", expressions = "bing")
sv2 <- segment_vector_simple(list(list(se2)))
seg_defined2  <- segment_define(sv2)
segment2 <- segment_ga4("Bing Traffic", session_segment  = seg_defined2)

ga_sessions <- google_analytics(viewId = view_id,
                            date_range = c(start_date, end_date),
                            metrics = "sessions",
                            dimensions = c("yearMonth"),
                            segments = list(segment1, segment2),
                            anti_sample = F)
```

**Comment by MarkEdmondson1234** [comment]
Thanks for the test!  I think this is solved now in the latest version on GitHub, will be on CRAN
