### ISSUE TITLE
ga_clientid_activity

### ISSUE THREAD

**Issue by DamienCaillet** [MarkEdmondson1234/googleAnalyticsR#261]
Hi Mark,
I'm getting this error:
"could not find function "ga_clientid_activity""
I installed the latest version of googleAnaltyicsR and Gauth.
Can you help please ?
Best, Damien

**Comment by MarkEdmondson1234** [comment]
Have you restarted R in between installing the new version? If you issue ‘sessionInfo()’ you can see if you have the latest version loaded.


________________________________

**Comment by DamienCaillet** [comment]
Yes, it works now :) Thanks a lot!
