### ISSUE TITLE
Request Status Code: 403 in ga_account_list()

### ISSUE THREAD

**Issue by selesnow** [MarkEdmondson1234/googleAnalyticsR#262]
## What goes wrong
Hello, thank for package!

When i try load account list i get error `Request Status Code: 403, Error: API returned: Insufficient Permission: Request had insufficient authentication scopes.`.

But when i try load data over `google_analytics` all work correctly.

Can you help?

## Steps to reproduce the problem
``` r
library(googleAuthR)
library(googleAnalyticsR)
#> 2019-07-03 10:35:09> Default Google Project for googleAnalyticsR is now set.  
#>  This is shared with all googleAnalyticsR users. 
#>  If making a lot of API calls, please: 
#>  visit: https://bit.ly/2Evk6hn 
#>  for instructions on setting your own Google Project


# loading config
cfg <- jsonlite::fromJSON("C:/ga2mssql/test_con.json")

# set options
options(googleAuthR.client_id       = cfg$google_analytics_con$googleAuthR.client_id)
options(googleAuthR.client_secret   = cfg$google_analytics_con$googleAuthR.client_secret)
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/analytics")


# auth
googleAnalyticsR::ga_auth("C:/ga2mssql/.httr-oauth")

# set viewID
ga_id <- "ga:179511554"

# get stats
google_analytics(ga_id, 
                 date_range = c("2019-06-20", "2019-07-01"), 
                 metrics = "sessions", 
                 dimensions = "date")
#> Auto-refreshing stale OAuth token.
#> 2019-07-03 10:35:11> Downloaded [12] rows from a total of [12].
#>          date sessions
#> 1  2019-06-20    11128
#> 2  2019-06-21    10593
#> 3  2019-06-22     6973
#> 4  2019-06-23     8649
#> 5  2019-06-24    14033
#> 6  2019-06-25    13096
#> 7  2019-06-26    12115
#> 8  2019-06-27    11849
#> 9  2019-06-28    11037
#> 10 2019-06-29     7568
#> 11 2019-06-30     8885
#> 12 2019-07-01    14554

# try get accounts
account_list <- ga_account_list()
#> 2019-07-03 10:35:12> Request Status Code: 403
#> Error: API returned: Insufficient Permission: Request had insufficient authentication scopes.
```

<sup>Created on 2019-07-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.0 (2019-04-26)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  Russian_Russia.1251         
#>  ctype    Russian_Russia.1251         
#>  tz       Europe/Helsinki             
#>  date     2019-07-03                  
#> 
#> - Packages --------------------------------------------------------------
#>  package          * version    date       lib
#>  askpass            1.1        2019-01-13 [1]
#>  assertthat         0.2.1      2019-03-21 [1]
#>  backports          1.1.4      2019-04-10 [1]
#>  callr              3.2.0      2019-03-15 [1]
#>  cli                1.1.0      2019-03-19 [1]
#>  crayon             1.3.4      2017-09-16 [1]
#>  curl               3.3        2019-01-10 [1]
#>  desc               1.2.0      2018-05-01 [1]
#>  devtools           2.0.2.9000 2019-06-19 [1]
#>  digest             0.6.19     2019-05-20 [1]
#>  dplyr              0.8.2      2019-06-29 [1]
#>  evaluate           0.13       2019-02-12 [1]
#>  fs                 1.3.1      2019-05-06 [1]
#>  glue               1.3.1      2019-03-12 [1]
#>  googleAnalyticsR * 0.6.0      2018-12-21 [1]
#>  googleAuthR      * 0.8.0      2019-06-30 [1]
#>  highr              0.8        2019-03-20 [1]
#>  htmltools          0.3.6      2017-04-28 [1]
#>  httr               1.4.0      2018-12-11 [1]
#>  jsonlite           1.6        2018-12-07 [1]
#>  knitr              1.23       2019-05-18 [1]
#>  magrittr           1.5        2014-11-22 [1]
#>  memoise            1.1.0      2017-04-21 [1]
#>  openssl            1.4        2019-05-31 [1]
#>  pillar             1.4.1      2019-05-28 [1]
#>  pkgbuild           1.0.3      2019-03-20 [1]
#>  pkgconfig          2.0.2      2018-08-16 [1]
#>  pkgload            1.0.2      2018-10-29 [1]
#>  prettyunits        1.0.2      2015-07-13 [1]
#>  processx           3.3.1      2019-05-08 [1]
#>  ps                 1.3.0      2018-12-21 [1]
#>  purrr              0.3.2      2019-03-15 [1]
#>  R6                 2.4.0      2019-02-14 [1]
#>  Rcpp               1.0.1      2019-03-17 [1]
#>  remotes            2.0.4      2019-04-10 [1]
#>  rlang              0.3.4      2019-04-07 [1]
#>  rmarkdown          1.12       2019-03-14 [1]
#>  rprojroot          1.3-2      2018-01-03 [1]
#>  sessioninfo        1.1.1      2018-11-05 [1]
#>  stringi            1.4.3      2019-03-12 [1]
#>  stringr            1.4.0      2019-02-10 [1]
#>  testthat           2.1.1      2019-04-23 [1]
#>  tibble             2.1.3      2019-06-06 [1]
#>  tidyr              0.8.3      2019-03-01 [1]
#>  tidyselect         0.2.5      2018-10-11 [1]
#>  usethis            1.5.0      2019-04-07 [1]
#>  withr              2.1.2      2018-03-15 [1]
#>  xfun               0.7        2019-05-14 [1]
#>  yaml               2.2.0      2018-07-25 [1]
#>  source                         
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  Github (r-lib/devtools@8c97dee)
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#>  CRAN (R 3.6.0)                 
#> 
#> [1] D:/r_library
#> [2] C:/Program Files/R/R-3.6.0/library
```

</details>

## Actual output

Before you run your code, please run:

`options(googleAuthR.verbose=2)` and copy-paste the console output here.  
Check it doesn't include any sensitive info like auth tokens or accountIds - you can usually just edit those out manually and replace with say `XXX`

```
> options(googleAuthR.verbose=2)
> # try get accounts
> account_list <- ga_account_list()
2019-07-03 10:37:09> Request: https://www.googleapis.com/analytics/v3/management/accountSummaries/
Auto-refreshing stale OAuth token.
2019-07-03 10:37:10> Request Status Code: 403
2019-07-03 10:37:10> API returned error: Insufficient Permission: Request had insufficient authentication scopes.
2019-07-03 10:37:10> No retry attempted: Insufficient Permission: Request had insufficient authentication scopes.
Error: API returned: Insufficient Permission: Request had insufficient authentication scopes.
```

**Comment by MarkEdmondson1234** [comment]
You need /analytics.edit scopes to list accounts for some reason, not just /analytics


________________________________

**Comment by selesnow** [comment]
Thanks so much, it`s works.
`options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/analytics.edit")`

**Comment by cmason89** [comment]
Hi @MarkEdmondson1234 I am running into a similar issue and would love some help. When I am running my google anythentication request between R and Google Analytics I am running into some errors. The first time I did this I was redirected to Google to authenticate the account I wanted to connect it with. Ever since I have ran this script, it does not work and will not connect. I continue to get this same error. The process on how I am getting there is below.

We are currently using the "ga_auth()" to connect R with Google Analytics. After I do that, I run these two lines below:
ga_accounts <- ga_account_list()
View(ga_accounts)

I am then prompted with:
Auto-refreshing stale OAuth token.
ℹ 2022-09-06 09:42:14 > Request Status Code:  403
Error in `abort_http()`:
! http_403 Request had insufficient authentication scopes.
Run `rlang::last_error()` to see where the error occurred.

The error that it was associated with was in: googleAuthR:::abort_http(status_code, error) 

This is where I am confused on what to do. What does this error mean? How do I get authetication to my Google account so I don't have this error appearing? 

2 of my other team members are running the exact same script and it's coming out fine. Am I missing something here? It's something to do with the authentication I am guessing..? Would you also have some tips on how to start over (deleting the cache or history in R) so I can just start from scratch?

Thank you for all your help!!

**Comment by MarkEdmondson1234** [comment]
The scopes message means the client.id you are authenticating with (e.g. `gar_set_client()` or similar) does not have the right APIs turned on I think.  Are you setting your own client.id? Maybe run through https://code.markedmondson.me/googleAnalyticsR/articles/setup.html again to see if its all working as expected

**Comment by MarkEdmondson1234** [comment]
Also report back what `getOption("googleAuthR.scopes.selected")` is - it should be analytics based ones.

**Comment by cmason89** [comment]
@MarkEdmondson1234 Thank you for such a quick response on that! I got. anew token and I got passed it but now on the next step when I'm trying to run this piece of code below, I am getting this error: "Error: http_403 Request had insufficient authentication scopes."

This is the code I am running where it's happening:

gf_sitebydate <-google_analytics(ga_id,
                                 date_range = c("2022-01-01", "2022-08-31"),
                                 metrics = c("users","sessions","goal1","goal2","goal3"),
                                 dimensions = "date")

What's confusing is that I just authorized this above and it worked. So, how am I still missing an authentication scope? 

I'm still pretty new to all of this so any advice and help is much appreciated!! Thank you!

**Comment by MarkEdmondson1234** [comment]
Best way to help is to see all the code you are running to setup, enough I can reproduce it myself and hopefully get the same error. I guess you are setting scopes with a custom client? The default client should work out of the box.

**Comment by cmason89** [comment]
Yes, I am running for a specific client and have the ga_id line of code in there which distinguishes the different client to look at. The code I am running (up until I get the error at the bottom) is below:

install.packages("googleAnalyticsR")
install.packages("dplyr")
library("googleAnalyticsR")
library("dplyr")

ga_auth()

ga_accounts <- ga_account_list()
View(ga_accounts)

ga_id <- (view ID for client) **#I am actually putting in the view ID in there**

gf_sitebydate <-google_analytics(ga_id,
                                 date_range = c("2022-01-01", "2022-08-31"),
                                 metrics = c("users","sessions","goal1","goal2","goal3"),
                                 dimensions = "date")

**Comment by MarkEdmondson1234** [comment]
Ok, I think you are installing and loading the library in the same script. You only need to install once per release.  Restart R after you have installed, and remove top two install lines.

**Comment by cmason89** [comment]
It works!! Thank you so much for all the help!

**Comment by MarkEdmondson1234** [comment]
Glad it helped ;)

**Comment by DataSplit** [comment]
I am using the following, but I am getting an error:  

Request Status Code: 403
Error in 'abort_http()`:
! http_403 Request had insufficient authentication scopes.

----

However, I have the 
library("googleAnalyticsR")

and then doing and getting authenticated via the browser
ga_auth()

but I get the error when I use the next call:
ga_account_list()
