### ISSUE TITLE
Using authDropdown / authDropdownUI with flexdashboard[DOCS] 

### ISSUE THREAD

**Issue by gilliganondata** [MarkEdmondson1234/googleAnalyticsR#265]
# Where should be the new or corrected documentation?

I'm not sure exactly where this documentation would make the most sense to live, but I'm struggling to figure out how to get the account/property/view selection dropdowns following auth when using flexdashboard. Possibly, simply having this issue would be where it could live.

# The use case

I'm working on a flexdashboard that has a lot of Shiny embedded in it, and the first step is allowing the user to authenticate and then select a view. This worked fine in straight-up Shiny with `gar_shiny_auth()` in conjunction with `authDropdown` and `callModule`, but I'm unclear as to how to get it to work in a flexdashboard environment.

The code below is complete code for a simplified flexdashboard:

* `ga-web-client.json` is in the working directory and includes all of the pertinent information (it was downloaded from the Google console, and it works fine with the Shiny app version of the code)
* The error message returned when I `Run Document` is `Warning: Error in : Authentication options didn't match existing session token and not interactive session so unable to manually reauthenticate`

I've reviewed #126 and #169, as well as some issues around flexdashboard to no avail. I'm unclear how flexdashboard actually works with a Shiny `session` (I don't _think_ the `shinyApp()` function call is needed, but I get the same result with or without it.

`
---
title: "Flexdashboard with Google Analytics Authorization"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup}
# Load the necessary libraries. 
library(shiny)
library(flexdashboard)
library(googleAuthR)       # For authentication
library(googleAnalyticsR)  # How we actually get the Google Analytics data

gar_set_client(web_json = "ga-web-client.json",
               scopes = "https://www.googleapis.com/auth/analytics.readonly")
options(googleAuthR.redirect = "https://gilligan.shinyapps.io/regression/")

```

Column {.sidebar data-width=400}
-------------------------------------

### Select a View 

```{r config, include=FALSE}
# Account/Property/View Selection
authDropdownUI("auth_menu",
               inColumns = FALSE)
```

```{r auth}

# Create a non-reactive access token
gar_shiny_auth(session)

# Populate the Account/Property/View dropdowns and return whatever the
# selected view ID is
view_id <- callModule(authDropdown, "auth_menu", ga.table = ga_account_list)

# shinyApp(gar_shiny_ui(ui, login_ui = gar_shiny_login_ui), server)
shinyApp(gar_shiny_ui(ui, login_ui = silent_auth), server)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```
`

**Comment by MarkEdmondson1234** [comment]
Because flexdashboard is a funny hybrid of RMarkdown and Shiny you are better off using the JS based authentication since the R based auth needs to redirect to a running Shiny URL that I don't know how it is exposed in flexdashboard.  But the JS based auth should work great.  The `googleAuth_js` module is the wya there: https://code.markedmondson.me/googleAuthR/articles/google-authentication-types.html#googleauth_js-module-example
