### ISSUE TITLE
google_analytics works without with_shiny() but returns error when wrapped

### ISSUE THREAD

**Issue by aavanesy** [MarkEdmondson1234/googleAnalyticsR#267]
## What goes wrong

>     codes$data  =  with_shiny(google_analytics,
>                viewId = "", ## replace with your View ID (correct View)
>                date_range = c("2019-01-01", "2019-03-01"),
>                metrics = "sessions", 
>                dimensions = "date",
>                max = -1,
>                shiny_access_token = access_token())

## Steps to reproduce the problem

Tried v3, v4. Runs all right if I remove the shiny wrapper, however whenever I deploy the app on my server, it bugs on any request

## Actual output
`2019-08-15 11:34:07> Body JSON parsed to: {"reportRequests":[{"viewId":"ga:","dateRanges":[{"startDate":"2019-01-01","endDate":"2019-03-01"}],"samplingLevel":"DEFAULT","dimensions":[{"name":"ga:date"}],"metrics":[{"expression":"ga:sessions","alias":"sessions","formattingType":"METRIC_TYPE_UNSPECIFIED"}],"pageToken":"0","pageSize":10000,"includeEmptyRows":true}]}
Error in UseMethod("http_error") : `
## Expected output

Data from API

**Comment by MarkEdmondson1234** [comment]
The codes$data looks atypical for Shiny, can you deploy a hello world Shiny app? You need a reactive context wrapped around functions to work (reactive() or renderPlot() etc.


________________________________

**Comment by aavanesy** [comment]
I use
`  codes = reactiveValues(
    data = NULL
  )`

And later with a button. The uncommented part doesn't work, returns the error above.
The commented part works just fine when using locally but when deployed, as soon as I try to extract from API app hands. I do a test beforehand, app when deployed connects well and obtains a token.

  observeEvent(input$down, {
    
    print(access_token())
    
    codes$data  =  with_shiny(google_analytics,
               viewId = "135532055", ## replace with your View ID
               date_range = c("2019-01-01", "2019-03-01"),
               metrics = "sessions",
               dimensions = "date",
               shiny_access_token = access_token())
    
            # codes$data = google_analytics(
            #   viewId = "135532055", ## replace with your View ID
            #   date_range = c("2019-01-01", "2019-03-01"),
            #   metrics = c("sessions"),
            #   dimensions = c("date")
            # )
    
  })

**Comment by MarkEdmondson1234** [comment]
I would create an object first via the method described in the examples and then assign to your reactiveValues. The way with_shiny() works with environments to find the token may be confusing it when adding an extra environment using code$data.

The most modern auth method described in googleAuthR documentation does away with with_shiny() so may be better for your use case.


________________________________

**Comment by aavanesy** [comment]
I am trying this
http://markedmondson.me/how-i-made-ga-effect-creating-an-online-statistics-dashboard-using-reais

The AuthCode  and AccessToken  reactivity doesn't work, only when I force values using button.

**Comment by aavanesy** [comment]
This is all I have in my Server.
Token returns just fine.
  ```
output$AuthGAURL <- renderUI({
    a("Click Here to Authorise Your Google Analytics Access", href=ShinyGetTokenURL())
  })
  
  AuthCode  <- reactive({
        ## gets all the parameters in the URL. Your authentication code should be one of them
        pars <- parseQueryString(session$clientData$url_search) 
        if(length(pars$code) > 0){
          return(pars$code)
        } 

  })
  
  AccessToken <- reactive({ 
      access_token <- ShinyGetToken(code = AuthCode())
      #print(access_token)
      token <- access_token$access_token
      # print(token)
  })
  
  
  gadata <- reactive({
    
    # token = AccessToken()
    # print(token)
    
    with_shiny(google_analytics,
                              viewId = "", ## replace with your View ID
                              date_range = c("2019-01-01", "2019-03-01"),
                              metrics = "sessions",
                              dimensions = "date",
                              shiny_access_token = AccessToken())

  })
```

Error still the same

2019-08-15 12:34:01> Calling APIv4....
2019-08-15 12:34:01> Single v4 batch
2019-08-15 12:34:01> Request: https://analyticsreporting.googleapis.com/v4/reports:batchGet/
2019-08-15 12:34:01> Body JSON parsed to: {"reportRequests":[{"viewId":"ga:","dateRanges":[{"startDate":"2019-01-01","endDate":"2019-03-01"}],"samplingLevel":"DEFAULT","dimensions":[{"name":"ga:date"}],"metrics":[{"expression":"ga:sessions","alias":"sessions","formattingType":"METRIC_TYPE_UNSPECIFIED"}],"pageToken":"0","pageSize":1000,"includeEmptyRows":true}]}
Error in UseMethod("http_error") :

**Comment by MarkEdmondson1234** [comment]
The implementation above is not as described in the help files - you don't need to created AuthCode, AccessToken etc.  

Use the Shiny module as described here:
https://code.markedmondson.me/googleAnalyticsR/articles/shiny.html

**Comment by aavanesy** [comment]
Issue can be closed.
Thank you very much for the support.
