### ISSUE TITLE
Error: had non-zero exit status 

### ISSUE THREAD

**Issue by Fethiys** [MarkEdmondson1234/googleAnalyticsR#271]
## What goes wrong
Hi Mark, I am having problem installing last version of your GoogleAnalyticsR package.
remotes::install_github("MarkEdmondson1234/googleAnalyticsR",force = T)
this code returns following error.
Error: Failed to install 'googleAnalyticsR' from GitHub:
  (converted from warning) installation of package ‘C:/.../googleAnalyticsR_0.6.0.9000.tar.gz’ had non-zero exit status

No problem with remotes::install_github("MarkEdmondson1234/googleAuthR",force = T)

**Comment by MarkEdmondson1234** [comment]
Can I see your `sessionInfo()`?  Its likely you have a dependency missing or something that I can add to the requirements so it will download it.

**Comment by Fethiys** [comment]
Ah okay, there was dependecy missing. Thank you.
