### ISSUE TITLE
Problem with new authentication

### ISSUE THREAD

**Issue by DavidGarciaEstaun** [MarkEdmondson1234/googleAnalyticsR#274]
Hi Mark,

I am finding some problems with the new authentication method.
I am following this instruction but it seems that somenthing goes wrong:
http://code.markedmondson.me/googleAnalyticsR/articles/setup.html

I am trying to authenticate via "Email authentication", but when I call ga_auth() this message appears:

```
> Error in gar_auto_auth(needed, new_user = new_user, no_auto = no_auto,  : 
>   Cannot authenticate - options(googleAuthR.scopes.selected) needs to be set to includehttps://www.googleapis.com/auth/analytics or https://www.googleapis.com/auth/analytics.readonly or https://www.googleapis.com/auth/analytics.manage.users.readonly or https://www.googleapis.com/auth/analytics.edit or https://www.googleapis.com/auth/analytics.manage.users or https://www.googleapis.com/auth/analytics.provision but scopes set are: ttps://www.googleapis.com/auth/analytics
> In addition: Warning message:
> In gar_auto_auth(needed, new_user = new_user, no_auto = no_auto,  :
>   Argument new_user is deprecated and will be removed next release.
```

Also, in my ga_auth method I can't pass the email parameter.

I have updated the version via the normal method "CRAN". It seems that I should not have the right version or I am missing a package. Is it possible?

Here the session info:

```
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                   LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleAnalyticsR_0.6.0 dplyr_0.8.3            RMySQL_0.10.17         DBI_1.0.0              arules_1.6-3           Matrix_1.2-15         

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        rstudioapi_0.10   magrittr_1.5      tidyselect_0.2.5  munsell_0.5.0     colorspace_1.4-1  lattice_0.20-38   R6_2.4.0          rlang_0.4.0      
[10] httr_1.4.0        plyr_1.8.4        tools_3.5.3       grid_3.5.3        gtable_0.3.0      googleAuthR_1.0.0 digest_0.6.20     yaml_2.2.0        lazyeval_0.2.2   
[19] assertthat_0.2.1  gargle_0.3.1      tibble_2.1.1      crayon_1.3.4      tidyr_0.8.3       purrr_0.3.2       fs_1.3.1          memoise_1.1.0     glue_1.3.1       
[28] compiler_3.5.3    pillar_1.4.0      scales_1.0.0      jsonlite_1.6      pkgconfig_2.0.2 

```

**Comment by MarkEdmondson1234** [comment]
It looks like you do not have the dev version of `googleAnalyticsR` installed, which is needed - its coming soon to CRAN, but the website is a little ahead. 

`remotes::install_github("MarkEdmondson1234/googleAnalyticsR"`

**Comment by DavidGarciaEstaun** [comment]
Thanks.
I tried, but I am receiving this error:

```
ERROR: lazy loading failed for package ‘googleAnalyticsR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/googleAnalyticsR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/googleAnalyticsR’
Error: Failed to install 'googleAnalyticsR' from GitHub:
  (convertido del aviso) installation of package ‘/var/folders/3l/nc031tdx3tz23v86vg2pzm7w0000gn/T//RtmpsMa7No/file49e4ce40967/googleAnalyticsR_0.6.0.9000.tar.gz’ had non-zero exit status
```

**Comment by MarkEdmondson1234** [comment]
I think this is a current bug, which you can get around if you temporarily comment out any auto_auth arguments (eg. `.Renviron` has `GA_AUTH_FILE` populated)

**Comment by MarkEdmondson1234** [comment]
New issue for the above https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/275

**Comment by MarkEdmondson1234** [comment]
Can you try again now?  It should work

`remotes::install_github("MarkEdmondson1234/googleAnalyticsR")`

**Comment by DavidGarciaEstaun** [comment]
Now I have seen this error:

`Downloading GitHub repo MarkEdmondson1234/googleAnalyticsR@master
Downloading GitHub repo tidyverse/tidyr@master
Running `R CMD build`...
* checking for file ‘/private/var/folders/3l/nc031tdx3tz23v86vg2pzm7w0000gn/T/RtmpzrpKn9/remotesb5613aafd8f/tidyverse-tidyr-b0749cf/DESCRIPTION’ ... OK
* preparing ‘tidyr’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to process help pages
      -----------------------------------
* installing *source* package ‘tidyr’ ...
** using staged installation
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk' [-Wmissing-sysroot]
In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/Rcpp.h:27:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/Rcpp/r/headers.h:59:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:305:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
#include_next <math.h>
              ^~~~~~~~
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘tidyr’
* removing ‘/private/var/folders/3l/nc031tdx3tz23v86vg2pzm7w0000gn/T/RtmpuIpGvk/Rinstc3e7ddc09/tidyr’
      -----------------------------------
ERROR: package installation failed
STDOUT:
* checking for file ‘/private/var/folders/3l/nc031tdx3tz23v86vg2pzm7w0000gn/T/RtmpzrpKn9/remotesb5613aafd8f/tidyverse-tidyr-b0749cf/DESCRIPTION’ ... OK
* preparing ‘tidyr’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to process help pages
      -----------------------------------
* installing *source* package ‘tidyr’ ...
** using staged installation
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk' [-Wmissing-sysroot]
In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/Rcpp.h:27:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/Rcpp/r/headers.h:59:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:305:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
#include_next <math.h>
              ^~~~~~~~
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘tidyr’
* removing ‘/private/var/folders/3l/nc031tdx3tz23v86vg2pzm7w0000gn/T/RtmpuIpGvk/Rinstc3e7ddc09/tidyr’
      -----------------------------------
ERROR: package installation failed
STDERR:

Error: Failed to install 'googleAnalyticsR' from GitHub:
  Failed to install 'tidyr' from GitHub:
  Failed to `R CMD build` package, try `build = FALSE`.`

**Comment by MarkEdmondson1234** [comment]
That is something to do with tidyr, you could try raise an issue with them.  Its just about to be released to CRAN so I expect it will clear up if you wait a bit. https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/278

The dev version is unstable, so if you need stability use the CRAN version until its all sorted out on here.

**Comment by DavidGarciaEstaun** [comment]
Ok, Thanks Mark.

**Comment by DavidGarciaEstaun** [comment]
Hi Mark,

I have update the package and now I am receiving this error on authentication:
Error: Could not authenticate via any gargle cred function

I try to authenticate via ga_auth().
Probably I am doing something wrong but I don't know what.

Thanks in advance.
David.

**Comment by MarkEdmondson1234** [comment]
What code are you using?  Can you also run it with `options(googleAuthr.verbose = 2)`

**Comment by DavidGarciaEstaun** [comment]
```
> options(googleAuthR.verbose = 2)
> ga_auth()
2019-09-27 14:27:06> Default Google Project for googleAnalyticsR is set.  
 This is shared with all googleAnalyticsR users. 
 If making a lot of API calls, please: 
 visit: https://bit.ly/2Evk6hn 
 for instructions on setting your own Google Project 

Error: Could not authenticate via any gargle cred function
```

**Comment by MarkEdmondson1234** [comment]
Hmm not much to go on there.  Could you also run this code and give results:

```r
sessionInfo()
gargle::gargle_oauth_sitrep()
options(googleAuthR.verbose = 1,  gargle_quiet = FALSE)
library(googleAnalyticsR)
ga_auth()
gargle::gargle_oauth_sitrep()
ga_auth(email="your@email.com") # <- replace with your google email
gargle::gargle_oauth_sitrep()
```

**Comment by DavidGarciaEstaun** [comment]
Hi Mark,

I think that I am having the same error that in googledriveR package:
[(https://github.com/tidyverse/googledrive/issues/274)]
```

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

Random number generation:
    RNG:     Mersenne-Twister
Normal:  Inversion
Sample:  Rounding

locale:
    [1] es_ES.UTF-8/es_ES.UTF-8/es_ES.UTF-8/C/es_ES.UTF-8/es_ES.UTF-8

attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
    [1] googleAnalyticsR_0.7.0

loaded via a namespace (and not attached):
    [1] Rcpp_1.0.2        magrittr_1.5      tidyselect_0.2.5  R6_2.4.0          rlang_0.4.0     
[6] httr_1.4.1        dplyr_0.8.3       tools_3.6.1       googleAuthR_1.1.1 withr_2.1.2     
[11] askpass_1.1       openssl_1.4.1     assertthat_0.2.1  digest_0.6.21     lifecycle_0.1.0 
[16] tibble_2.1.3      gargle_0.3.1      crayon_1.3.4      purrr_0.3.2       tidyr_1.0.0     
[21] vctrs_0.2.0       fs_1.3.1          curl_4.2          zeallot_0.1.0     memoise_1.1.0   
[26] glue_1.3.1        compiler_3.6.1    pillar_1.4.2      backports_1.1.4   jsonlite_1.6     
[31] pkgconfig_2.0.3 
> gargle::gargle_oauth_sitrep()
gargle OAuth cache path:
    /Users/davidgarciaestaun/.R/gargle/gargle-oauth

Error: Cache contains tokens with names that do not match their hash:
    * Token stored as 'ff5ac8544ab9d11dda711c6555a0c8cf_asimon@bobochoses.com'
but hash is 'd8bd72a790109fea516d638703457f64_asimon@bobochoses.com'
Call `rlang::last_error()` to see a backtrace
> options(googleAuthR.verbose = 1,  gargle_quiet = FALSE)
> library(googleAnalyticsR)
> ga_auth()
2019-09-30 10:26:19> Default Google Project for googleAnalyticsR is set. 
This is shared with all googleAnalyticsR users.
If making a lot of API calls, please:
    visit: https://bit.ly/2Evk6hn
for instructions on setting your own Google Project

trying token_fetch()
trying credentials_service_account()
Error: parse error: premature EOF

(right here) ------^

    trying credentials_app_default()
trying credentials_gce()
trying credentials_byo_oauth()
Error: inherits(token, "Token2.0") is not TRUE
trying credentials_user_oauth2()
Gargle2.0 initialize
adding 'userinfo.email' scope
loading token from the cache
Error: Cache contains tokens with names that do not match their hash:
    * Token stored as 'ff5ac8544ab9d11dda711c6555a0c8cf_asimon@bobochoses.com'
but hash is 'd8bd72a790109fea516d638703457f64_asimon@bobochoses.com'
Error: Could not authenticate via any gargle cred function
> gargle::gargle_oauth_sitrep()
gargle OAuth cache path:
    /Users/davidgarciaestaun/.R/gargle/gargle-oauth

Error: Cache contains tokens with names that do not match their hash:
    * Token stored as 'ff5ac8544ab9d11dda711c6555a0c8cf_asimon@bobochoses.com'
but hash is 'd8bd72a790109fea516d638703457f64_asimon@bobochoses.com'
Call `rlang::last_error()` to see a backtrace
> ga_auth(email="asimon@bobochoses.com") # <- replace with your google email
2019-09-30 10:26:19> Default Google Project for googleAnalyticsR is set. 
This is shared with all googleAnalyticsR users.
If making a lot of API calls, please:
    visit: https://bit.ly/2Evk6hn
for instructions on setting your own Google Project

trying token_fetch()
trying credentials_service_account()
Error: parse error: premature EOF

(right here) ------^

    trying credentials_app_default()
trying credentials_gce()
trying credentials_byo_oauth()
Error: inherits(token, "Token2.0") is not TRUE
trying credentials_user_oauth2()
Gargle2.0 initialize
adding 'userinfo.email' scope
loading token from the cache
Error: Cache contains tokens with names that do not match their hash:
    * Token stored as 'ff5ac8544ab9d11dda711c6555a0c8cf_asimon@bobochoses.com'
but hash is 'd8bd72a790109fea516d638703457f64_asimon@bobochoses.com'
Error: Could not authenticate via any gargle cred function
> gargle::gargle_oauth_sitrep()
gargle OAuth cache path:
    /Users/davidgarciaestaun/.R/gargle/gargle-oauth

Error: Cache contains tokens with names that do not match their hash:
    * Token stored as 'ff5ac8544ab9d11dda711c6555a0c8cf_asimon@bobochoses.com'
but hash is 'd8bd72a790109fea516d638703457f64_asimon@bobochoses.com'
Call `rlang::last_error()` to see a backtrace

```

**Comment by DavidGarciaEstaun** [comment]
Solved!!! Thanks!!! :)

**Comment by GuidoMC** [comment]
Hola @DavidGarciaEstaun , que hiciste para resolverlo?

**Comment by DavidGarciaEstaun** [comment]
Hola @GuidoMC ,

Si no recuerdo mal hice lo que comentaba @MarkEdmondson1234 . Básicamente el problema que creo que tuve es que actualicé antes de que estuviera todo subido a CRAN y tenía ciertas funciones que no tiraban bien. Se me quedo la caché corrupta.
Dudo que sea lo mismo que te pasa a ti, pero intenta borrar la caché que comenta @MarkEdmondson1234 y te funcionará. Sino prueba a borrar la librería y volver a instalar, que supongo que ya lo habrás hecho.

Si te puedo ayudar en algo dime.

Un saludo
