### ISSUE TITLE
Error in as(dim_filters, ".filter_clauses_ga4") : no method or default for coercing “list” to “.filter_clauses_ga4”

### ISSUE THREAD

**Issue by etk4ya** [MarkEdmondson1234/googleAnalyticsR#279]
Similar to Issue #253, in a previous version (0.5.0), users were able to create multiple filters using filter_clauses_ga4 and combine them using list(). But this still generates an error "Error in as(dim_filters, "filter_clauses_ga4") : no method or default for coercing “list” to “.filter_clauses_ga4”".

Not sure if this would be resolved with the same fix for Issue #253?

**Comment by MarkEdmondson1234** [comment]
Thanks, will look to solve in a similar manner yes

**Comment by MarkEdmondson1234** [comment]
Can you try it now with latest github version?  `remotes::install_github("MarkEdmondson1234/googleAnalyticsR")`

**Comment by etk4ya** [comment]
Sure, thank you for that. It seems that a similar error still occurs, even after installing the latest github version "Error in as(x, the_class) : no method or default for coercing “list” to “.filter_clauses_ga4”".

**Comment by MarkEdmondson1234** [comment]
Did you restart R after installation?  can I see the code you are using to test?

**Comment by MarkEdmondson1234** [comment]
This works for me:

```r
#' ## create filters on metrics
mf <- met_filter("bounces", "GREATER_THAN", 0)
mf2 <- met_filter("sessions", "GREATER", 2)
#'
#' ## create filters on dimensions
df <- dim_filter("source","BEGINS_WITH","1",not = TRUE)
df2 <- dim_filter("source","BEGINS_WITH","a",not = TRUE)
#'
#' ## construct filter objects
fc2 <- filter_clause_ga4(list(df, df2), operator = "AND")
fc <- filter_clause_ga4(list(mf, mf2), operator = "AND")
#'
#' ## make v4 request

ga_id <- 1234567
ga_data1 <- google_analytics_4(ga_id,
                                date_range = c("2015-07-30","2015-10-01"),
                                dimensions=c('source','medium'),
                               metrics = c('sessions','bounces'),
                                met_filters = fc,
                                dim_filters = fc2,
                                filtersExpression = "ga:source!=(direct)")
```

**Comment by etk4ya** [comment]
Yes, I did restart R after installation. Here is my code below:
`
## create filters on dimensions
df_m1 <- dim_filter("networkLocation", operator = "REGEX", "example", caseSensitive = FALSE, not = TRUE)
df_m2 <- dim_filter("networkLocation", operator = "REGEX", "example2", caseSensitive = FALSE, not = TRUE)

df_u1 <- dim_filter("pagePath", operator = "EXACT", "exampleUrl", caseSensitive = FALSE, not = FALSE)
df_u2 <- dim_filter("pagePath", operator = "EXACT", "exampleUrl2", caseSensitive = FALSE, not = FALSE)
df_u3 <- dim_filter("pagePath", operator = "EXACT", "exampleUrl3", caseSensitive = FALSE, not = FALSE)

df_r1 <- dim_filter("region", operator = "EXACT", "state", caseSensitive = FALSE, not = FALSE)
df_r2 <- dim_filter("region", operator = "EXACT", "state", caseSensitive = FALSE, not = FALSE)
df_r3 <- dim_filter("region", operator = "EXACT", "state", caseSensitive = FALSE, not = FALSE)


## create filter objects
df_mFilter <- filter_clause_ga4(list(df_m1, df_m2), operator = "AND")
df_uFilter <- filter_clause_ga4(list(df_u1, df_u2, df_u3), operator = "OR")
df_rFilter <- filter_clause_ga4(list(df_r1, df_r2, df_r3), operator = "OR")


## make v4 request
ga_data <- google_analytics(viewId = "123456",
                                date_range = c("2019-01-01", "2019-01-31"),
                                dimensions=c("date", "pagePath", "region"),
                                metrics = c("uniquePageviews"),
                                dim_filters = list(df_mFilter, df_uFilter, df_rFilter),
                                useResourceQuotas = TRUE,
                                max = -1)
`

**Comment by MarkEdmondson1234** [comment]
Thanks I see now your example.

Can you try it with the latest version now? The below works for me

```r
#' ## create filters on dimensions
df <- dim_filter("source","BEGINS_WITH","1",not = TRUE)
df2 <- dim_filter("source","BEGINS_WITH","a",not = TRUE)
df3 <- dim_filter("medium","EXACT","organic")

#'
#' ## construct filter objects
fc <- filter_clause_ga4(list(mf, mf2), operator = "AND")
fc2 <- filter_clause_ga4(list(df, df2), operator = "AND")
fc3 <- filter_clause_ga4(list(df3))
#'
#' ## make v4 request

ga_id <- 81416156
ga_data1 <- google_analytics(ga_id,
                             date_range = c("2015-07-30","2015-10-01"),
                             dimensions=c('source','medium'),
                             metrics = c('sessions','bounces'),
                             met_filters = fc,
                             dim_filters = list(fc2,fc3),
                             filtersExpression = "ga:source!=(direct)")
```

**Comment by MarkEdmondson1234** [comment]
@jdeboer this looks like this breaks this test though:

```r
 library(ganalytics)
  # Device category is desktop or tablet - a dimension filter using an OR condition.
  desktop_or_mobile <- Expr(~deviceCategory == "desktop") | Expr(~deviceCategory == "tablet")
  
  # New visitors using either a desktop or tablet device - a dimension filter involving both an AND and an OR condition.
  new_desktop_and_mobile_visitors <- Expr(~userType == "new") & desktop_or_mobile
  
  # At least one goal completion or transaction - a metric filter using an OR condition.
  at_least_one_conversion <- Expr(~goalCompletionsAll > 0) | Expr(~transactions > 0)
  
  results <- google_analytics(
    viewId = ga_id2,
    date_range = c("30daysAgo", "yesterday"),
    metrics = c("users", "sessions", "goalCompletionsAll", "transactions"),
    dimensions = c("deviceCategory", "userType"),
    dim_filters = new_desktop_and_mobile_visitors,
    met_filters = at_least_one_conversion
  )
#Error in as.list.default(X) : 
  no method for coercing this S4 class to a vector
```

Is there a fix for this via `class(x)` etc?

**Comment by jimmyg3g** [comment]
fwiw, my current workaround is to use the `renv` package, [https://rstudio.github.io/renv/articles/renv.html](url). In projects that use `ganalytics::Expr()`, `renv` attaches `googleAnalyticsR_0.6.0`. In projects that use `googleAnalyticsR::ga_clientid_activity()`. `renv` attaches `googleAnalyticsR_0.7.0.9000`. 

In my use cases, `ganalytics::Expr()` still works with  `googleAnalyticsR_0.6.0`.

**Comment by jdeboer** [comment]
See https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/339#issuecomment-731463601 for a proposed solution.
