### ISSUE TITLE
App has not been verified yet by Google

### ISSUE THREAD

**Issue by omedasky** [MarkEdmondson1234/googleAnalyticsR#292]
## What goes wrong
When calling ga_auth(), Google throws an app verification error

## Steps to reproduce the problem

ga_auth()

<img width="512" alt="Sign_in_-_Google_Accounts_ga_auth" src="https://user-images.githubusercontent.com/54335157/70463217-7d680700-1a8a-11ea-9eb2-eb4e1ebb0fc6.png">

**Comment by MarkEdmondson1234** [comment]
You may be able to carry on if you hit a link on that scren, but Google is tightening up policy around OAuth2 in general and it seems the defualt project is up for re-evaluation.  The best way to avoid this is to use your own GCP project as detailed on the website https://code.markedmondson.me/googleAnalyticsR/articles/setup.html

**Comment by MarkEdmondson1234** [comment]
It should be ok again if you are authenticating under these scopes:


> Dear Developer,Thank you for submitting a verification request.Your OAuth App Verification request for project g-analytics-r has been approved for the following scopes:
https://www.googleapis.com/auth/analytics
https://www.googleapis.com/auth/analytics.edit
https://www.googleapis.com/auth/analytics.manage.users 
https://www.googleapis.com/auth/analytics.manage.users.readonly
https://www.googleapis.com/auth/analytics.readonly
https://www.googleapis.com/auth/analytics.user.deletion

**Comment by MarkEdmondson1234** [comment]
Should be ok again now.
