### ISSUE TITLE
Error when using slow_fetch = TRUE

### ISSUE THREAD

**Issue by hauerland** [MarkEdmondson1234/googleAnalyticsR#293]
## What goes wrong
I am getting an error when using slow_fetch = TRUE for a few weeks in googleAnalyticsR version 0.7.1. May be it´s some how connected with this issue [#282](https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/282)?

## Steps to reproduce the problem

```
start_date <- 'XXX'
end_date <- 'XXX'
df <- dim_filter("eventCategory", "EXACT", "XXX")
fc <- filter_clause_ga4(list(df), operator = "AND")

 x <- google_analytics(XXX, 
                                   date_range = c(start_date, end_date),
                                   dimensions=c('date', 'eventAction', 'eventLabel'),
                                   metrics = c('totalEvents', 'uniqueEvents'),
                                   dim_filters = fc,
                                   samplingLevel="WALK",
                                   anti_sample = TRUE,
                                   anti_sample_batches = "auto",
                                   slow_fetch = TRUE
                                   )
```
## Actual output
```
2019-12-14 09:24:24> anti_sample set to TRUE. Mitigating sampling via multiple API calls.
2019-12-14 09:24:24> Finding how much sampling in data request...
2019-12-14 09:24:26> Downloaded [10] rows from a total of [557].
2019-12-14 09:24:26> No sampling found, returning call
2019-12-14 09:24:26> Slow fetch: [0] from estimated actual Rows [9999]
**Error in if (as.integer(npt) >= max_rows) { : argument is of length zero**
```

**Comment by MarkEdmondson1234** [comment]
Hmm yes thank you, for some reason the number of rows is null. Will check it.


________________________________

**Comment by MarkEdmondson1234** [comment]
Many thanks to @octaviancorlade who made a fix for this, could @hauerland try this now with latest version?  `remotes::install_github("MarkEdmondson1234/googleAnalyticsR")`

**Comment by jenccnej** [comment]
> Many thanks to @octaviancorlade who made a fix for this, could @hauerland try this now with latest version? `remotes::install_github("MarkEdmondson1234/googleAnalyticsR")`

Hello!
Tested, everything works now
Thanks

**Comment by MarkEdmondson1234** [comment]
Great, thanks everyone - will be in next CRAN release
