### ISSUE TITLE
Question: Is there a way to access demographic information?

### ISSUE THREAD

**Issue by NateMietk** [MarkEdmondson1234/googleAnalyticsR#295]
I am generally interested in accessing the demographic information (age/gender) contained within the GA Audience.  Is there a way to accomplish this task?  I have implemented various other calls successfully, but cannot seem to find a way to capture these data.  Great package and look forward to hearing from you!

**Comment by MarkEdmondson1234** [comment]
Thanks for using the package :)

You can see all available metrics and dimensions via the ‘meta’ data.frame that comes with the package, which is a copy of the data here https://ga-dev-tools.appspot.com/dimensions-metrics-explorer/

It includes the DoubleClick demographics such as gender but you need to ensure that’s  being collected in your GA settings. Also note there was a bug recently that globally removed these demographics, but it’s back again this week I think.


________________________________

**Comment by NateMietk** [comment]
@MarkEdmondson1234 Thanks for the prompt response! I did not realize they were in the met data.frame - I must have skipped over it when I looked. Thanks again and appreciate all the hard work you have to done to produce such an impressive package!
