### ISSUE TITLE
429 errors for large complicated queries 

### ISSUE THREAD

**Issue by tobmcv** [MarkEdmondson1234/googleAnalyticsR#296]
## What goes wrong
When making a call for a large table of data using `google_analytics` the Google Analytics server responds with an error. The query works with data for a single day, and returns 446,000 rows for 1 day.

My request contains a request for client ID, session ID, hit timestamp and Page URI, and unique pageviews. I need a month of data for my use-case.

```r
table <- google_analytics(ga_tableid,
                            date_range = c("2020-01-01", "2020-01-31"),
                            metrics = c("uniquePageviews"),
                            dimensions = c("pagePath","dimension16","dimension14", "dimension13"),
                            anti_sample = TRUE,
                            slow_fetch = TRUE)
```

The error states that there are too many failed requests and the user should implement **exponential backoff**. How do we do this with the google AnalyticsR package? Can I add a random wait command in a function? Or do I need to write my own script for handling the response codes from Google?

Alternatively, is there a way to rewrite the request to just rerun the query for a range of dates?

Google defines Exponential backoff as

> Exponential backoff is the process of a client periodically retrying a failed request over an increasing amount of time. It is a standard error handling strategy for network applications. The Management API is designed with the expectation that clients which choose to retry failed requests do so using exponential backoff. Besides being "required", using exponential backoff increases the efficiency of bandwidth usage, reduces the number of requests required to get a successful response, and maximizes the throughput of requests in concurrent environments.

See https://developers.google.com/analytics/devguides/config/mgmt/v3/errors#backoff

## Steps to reproduce the problem
Request a large table with custom dimensions with around 1,000,000 or more rows.

In my example the following custom dimensions have very different scopes

* Client ID is a session-scoped custom dimension
* Session ID is a session-scoped custom dimension
* Hit timestamp is a hit-scoped custom dimension
* Unique Pageviews is a hit-scoped standard metric
* Page Path is a hit-scoped standard metric

## Expected output
A large table of 1,000,000 or more rows combining hit and session-scoped custom dimensions with standard metrics and dimensions.

## Actual output

Before you run your code, please run:

console error 
```
Error : API returned: Quota Error: Number of recent failed reporting API requests is too high, please implement exponential back off.
See developer documentation for details at https://developers.google.com/analytics/devguides/reporting/core/v4/limits-quotas#reporting_apis_request_errors
2020-02-11 09:02:16> Error requesting v4 batch - retrying with slow_fetch=TRUE ...
2020-02-11 09:02:21> Slow fetch: [0] from estimated actual Rows [9999]
Request failed [429]. Retrying in 1 seconds...
Request failed [429]. Retrying in 1 seconds...
2020-02-11 09:02:24> Request Status Code: 429
2020-02-11 09:02:24> Trying again: 1 of 1
2020-02-11 09:02:26> All attempts failed.
Error : API returned: Quota Error: Number of recent failed reporting API requests is too high, please implement exponential back off.
See developer documentation for details at https://developers.google.com/analytics/devguides/reporting/core/v4/limits-quotas#reporting_apis_request_errors
Error in error_check(out) : 
  API returned: Quota Error: Number of recent failed reporting API requests is too high, please implement exponential back off.
See developer documentation for details at https://developers.google.com/analytics/devguides/reporting/core/v4/limits-quotas#reporting_apis_request_errors
```

## Session Info

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleAnalyticsR_0.6.0 jsonlite_1.6          

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2        pillar_1.4.2      compiler_3.6.1    googleAuthR_1.0.0
 [5] remotes_2.1.0     prettyunits_1.0.2 tools_3.6.1       testthat_2.2.1   
 [9] pkgload_1.0.2     zeallot_0.1.0     digest_0.6.20     pkgbuild_1.0.5   
[13] memoise_1.1.0     gargle_0.3.1      tibble_2.1.3      lifecycle_0.1.0  
[17] pkgconfig_2.0.2   rlang_0.4.2       cli_1.1.0         rstudioapi_0.10  
[21] curl_4.0          withr_2.1.2       dplyr_0.8.3       httr_1.4.1       
[25] askpass_1.1       desc_1.2.0        fs_1.3.1          vctrs_0.2.1      
[29] htmlwidgets_1.3   devtools_2.2.0    rprojroot_1.3-2   DT_0.8           
[33] tidyselect_0.2.5  glue_1.3.1        R6_2.4.0          processx_3.4.1   
[37] sessioninfo_1.1.1 tidyr_1.0.0       purrr_0.3.3       callr_3.3.1      
[41] magrittr_1.5      usethis_1.5.1     backports_1.1.4   ps_1.3.0         
[45] htmltools_0.3.6   ellipsis_0.2.0.1  assertthat_0.2.1  openssl_1.4.1    
[49] crayon_1.3.4
```

**Comment by MarkEdmondson1234** [comment]
Are you using your own client.id ? It may be clashing with other users of the package, in which case its best to use your own.

Exponential backoff is implemented so if API errors occur up to 3 retries are attempted before an error is returned.  You can see these attempts if you set `options(googleAuthR.verbose=2)`

But for very large complicated queries it may not be enough - it looks like you should configure the API calls more than the defaults which work for most queries but not all. There are some details on this here: http://code.markedmondson.me/googleAnalyticsR/articles/v4.html#customising-api-fetches

I would try first using `slow_fetch=TRUE` (to turn off the v4 batching) and lowering the amount of rows returned per API call (`rows_per_call = 1000`)

Also check the query is valid at all, with a single days worth of data and only 1000 rows to return. 

Also note that the maximum hard limit for one API call is 1million rows, so if you are expecting data amounts greater than that then you will need to split up the date range - there is an example of how to do that in this video https://youtu.be/2-f0aTwWiNw?t=454

**Comment by MarkEdmondson1234** [comment]
Also do update to googleAnalyticsR 0.7.1 which has some work done to help fetching

**Comment by tobmcv** [comment]
Your tips helped immensely and solved my problem. This is the most incredible improvement I've seen in R code. Thank you so much! The code runs at least twice as fast now!

**Comment by MarkEdmondson1234** [comment]
Great, yes it was probably slow as it was trying the API and failing each time with retries, sometimes working sometimes not.
