### ISSUE TITLE
Error presented when using gar_auth_js

### ISSUE THREAD

**Issue by lodowner** [MarkEdmondson1234/googleAnalyticsR#298]
## What goes wrong
When using gar_auth_js module inside 'server' function I receive a coercion error message.
Appears to work fine without function.

## Steps to reproduce the problem
See code below 

```
library(shiny)
library(googleAuthR)

gar_set_client(scopes = c("htps://www.googleapis.com/auth/analytics.readonly"))



library(googleAnalyticsR)

ui <- fluidPage(
  googleAuth_jsUI("auth"))

server <- function(input, output, session) {
  
  auth() <- callModule(gar_auth_js, "auth")

}

shinyApp(ui = ui, server = server)

```

And without....

```
library(shiny)
library(googleAuthR)

gar_set_client(scopes = c("htps://www.googleapis.com/auth/analytics.readonly"))



library(googleAnalyticsR)

ui <- fluidPage(
  googleAuth_jsUI("auth"))

server <- function(input, output, session) {

}

shinyApp(ui = ui, server = server)

```

## Expected output

Expected output is to see 'Log In' button associated with googleAuth_jsUI. However when I use the function I get the error message below.

## Actual output

```
Listening on http://xxx.x.x.x:xxxx
Warning: Error in as.character: cannot coerce type 'closure' to vector of type 'character'
  58: sprintf
  57: gettextf
  56: .Deprecated
  55: module
  50: callModule
  49: server [/Users/"file path"/app.R#15]
Error in as.character(function (input, output, session, message = "Authenticate with your Google account")  : 
  cannot coerce type 'closure' to vector of type 'character'

```

I understand that R is expecting a character vector but I am unsure as to what this relates to specifically. Additionally, I am unsure what value "auth" relates to.

**Comment by lodowner** [comment]
Adding sessioninfo

R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleAnalyticsR_0.7.1 googleAuthR_1.1.1      shiny_1.4.0           

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2       rstudioapi_0.10  magrittr_1.5     tidyselect_0.2.5 xtable_1.8-4     R6_2.4.0        
 [7] rlang_0.4.2      fastmap_1.0.1    httr_1.4.1       dplyr_0.8.3      tools_3.6.1      htmltools_0.4.0 
[13] assertthat_0.2.1 digest_0.6.22    lifecycle_0.1.0  tibble_2.1.3     gargle_0.4.0     crayon_1.3.4    
[19] tidyr_1.0.0      purrr_0.3.3      later_1.0.0      vctrs_0.2.0      promises_1.1.0   fs_1.3.1        
[25] zeallot_0.1.0    memoise_1.1.0    glue_1.3.1       mime_0.8         compiler_3.6.1   pillar_1.4.2    
[31] backports_1.1.5  jsonlite_1.6     httpuv_1.5.2     pkgconfig_2.0.3

**Comment by MarkEdmondson1234** [comment]
The problem was it was sending back the deprecated message for the function - use the updated function instead:

```r
>googleAuthR::gar_auth_jsUI("sd")
# ...
# Warning message:
#283 'googleAuthR::gar_auth_jsUI' is deprecated.

>googleAuthR::googleAuth_jsUI("sd")
```
