### ISSUE TITLE
No option to include anti-sampling dimensions in the output

### ISSUE THREAD

**Issue by Rifmaz** [MarkEdmondson1234/googleAnalyticsR#299]
**Is your feature request related to a problem? Please describe.**
Not sure if this fits a Bug or a New Feature request ticket but:

When using the anti-sampling feature, the function uses up at least the _date_ dimension (out of a possible 9 dimensions). The _date_ dimension is then dropped in the output and there is no option to keep them in the output (i.e. stop the aggregation).

**Describe the solution you'd like**
To be given the option to aggregate the data or not and, if not, for the dimensions used for anti-sampling to be kept in the final output. 

**Describe alternatives you've considered**
Checked in the documentation to see if this option exists but could not find it.

**Additional context**
None

**Comment by MarkEdmondson1234** [comment]
I'm not sure I follow, could you include an example?  If you include the date dimension it should appear in the results anti_sample of not.

**Comment by Rifmaz** [comment]
Hi Mark. Sorry, I should have included an example. The first couple of screenshots give context, the third is what this ticket is about.

Below you can see the size of the array I've used for generating the data pull. It's an array of size 9, the maximum number of dimensions.
![Dimensions Array](https://user-images.githubusercontent.com/10761465/75064891-ae7ba380-54df-11ea-9617-f5c2ea9607ad.png)

When I try to run it, however, I get the following error:
![Error Response](https://user-images.githubusercontent.com/10761465/75065129-221db080-54e0-11ea-8d63-031c2dbc7519.png)

Which indicated to me that a 10th dimension is appended, probably for anti-sampling. I checked the github repo briefly and noticed that "date " may be appended to the API call. The problem is that when I drop one of my dimensions so I now have 8, the google_analytics function ends up returning 8 dimensions, without the "date". I assume this is because, during processing, the extra dimension is dropped from the table.
![Results_header](https://user-images.githubusercontent.com/10761465/75066101-103d0d00-54e2-11ea-986c-f1adec694636.png)

For reference, here's the set-up of the call:

```
google_analytics(viewId = ga_config_item$view_id,
                                     date_range= c(startDate,endDate),
                                     dimensions = dimensions,
                                     metrics = metrics,
                                     segments = segments,
                                     anti_sample = anti_sample_choice,
                                     anti_sample_batches = anti_Sample_batches,
                                     max = -1)
```

Thanks for looking into this! Please let me know if I've misunderstood what the code does.

**Comment by Rifmaz** [comment]
Hi Mark,

I just realised what the problem was... The Segment counts as a dimension. Sorry for raising this as an issue.

I've now closed it.

**Comment by MarkEdmondson1234** [comment]
Ok no worries :)


________________________________
