### ISSUE TITLE
Error: package or namespace load failed for ‘googleAnalyticsR’

### ISSUE THREAD

**Issue by acamposc** [MarkEdmondson1234/googleAnalyticsR#301]
## What goes wrong
Cannot install from github nor use previously installed googleAnalyticsR package.

## Steps to reproduce the problem
remotes::install_github("MarkEdmondson1234/googleAnalyticsR")
library(googleAnalyticsR)

## Expected output
Regular usage of the library.

## Actual output
Error: package or namespace load failed for ‘googleAnalyticsR’:
 .onAttach failed in attachNamespace() for 'googleAnalyticsR', details:
  call: NULL
  error: $installed not found in JSON - have you downloaded the correct JSON file? 
           (Service account client > Other, not Service Account Keys)
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/googleAnalyticsR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/googleAnalyticsR’
Error: Failed to install 'googleAnalyticsR' from GitHub:
  (converted from warning) installation of package ‘/var/folders/nm/ztnl6ht55hx8l4z9l2072cd00000gn/T//Rtmp8soLqB/file330f150eee1c/googleAnalyticsR_0.7.1.9000.tar.gz’ had non-zero exit status

Before you run your code, please run:

`options(googleAuthR.verbose=2)` and copy-paste the console output here.  
Check it doesn't include any sensitive info like auth tokens or accountIds - you can usually just edit those out manually and replace with say `XXX`

> options(googleAuthR.verbose=2)
> remotes::install_github("MarkEdmondson1234/googleAnalyticsR")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo MarkEdmondson1234/googleAnalyticsR@master
✓  checking for file ‘/private/var/folders/nm/ztnl6ht55hx8l4z9l2072cd00000gn/T/Rtmp8soLqB/remotes330f3b817f6d/MarkEdmondson1234-googleAnalyticsR-1d55625/DESCRIPTION’ ...
─  preparing ‘googleAnalyticsR’: (448ms)
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘googleAnalyticsR_0.7.1.9000.tar.gz’
   
* installing *source* package ‘googleAnalyticsR’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘googleAnalyticsR’:
 .onAttach failed in attachNamespace() for 'googleAnalyticsR', details:
  call: NULL
  error: $installed not found in JSON - have you downloaded the correct JSON file? 
           (Service account client > Other, not Service Account Keys)
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/googleAnalyticsR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/googleAnalyticsR’
Error: Failed to install 'googleAnalyticsR' from GitHub:
  (converted from warning) installation of package ‘/var/folders/nm/ztnl6ht55hx8l4z9l2072cd00000gn/T//Rtmp8soLqB/file330f32d4eba0/googleAnalyticsR_0.7.1.9000.tar.gz’ had non-zero exit status

## 'API Data failed to parse' diagnostics

If you have an error starting with:

`API Data failed to parse.`

* Please install googleAuthR >v0.7.9000:

```r
remotes::install_github("MarkEdmondson1234/googleAuthR")
```

* Restart the R session and run your bugged code.
* It should write a file called `gar_parse_error.rds` to your working directory.
* Run the below to output some diagnostic information and paste the response here.

```r
googleAuthR::gar_debug_parsing("gar_parse_error.rds")
```
> options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/analytics.readonly")
> service_token <- gar_auth_service(json_file="/Users/xxxxxxx/Downloads/xxxx-keys.json")
> service_token
<Token>
<oauth_endpoint>
 authorize: https://accounts.google.com/o/oauth2/auth
 access:    https://accounts.google.com/o/oauth2/token
 validate:  https://www.googleapis.com/oauth2/v1/tokeninfo
 revoke:    https://accounts.google.com/o/oauth2/revoke
NULL
<credentials> access_token, expires_in, token_type
---
> googleAuthR::gar_debug_parsing("gar_parse_error.rds")
Error: Path 'gar_parse_error.rds' does not exist

## Session Info

Please run `sessionInfo()` so we can check what versions of packages you have installed
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleAuthR_1.1.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3             pillar_1.4.3           compiler_3.6.2         googleAnalyticsR_0.7.1 prettyunits_1.1.1     
 [6] remotes_2.1.1          tools_3.6.2            digest_0.6.25          pkgbuild_1.0.6         jsonlite_1.6.1        
[11] memoise_1.1.0          gargle_0.4.0           tibble_2.1.3           lifecycle_0.1.0        pkgconfig_2.0.3       
[16] rlang_0.4.4            cli_2.0.1              rstudioapi_0.11        curl_4.3               withr_2.1.2           
[21] dplyr_0.8.4            httr_1.4.1             fs_1.3.1               vctrs_0.2.3            askpass_1.1           
[26] rprojroot_1.3-2        tidyselect_1.0.0       glue_1.3.1             R6_2.4.1               processx_3.4.2        
[31] fansi_0.4.1            purrr_0.3.3            tidyr_1.0.2            callr_3.4.2            magrittr_1.5          
[36] backports_1.1.5        ps_1.3.2               assertthat_0.2.1       openssl_1.4.1          crayon_1.3.4

**Comment by acamposc** [comment]
Even if I set the env var  "GAR_CLIENT_JSON" with the correct path to the keys I get the error:

> Sys.getenv("GAR_CLIENT_JSON")
[1] "/Users/XXXXXX/Downloads/CLIENT_SERV_KEY.json"
> library(googleAnalyticsR)
Error: package or namespace load failed for ‘googleAnalyticsR’:
 .onAttach failed in attachNamespace() for 'googleAnalyticsR', details:
  call: NULL
  error: $installed not found in JSON - have you downloaded the correct JSON file? 
           (Service account client > Other, not Service Account Keys)

**Comment by MarkEdmondson1234** [comment]
It’s the wrong JSON file somehow. What is the content of your file? Also remember to restart R in between Renviron changes.

**Comment by acamposc** [comment]
Thanks for the quick reply.

`
File contents: 
{
  "type": "service_account",
  "project_id": "PROJ-ID",
  "private_key_id": "PRIVATE KEY ID",
  "private_key": "-----BEGIN PRIVATE KEY-----...==\n-----END PRIVATE KEY-----\n",
  "client_email": "XXXXXXX@PROJ-ID.iam.gserviceaccount.com",
  "client_id": "999999999999999",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/PROJ_ID.iam.gserviceaccount.com"
}
`


Also: 

Restarting R session...

> library(googleAnalyticsR)
Error: package or namespace load failed for ‘googleAnalyticsR’:
 .onAttach failed in attachNamespace() for 'googleAnalyticsR', details:
  call: NULL
  error: $installed not found in JSON - have you downloaded the correct JSON file? 
           (Service account client > Other, not Service Account Keys)

**Comment by MarkEdmondson1234** [comment]
Yes that is the wrong JSON file.  Its an auth file (with a private key).  You want the client JSON that specifies the client etc.

**Comment by acamposc** [comment]
You were very right sir. Thanks
