### ISSUE TITLE
Generating VM - API error 

### ISSUE THREAD

**Issue by inespereda** [MarkEdmondson1234/googleAnalyticsR#310]
Hi Mark, 

I am an ecologist just trying to get some more RAM to run remotely sensed data, I am as fresh as it gets to Google Cloud and fairly new to R. I am not able to set a VM to get RStudio running. It does not recognize the API and it is definitely enabled. But then I also get the error of no Authorization or on the token which is definitely there as well. 

I've tried in two different ways, with so the code lines are separated to show it. 

errata: I've already posted this a couple of hs ago and wanted to update the new try but I don't know why it didn't appear within the issues. sorry if it is duplicated.

Hope you can help and many thanks in advance! 

## This is my code 
remotes::install_github("MarkEdmondson1234/googleAuthR")

key <- "C:/project/tordokey.json"
zone <- "australia-southeast1-a"
project <- "tordo"

library(googleComputeEngineR) # latest github version

Sys.setenv(GCE_AUTH_FILE = key, 
           GCE_DEFAULT_ZONE = zone,
           GCE_DEFAULT_PROJECT_ID = project)

gce_global_project(project)
gce_global_zone(zone)

vm <- gce_vm(template = "rstudio", 
             name = "r-studio-server",
             username = "ines",
             pasword = "XXXX",
             predefined_type = "n1-highmem-1")

 Second option -----------------
library(googleComputeEngineR)
library(googleAuthR)

auth_file <- "C:/project/tordokey.json"

options(googleAuthR.scopes.selected = c("https://www.googleapis.com/auth/cloud-platform"))
Sys.setenv(GCE_AUTH_FILE = auth_file)

gar_auth_service(auth_file, scope = getOption("googleAuthR.scopes.selected"))

gce_global_project("tordo")
gce_global_zone("australia-southeast1-a")
tag <- gce_tag_container("google-auth-r-cron-tidy", project = "tordo")

vm <- gce_vm(name = "tordo",
             template = "rstudio",
             username = "ines",
             password = "XXXX",
             predefined_type = "n1-standard-1",
             dynamic_image = tag)

options(googleAuthR.verbose=2)

## These are the outputs and errors

> library(googleComputeEngineR)
> Sys.setenv(GCE_AUTH_FILE = key, 
>                  GCE_DEFAULT_ZONE = zone,
>                   GCE_DEFAULT_PROJECT_ID = project)
> gce_global_project(project)
2020-04-26 19:25:35> Set default project name to 'tordo'
> gce_global_zone(zone)
Set default zone name to 'australia-southeast1-a'
> vm <- gce_vm(template = "rstudio", 
>              name = "r-studio-server",
>              username = "ines",
>              pasword = "XXXX",
>              predefined_type = "n1-highmem-1")

+2020-04-26 19:25:37> No authorization yet in this session!
+2020-04-26 19:25:37> No  .httr-oauth  file exists in current working directory.  Do library +authentication steps to provide credentials.
+Error: Invalid token

> library(googleAuthR)
> auth_file <- "C:/project/tordokey.json"
> options(googleAuthR.scopes.selected = c("https://www.googleapis.com/auth/cloud-platform"))
> Sys.setenv(GCE_AUTH_FILE = auth_file)
> gar_auth_service(auth_file, scope = getOption("googleAuthR.scopes.selected"))
> gce_global_project("tordo")
2020-04-26 19:25:55> Set default project name to 'tordo'
> gce_global_zone("australia-southeast1-a")
Set default zone name to 'australia-southeast1-a'
> tag <- gce_tag_container("google-auth-r-cron-tidy", project = "tordo")
> vm <- gce_vm(name = "tordo",
>              template = "studio",
>              username = "ines",
>              password = "XXXX",
>              predefined_type = "n1-standard-1",
>              dynamic_image = tag)

+2020-04-26 19:26:00> Request Status Code: 404
+Error: API returned: The resource 'projects/tordo' was not found

> options(googleAuthR.verbose=2)
>  
> vm <- gce_vm(name = "tordo",
>              template = "studio",
>              username = "lines",
>              password = "XXX",
>              predefined_type = "n1-standard-1",
>              dynamic_image = tag)

+2020-04-26 19:26:35> Token exists.
+2020-04-26 19:26:35> Request: +https://www.googleapis.com/compute/v1/projects/tordo/zones/australia-southeast1-+a/instances/?filter=status%20eq%20TERMINATED
+2020-04-26 19:26:36> Request Status Code: 404
+2020-04-26 19:26:36> API returned error: The resource 'projects/tordo' was not found
+2020-04-26 19:26:36> No retry attempted: The resource 'projects/tordo' was not found
+Error: API returned: # The resource 'projects/tordo' was not found
+global
+notFound

## Renviron 
I've set the .Renviron in the home directory as: 
GCE_AUTH_FILE= "C:/project/tordokey.json"
GCE_DEFAULT_ZONE = "australia-southeast1-a"
GCE_DEFAULT_PROJECT_ID = "tordo"

## Session info: 
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_Australia.1252      
 ctype    English_Australia.1252      
 tz       Australia/Perth             
 date     2020-04-26                  

Packages 
 package              * version    date       lib
 askpass                1.1        2019-01-13 [1]
 assertthat             0.2.1      2019-03-21 [1]
 backports              1.1.5      2019-10-02 [1]
 callr                  3.4.2      2020-02-12 [1]
 cli                    2.0.2      2020-02-28 [1]
 codetools              0.2-16     2018-12-24 [2]
 crayon                 1.3.4      2017-09-16 [1]
 curl                   4.3        2019-12-02 [1]
 desc                   1.2.0      2018-05-01 [1]
 devtools               2.2.2      2020-02-17 [1]
 digest                 0.6.25     2020-02-23 [1]
 ellipsis               0.3.0      2019-09-20 [1]
 fansi                  0.4.1      2020-01-08 [1]
 fs                     1.3.2      2020-03-05 [1]
 future                 1.17.0     2020-04-18 [1]
 gargle                 0.4.0      2019-10-04 [1]
 globals                0.12.5     2019-12-07 [1]
 glue                   1.3.2      2020-03-12 [1]
 googleAuthR          * 1.2.1.9000 2020-04-26 [1]
 googleComputeEngineR * 0.3.0.9000 2020-04-26 [1]
 httr                   1.4.1      2019-08-05 [1]
 jsonlite               1.6.1      2020-02-02 [1]
 listenv                0.8.0      2019-12-05 [1]
 magrittr               1.5        2014-11-22 [1]
 memoise                1.1.0      2017-04-21 [1]
 openssl                1.4.1      2019-07-18 [1]
 pkgbuild               1.0.6      2019-10-09 [1]
 pkgload                1.0.2      2018-10-29 [1]
 prettyunits            1.1.1      2020-01-24 [1]
 processx               3.4.2      2020-02-09 [1]
 ps                     1.3.2      2020-02-13 [1]
 R6                     2.4.1      2019-11-12 [1]
 Rcpp                   1.0.3      2019-11-08 [1]
 remotes                2.1.1.9000 2020-03-25 [1]
 rlang                  0.4.5      2020-03-01 [1]
 rprojroot              1.3-2      2018-01-03 [1]
 rstudioapi             0.11       2020-02-07 [1]
 sessioninfo            1.1.1      2018-11-05 [1]
 testthat               2.3.2      2020-03-02 [1]
 usethis                1.5.1      2019-07-04 [1]
 withr                  2.1.2      2018-03-15 [1]
 source                                        
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.1)                                
 CRAN (R 3.6.1)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.1)                                
 CRAN (R 3.6.1)                                
 CRAN (R 3.6.1)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.1)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.1)                                
 CRAN (R 3.6.3)                                
 Github (MarkEdmondson1234/googleAuthR@ca4b56f)
 Github (cloudyr/googleComputeEngineR@5b23366) 
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.1)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.1)                                
 CRAN (R 3.6.1)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.1)                                
 CRAN (R 3.6.3)                                
 Github (r-lib/remotes@e8c60b4)                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.1)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.3)                                
 CRAN (R 3.6.1)                                

[1] C:/Users/ines_/Documents/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.3/library

**Comment by MarkEdmondson1234** [comment]
tordo is an unlikely name for a GCP project-is, I think you have misread that. Go to your GCP console home and read the project-id top left.

________________________________

**Comment by inespereda** [comment]
That's the name I've given to the project in GCP. Isn't that what it's supposed to be? 
![GCP](https://user-images.githubusercontent.com/64351848/80333565-130d0300-8881-11ea-9ca6-e79f9811b723.png)

**Comment by MarkEdmondson1234** [comment]
Your project-id is not the project name, it’s the value below it so from your screenshot “tordo-275209”

________________________________

**Comment by inespereda** [comment]
Legend! Thanks
