### ISSUE TITLE
Multiple Filters with dim_filters

### ISSUE THREAD

**Issue by michaeltruhl** [MarkEdmondson1234/googleAnalyticsR#313]
I wanted to see if it's possible to have multiple conditions within dim_filters in googleAnalyticsR. I'm looking to create a single filter to include something along these lines:

```
(
   ( condition 1 AND condition 2)
     AND
   ( condition 3 OR condition 4 OR condition 5)
)
```

Forgive the psuedo-code, but I'm basically looking to nest several conditions. Is this possible? Likewise, is it possible to have something like below, which may be a workaround:

```
table <- google_analytics(my_id
                                     , date_range = c("2020-01-01", '2020-04-30')
                                     , metrics = c("users")
                                     , dimensions = c("country", "source")
                                     , max = 400000
                                     , anti_sample = FALSE
                                     , dim_filters = filter_one AND filter_two
)

```
I haven't had any luck finding info or example code for this circumstance.

**Comment by MarkEdmondson1234** [comment]
The top level is a `filter_clause_ga4()` which gives you the AND/OR operator, and I don't think those can be combined - you would need to have the inner AND/OR within the `dim_filter()` which may be possible via the different operators (e.g. using regex via `dim_filter("dim", "REGEXP", "condition1|condition2|condition3")`).

I think `(condition1 AND condition2) AND (condition3 OR condition4 OR condition5)` would also be equivalent to `(condition1 AND condition2 AND (condition3 OR condition4 OR condition5)` e.g. 2 filters vs 3 filters.

A full example would then be:

```r
filter_clause_ga4(list(
  dim_filter("blah", "EXACT", "condition1"),
  dim_filter("blah", "EXACT","condition2"),
  dim_filter("blah","REGEXP","condition3|condition4|condition5")
)
operator = "AND")
```
If that doesn't suffice segments are more flexible and may be what you are looking for, although sampling will be more prevelant.  

You could also make two calls and then use R to join the tables data to the format of what you need, for non-super huge data that will probably be quickest.

**Comment by michaeltruhl** [comment]
Thanks Mark - that's a big help. I'll take a crack at it. Could you share info on the technical constraints which don't allow one to use _dim_filters_ and _filtersExpression_ together in the data calls? My understanding is that it's either-or for those 2 parameters.

**Comment by MarkEdmondson1234** [comment]
You can use those together, and have to - filterExpressions wrap dim_filters..  But you couldn't have two filterExpressions for example - `list(filter_clause_ga4(...), filter_clause_gar(...))`

**Comment by michaeltruhl** [comment]
Ok so since it wraps it, you can't have the following, because it's essentially be doing filterExpressions twice:

_google_analytics(my_id
                                    , date_range = c("2020-01-01", '2020-04-30')
                                    , metrics = c("users")
                                    , dimensions = c("year")
                                    , anti_sample = FALSE
                                    , **filtersExpression** = "ga:pageviews>=100"
                                    , **dim_filters** = filter_multi
)_

**Comment by MarkEdmondson1234** [comment]
Oh I see, I'm not sure about that, would need to test it - it could work perhaps.

**Comment by michaeltruhl** [comment]
Alright, thanks. For the above code, I get the following error:

```
2020-05-13 08:37:06> Request Status Code: 400
Error: API returned: Invalid value 'ga:pageviews>=100' for filters parameter.
```

I can use either of these filters one at a time, but not both at once - I wanted to make sure that was an expected constraint.

**Comment by MarkEdmondson1234** [comment]
Ok I don't see it explicitly documented in the API docs, but it seems like it is.

**Comment by michaeltruhl** [comment]
Alright, that's a shame, but it is what it is. Thanks.

Separate quick question: We get the _users_ dimension frequently, and I would like to use the _anti_sample = TRUE_ parameter, but it seems like the data pulls it by days to avoid sampling, then sums together individual days in the given timeframe. Obviously summing users with web analytics by day over a given period of time is not recommended, due to potentially double-counting users. Is there a way you recommend avoiding sampling while getting _users_ metric? Below is the type of call I'd work with

```
pathways_page <- google_analytics(my_id
                                   , date_range = c("2020-01-01", '2020-04-30')
                                   , metrics = c("users")
                                   , dimensions = c("pageTitle", "nthDay")
                                   , max = 400000
                                   , anti_sample = TRUE
                                   , dim_filters = filter_multi
)
```

**Comment by MarkEdmondson1234** [comment]
Yes it won't work for user based metrics, as they are reliant on the date range to compute them.  You need to look at GA360 etc. if you want to avoid that sampling.

**Comment by michaeltruhl** [comment]
That's what I figured, but I was hoping you had a rabbit somewhere in your hat. 

I love your R packages - thanks for supporting them on Github with comment threads like this. Very helpful.

**Comment by MarkEdmondson1234** [comment]
Cool thanks very much!  Good luck with it all.
