### ISSUE TITLE
Keep milliseconds in activityTime value

### ISSUE THREAD

**Issue by VadimChernik** [MarkEdmondson1234/googleAnalyticsR#314]
Hi Mark,

I have a little issue with iso8601_to_r function from utilities.R.
As I see, this function changes a Timestamp value into POSIXct format, but it keeps only seconds.
> x <- as.POSIXct(gsub("\\....Z$","","2014-10-02T15:01:23.045123456Z"), format = "%Y-%m-%dT%H:%M:%S", tz = "UTC")
> x
[1] "2014-10-02 15:01:23 UTC"
> format(x, "%Y-%m-%d %H:%M:%OS6")
[1] "2014-10-02 15:01:23.000000"

Is it possible to keep milliseconds from the original value?
I've tried to use the format "%Y-%m-%dT%H:%M:%OS" while changing the original Timestamp value. And I got the desired result.
> x <- as.POSIXct(gsub("\\....Z$","","2014-10-02T15:01:23.045123456Z"), format = "%Y-%m-%dT%H:%M:%OS", tz = "UTC")
> x
[1] "2014-10-02 15:01:23 UTC"
> format(x, "%Y-%m-%d %H:%M:%OS6")
[1] "2014-10-02 15:01:23.045123"

I think this fix will be helpful for users if they want to keep a sequence of interactions.

**Comment by MarkEdmondson1234** [comment]
Thanks, I have updated the parsing to 

```r
#' iso8601 timestamp to R
#' @noRd
iso8601_to_r <- function(x){
  as.POSIXct(gsub("\\....Z$","",x), format = "%Y-%m-%dT%H:%M:%OS", tz = "UTC")
}
```

The timestamps are available to millisecond level but you will need to set your R options to see them e.g. \code{options(digits.secs=3)}

**Comment by VadimChernik** [comment]
Thanks a lot.
