### ISSUE TITLE
[DOCS] Closing parenthesis missing in the last example [multiple API call example]

### ISSUE THREAD

**Issue by madilk** [MarkEdmondson1234/googleAnalyticsR#317]
# Where should be the new or corrected documentation?
![fetching from multiple projects](https://user-images.githubusercontent.com/20192415/82736739-f7d8ca80-9d3c-11ea-942a-3ca0440dd499.JPG)

https://code.markedmondson.me/googleAnalyticsR/articles/v4.html

# What changes should be made?
Hi Mark,
In the last function, there's a closing parenthesis missing. If you try executing the function without it, will get this error: Error: unexpected '}' in:
"  dimensions = c("deviceCategory","year")
  }"
I've attached a screenshot showing where I added and after which, R accepted it.

**Comment by MarkEdmondson1234** [comment]
Thank you!
