### ISSUE TITLE
Custom Date Ranges

### ISSUE THREAD

**Issue by michaeltruhl** [MarkEdmondson1234/googleAnalyticsR#319]
I wanted to inquire about the ability to customize date ranges with "_date_range_" when pulling data. If I wanted to Select data for specific, non-sequential months, how might I do that when querying? For example, if I wanted to get values for dimension "_Month of Year_" for values 201901, 202001, 201910, and 201703, how might I do that with "_date_range_" in my query? If that's not possible, is there another workaround? Thanks, as always. Below is an example

```
Table <- google_analytics(my_id
                                    , date_range = c("2019-01-01", '2020-04-30')
                                    , metrics = c("users")
                                    , dimensions = c("year")
                                    , max = 400000
                                    , anti_sample = FALSE
)
```

**Comment by MarkEdmondson1234** [comment]
No need to set the argument max so high, set it to -1 to see all results. 

There are some date examples on the website, it sounds like you want to set it to the earliest month and the latest date then the yearMonth dimension - don’t use date dimension unless you want daily figures.

**Comment by MarkEdmondson1234** [comment]
If you want only two months non-sequential then you can send in two date ranges: 2020-01-01, 2020-01-31, 2020-03-01, 2020-03-32 would get Jan and March. 

Website has some more examples of sending in comparison date ranges.

**Comment by michaeltruhl** [comment]
Thanks Mark
