### ISSUE TITLE
authentication problem - 401 deleted client

### ISSUE THREAD

**Issue by stavrovskaya** [MarkEdmondson1234/googleAnalyticsR#327]
Hi, I have authentification problem in Chrome 
I'm using the command in my R script:

googleAnalyticsR::ga_auth()

But it leads me to the error page in browser:
https://prnt.sc/tnsfhc
![image](https://user-images.githubusercontent.com/19977213/88382489-404e4c00-cdb1-11ea-9dd7-7cb34630b90a.png)

**Comment by MarkEdmondson1234** [comment]
You need to update to the latest version.

________________________________

**Comment by stavrovskaya** [comment]
Thank you very match, I've installed the latest version and now I can access with gar_auth_service()

**Comment by MarkEdmondson1234** [comment]
With the latest version you can also authenticate with ga_auth(json_file="file-location.json")

Glad it's sorted :)
