### ISSUE TITLE
[question] Possible to force daily data?

### ISSUE THREAD

**Issue by hubisan** [MarkEdmondson1234/googleAnalyticsR#330]
## What goes wrong

For some reason Google Analytics says that the results of a query contains no sampled data. But I am quite confident that it is sampled. I can verify this by querying daily data (the numbers differ) or leaving out a dimension and compare it by summing.

This problem occurs also when using the Google Analytics web client or the Query Explorer. So is has nothing to do with googleAnalyticsR.

We are investigating the cause.

## Question

Is it possible to force retrieving the data by daily batches somehow?

Using this doesn't work as there is no sampling reported:

```R
anti_sample = TRUE,
anti_sample_batch = 1
```

**Comment by MarkEdmondson1234** [comment]
Are you using user type metrics in your verification?  That would alter totals - look to compare a custom report in the WebUI vs the exact same dimensions in your API call.

The data triggers anti_sample when the sample counts are present in the response, so as the API thinks the data is not sampled if it doesn't trigger.

You could make your own loop to fetch daily to verify although it should make no difference (if you are not using user metrics)

Something like

```r
library(googleAnalyticsR)

## the dates to fetch one day at a time
the_dates <- seq(as.Date("2020-01-01"), as.Date("2020-02-01"), by = 1)

my_fetch <- function(x) {
  google_analytics(1234567,
                   date_range = c(x,x),
                   metrics = "sessions",
                   dimensions = c("date","medium"))
}

## loop over dates into a list
all_data <- lapply(gaids, my_fetch)

## combine into one dataframe
df <- Reduce(rbind, all_data)
```

**Comment by hubisan** [comment]
Ok, I have a go with a loop then.

The case itself seems very strange:
![image](https://user-images.githubusercontent.com/4160043/91830498-22db9000-ec43-11ea-89af-acd395e9b88b.png)

And the same with a daily data range:
![image](https://user-images.githubusercontent.com/4160043/91830763-7bab2880-ec43-11ea-8ac2-ba838e32db25.png)

Hmm, maybe an event for a specific date can occur on another date somehow.
