### ISSUE TITLE
[DOCS] 

### ISSUE THREAD

**Issue by AntoineSoetewey** [MarkEdmondson1234/googleAnalyticsR#343]
Dear Mark,

Thanks for your package.

When reading the [tutorials section](https://code.markedmondson.me/googleAnalyticsR/#tutorials) of the package's documentation, I found some broken links: 

* Bert uses googleAnalyticsR to detect bot traffic
* Fredrik forecasts sales from Google Analytics and sends it to your own Slack bot [Swedish]
* Omar shows some heatmaps and ggplot2 using googleAnalyticsR in Spanish
* Mararoff.com shows how to compare your CRM data with Google Analytics in Russian

**Comment by MarkEdmondson1234** [comment]
Thanks, will try to see if they moved or simply remove them.

**Comment by AntoineSoetewey** [comment]
Perfect!

**Comment by AntoineSoetewey** [comment]
Dear Mark,

I recently wrote another tutorial on how to track performance of a blog using your package: https://www.statsandr.com/blog/track-blog-performance-in-r/.

By any chance, would it be eligible to be included in the tutorial sections?

Feel free to let me know if you have any suggestions.

Regards,
Antoine

**Comment by MarkEdmondson1234** [comment]
Looks great!  Yes I will include it, very in-depth and I like stress on the analysis part of what you can do with the data for those links.
