### ISSUE TITLE
[DOCS] How to pull minute level data from new ga_data API

### ISSUE THREAD

**Issue by mgahan** [MarkEdmondson1234/googleAnalyticsR#348]
Is it possible to pull `dataHourMinute` data from 

```
basic <- ga_data(
   "32842739",
   metrics = c("sessions"),
   dimensions = c("dateHourMinute"),
   date_range = c("2020-12-10", "2020-12-14")
 )
ℹ 2020-12-15 09:48:01 > Request Status Code:  400
Error: API returned: Field dateHourMinute is not a valid dimension. For a list of valid dimensions and metrics, see https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema 
```

Are they removing this functionality from the API?

**Comment by MarkEdmondson1234** [comment]
I expect the list of dimensions to increase in the future but for now it's only those listed at the link in the error message. You could make a custom event with the data I guess, hitTimestamp for instance.

**Comment by mgahan** [comment]
Thanks Mark! Appreciate all the work with this package.

**Comment by mgahan-he** [comment]
The Data API appears to have dateHourMinute now!
