### ISSUE TITLE
MCF reports not working (v4)

### ISSUE THREAD

**Issue by pochenok** [MarkEdmondson1234/googleAnalyticsR#35]
Hello,
It seems like the plugin won't recognize mcf dimensions and metrics. It tries to add "ga:" string, instead of adding "mcf:"
I'm not sure If it's just a bug or mcf support requires more thing to do.

**Comment by MarkEdmondson1234** [comment]
Yes MCF are not avilable yet for v4, instead of `google_analytics_4` you need to use `google_analytics`  which is v3, and supply the argument `type="mcf"`
