### ISSUE TITLE
Error in auth - This app is blocked

### ISSUE THREAD

**Issue by selesnow** [MarkEdmondson1234/googleAnalyticsR#351]
Hi, i get error when i try auth with my own google app.

## What goes wrong
When i try auth with my app i get next:

![](http://img.netpeak.ua/alsey/160881511531_kiss_13kb.png)

## Steps to reproduce the problem
My code

```r
googleAuthR::gar_set_client(json =  "C:/my_develop_workshop/ppc_digest/ga_app/ga_app.json")
ga_auth(email = "my_email@gmail.com")
```

## Expected output
Succes auth

**Comment by MarkEdmondson1234** [comment]
The client.Id had access to scopes that Google deems sensitive such as Google drive. Try making a new client.Id with no scopes, as none are needed for GA.

**Comment by selesnow** [comment]
Thanks, i added my_email@gmail.com like editor in google cloud project where the app was created. And it worked for me.
