### ISSUE TITLE
includeEmptyRows argument in google_analytics() function 

### ISSUE THREAD

**Issue by selesnow** [MarkEdmondson1234/googleAnalyticsR#352]
Hi!

In `RGA::get_ga()` function has `include.empty.rows` argument, for load all rows. 

How i can apply this option in your `google_analytics()` function?

When i try:

```r
  google_analytics(viewId = paste0("ga:",view_id),
                   max = -1, 
                   filtersExpression = "ga:source=~(google|yandex|direct|direkt|vk|vkontakte|fb|facebook);ga:medium=~(cpc|cpm|ppc)",
                   date_range = c(paste0(days_num, "daysAgo"), "yesterday"), 
                   metrics = c("ga:impressions",
                               "ga:adClicks",
                               "ga:adCost",
                               "ga:sessions",
                               "ga:bounces",
                               "ga:transactions"), 
                   dimensions = c("ga:date",
                                  "ga:source",
                                  "ga:medium"),
                   includeEmptyRows = TRUE)
```

I get error: `unused argument (includeEmptyRows = TRUE)`

**Comment by MarkEdmondson1234** [comment]
It's included in all calls, I didn't see any point to not have it TRUE if it's coming back into R.

**Comment by MarkEdmondson1234** [comment]
You also do not need to include "ga:" in your calls.

**Comment by selesnow** [comment]
> You also do not need to include "ga:" in your calls, aside from the filter expression.

Yes, i include this in view_id, dimension and metrics, and in filtersExpression .

My filter expression inclure ga: - `"ga:source=~(google|yandex|direct|direkt|vk|vkontakte|fb|facebook);ga:medium=~(cpc|cpm|ppc)",`
