### ISSUE TITLE
Candidates

### ISSUE THREAD

**Issue by muhammad9824** [MarkEdmondson1234/googleAnalyticsR#355]
I hope  I get new update and solve from Candidates

* User lists https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/accounts.userLinks/audit
* site tag https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.webDataStreams/getGlobalSiteTag
* dev guides
    - https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.webDataStreams/list
    - https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.androidAppDataStreams/list
    - https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.iosAppDataStreams/list
 * Google Ads list https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.googleAdsLinks/list
 * Firebase links https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.firebaseLinks/list
 * Data Sharing settings https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties/getDataSharingSettings

_Originally posted by @MarkEdmondson1234 in https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/350#issuecomment-747412855_

**Comment by MarkEdmondson1234** [comment]
Its not clear what you are asking here
