### ISSUE TITLE
Potentially breaking changes in GA4 API - ordering, date_range column

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAnalyticsR#361]
We're making two potentially breaking changes to the API response based on
this feedback. The changes are:

   1. Current: If multiple date ranges or metric aggregations are included
   in a run report request, currently the response rows are unordered.
   Updated: After this update, the response rows will always be ordered by
   the request's order bys. This means that response row ordering is not
   affected by multiple date ranges or metric aggregations.

   2. Current: If a single date range and a metric aggregation is included
   in a run report request, currently a date_range column is included in the
   response. This date range column always attains the value "date_range_0".
   This date range column was not specified in the request.
   Updated: After this update, the date_range column will not be added for
   single date range and metric aggregation requests. The date range column
   will still be added automatically if the request specifies multiple date
   ranges.

For background, the default ordering of response rows is descending by the
first metric. Order bys in the request override that default ordering.

These changes will go live this week.

**Comment by pluszero-global** [comment]
Hi MarkEdmondson!

I am having difficulty with GA4 API. I have updated the library and tried to follow the steps you listed here: https://code.markedmondson.me/googleAnalyticsR/articles/reporting-ga4.html

However, it continually gives me an error.
If you give a new instruction on the installation of GA4 library that I could follow, I would be very pleased.

Thanks you.

**Comment by MarkEdmondson1234** [comment]
@pluszero-global please continue your issue in this thread https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/363

**Comment by MarkEdmondson1234** [comment]
Admin API

Breaking changes

update_mask field is required for all Update operations.

country_code field renamed to region_code in Account.

url_query_parameter field renamed to uri_query_parameter in EnhancedMeasurementSettings.

parent field removed from GoogleAdsLink.

Features

Pagination support added for ListFirebaseLinks operation.
Please make sure your code is updated to use the latest version of the API client libraries.

 

Data API

Quota updates

The Data API reduced the quota tokens charged per query. The quota limits for property quota tokens per hour and per day were not changed. 


New dimensions

The following new dimensions have been added to the Analytics Data API schema:

hour The two-digit hour of the day that the event was logged. This dimension ranges from 00-23 and is reported in your property's timezone.

nthHour The number of hours since the start of the date range. The starting hour is 0000.

nthYear The number of years since the start of the date range. The starting year is 0000.

dateHour The combined values of date and hour formatted as YYYYMMDDHH.



Custom Metric Variants

Each custom metric that a property registers creates three API metric variants: a sum, an average, and a count.

**Comment by MarkEdmondson1234** [comment]
Looks ok in the tests
