### ISSUE TITLE
Data API problems

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAnalyticsR#363]
Hi MarkEdmondson!

I am having difficulty with GA4 API. I have updated the library and tried to follow the steps you listed here: https://code.markedmondson.me/googleAnalyticsR/articles/reporting-ga4.html

However, it continually gives me an error.
If you give a new instruction on the installation of GA4 library that I could follow, I would be very pleased.

Thanks you.

_Originally posted by @pluszero-global in https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/361#issuecomment-767433023_

**Comment by MarkEdmondson1234** [comment]
@pluszero-global Could you show me the code you used and the error message.

**Comment by pluszero-global** [comment]
> @pluszero-global Could you show me the code you used and the error message.

Thanks for the quick reply!
Here's the code:

`library(googleAnalyticsR)
ga_auth(email = "pluszero@pluszero.co.kr")
ga_account_list("ga4")`

It's exactly the same code you wrote! However, every time I run the code I receive this error:

"Error in ga_account_list("ga4") : 사용되지 않은 인자 ("ga4")"
-> Translating: "ga4" is not the correct argument.

I've tried to update the package with this statement: "install.package("googleAnalyticsR", dependency = T)"
Thanks

**Comment by MarkEdmondson1234** [comment]
It needs to be installed using the GitHub version for now, (see Website for how) it won't be on CRAN until the GA4 API is in beta.

**Comment by pluszero-global** [comment]
> It needs to be installed using the GitHub version for now, (see Website for how) it won't be on CRAN until the GA4 API is in beta.

Thank you for the quick reply.
I'll try the way you explained.

Anyways, I just wanna express my sincere thanks for creating and updating this amazing library.
Your GA R libray is a huge hit in Korea!

Thanks.

**Comment by MarkEdmondson1234** [comment]
Hello Korea!  You should be ready after you use `remotes::install_github("MarkEdmondson1234/googleAnalyticsR")` then restart R and re-run the code above.

**Comment by MarkEdmondson1234** [comment]
That should sort out your issue.  When the API its in beta the package will be on CRAN version 0.9
