### ISSUE TITLE
Limit rows clientId

### ISSUE THREAD

**Issue by everleazy** [MarkEdmondson1234/googleAnalyticsR#365]
Hello.
Sorry in advance - I use Google translator. =)

Faced a problem - I can't get more than 10,000 rows when requesting data from a client.
There are about 30,000 users in Analytics per day.
When I try to query in 1 day, I get exactly 10,000 rows.

Tried with the parameter "max" (-1), anti_sample.
I still only get 10,000 lines.

**Comment by MarkEdmondson1234** [comment]
Hmm seems like this issue is still the case then:
https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/283

Closing this one as a duplicate, please see the other thread - but for some people it seems it was fixed?

**Comment by everleazy** [comment]
Hello!

It went by itself))

I don’t know if you fixed it or not.

But now it works - right now I have downloaded statistics for 30 days for almost 1 million lines.
