### ISSUE TITLE
Limit of 50,0000 rows

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAnalyticsR#374]
Hey!

I have a problem with function **google_analytics** and customDimensions. I get a maximum of 50,000 lines. In fact, there are many more of them in GA.

Example request:
ga_stat_query <- google_analytics (ga_id $ viewId,
                                  date_range = c (startDate, endDate),
                                  metrics = c ("sessions"),
                                  dimensions = c ("dimension12"),
                                  max = -1)

How do I fix this?

Thank!

_Originally posted by @baikulov in https://github.com/MarkEdmondson1234/googleAnalyticsR/discussions/345#discussioncomment-429750_

**Comment by MarkEdmondson1234** [comment]
Hi @baikulov I moved it here.

It sounds like you are hitting API limits?  If you read this does it help? https://support.google.com/analytics/answer/1009671?hl=en

**Comment by baikulov** [comment]
Yes. This was the reason. Divided the request into parts and solved the problem.

Thank!
