### ISSUE TITLE
Minor error documentation typo: "gar_auth()"

### ISSUE THREAD

**Issue by gilliganondata** [MarkEdmondson1234/googleAnalyticsR#38]
I think this should say ga_auth()

![image](https://cloud.githubusercontent.com/assets/19396775/18253122/8e5b9970-7392-11e6-9573-7bd1e74bde51.png)

**Comment by MarkEdmondson1234** [comment]
Thanks!

**Comment by gilliganondata** [comment]
Actually... maybe this isn't a bug? I think gar_auth() is correct, isn't it?

**Comment by MarkEdmondson1234** [comment]
It's confusing so it will change, but technicall you can run gar_auth as ga_auth just wraps it with some defaults set.
