### ISSUE TITLE
[DOCS] googleAnalyticsR tutorial videos and articls for Russian Language users

### ISSUE THREAD

**Issue by selesnow** [MarkEdmondson1234/googleAnalyticsR#388]
Hello Mark, I have created several training materials for Russian-speaking users, if you wish, you can add links to the package website.

Videos:

1. [Как работать с API Google Analytics на языке R с помощью пакета googleAnalyticsR](https://youtu.be/p2D_iLZ1f-8)
2. [Как работать с API Google Analytics 4 на языке R, воркшоп для новичков (googleAnalyticsR)](https://youtu.be/zJyDxd4JGg0)

Articles:

1. [Как загрузить данные из API Google Analytics в R: часть 2](https://netpeak.net/ru/blog/kak-zagruzit-dannyye-iz-api-google-analytics-v-r-chast-2/)

I would be grateful if you add these links to [googleAnalyticsR site](https://code.markedmondson.me/googleAnalyticsR/)

**Comment by MarkEdmondson1234** [comment]
Amazing thank you!

**Comment by MarkEdmondson1234** [comment]
@selesnow I would just like to mention that you can authenticate with a JSON key directly now with `ga_auth()` - so 

```r
# replace this
googleAuthR::gar_auth_service(json_file = "D:/ga_auth/service.json")

# with this
ga_auth(json_file = "D:/ga_auth/service.json")
```

**Comment by MarkEdmondson1234** [comment]
Its on the dev website: https://code.markedmondson.me/googleAnalyticsR/dev/

I think changes like this shouldn't wait for the next CRAN release though so will think about a workflow for merging in website changes so it appears at https://code.markedmondson.me/googleAnalyticsR/

**Comment by selesnow** [comment]
Thanks!
