### ISSUE TITLE
 Error: could not find function "dynamicSegment"

### ISSUE THREAD

**Issue by gilliganondata** [MarkEdmondson1234/googleAnalyticsR#39]
The following code returns:

`Error: could not find function "dynamicSegment"`

It's weird. googleAnalyticsR is loaded, and the help is showing, but R is saying the function doesn't exist. (Put aside that I might not have the syntax right yet... but it seems like there's something more fundamental I'm missing here.)

```
library(googleAnalyticsR)
segments_list <- list(
  segment_ga4("All Visits","gaid::-1"),
  dynamicSegment("Non-Paid",sessionSegment = "sessions::condition::ga:channelGrouping=~(Organic.Search)|(Direct)|(Referral)"),
  dynamicSegment("Paid",sessionSegment = "sessions::condition::ga:channelGrouping=~(Paid.Search)|(Display)|(Video)|(Social)|(Email)|(Other)")
)
```

**Comment by MarkEdmondson1234** [comment]
The nesting is wrong here, I definitely need better examples. Where is dynamicSegment from? Perhaps I need to hide internal functions. I think if you are mixing old style segment definitions you need to use segmentExpression instead.

**Comment by gilliganondata** [comment]
Ah. Got it. Yeah... there is a lot of documentation, but it's sparse. So, it wasn't clear what the hierarchy was and where. Thanks!

**Comment by MarkEdmondson1234** [comment]
Working now? Cool. Could I grab your code to put as an example?

**Comment by gilliganondata** [comment]
Just the snippet above? Grab away!

**Comment by gilliganondata** [comment]
A) I now realize the documentation said that dynamicSegment was a snippet.
B) I've found the v4 segments documentation at: http://code.markedmondson.me/googleAnalyticsR/v4.html. So...working my way through that.
