### ISSUE TITLE
Anti sampling don't work

### ISSUE THREAD

**Issue by egkasatkin** [MarkEdmondson1234/googleAnalyticsR#393]
## What goes wrong
Anti sampling don't work

## Steps to reproduce the problem
my requst

GA_SEO_all <- google_analytics(
        GAid,
        date_range  = c(date_start, date_start),
        dimensions  = c("clientId", "date", "sourceMedium", "campaign", "deviceCategory", "keyword", "userType"),
        metrics     = c("goal2completions", "goal8completions", "goal12completions", "goal15completions", "users", "pageviews", "sessions", "newUsers", "sessionDuration", "bounces"),
        dim_filters = exp,
        anti_sample = TRUE)

## Expected output
2021-12-09 14:12:38 > anti_sample set to TRUE. Mitigating sampling via multiple API calls.
i 2021-12-09 14:12:38 > Finding how much sampling in data request...
i 2021-12-09 14:12:38 > Reading cache
i 2021-12-09 14:12:38 > Downloaded [ 9 ] rows from a total of [ 10001 ].
i 2021-12-09 14:12:38 > No sampling found, returning call
i 2021-12-09 14:12:41 > Downloaded [ 9999 ] rows from a total of [ 10001 ].
i 2021-12-09 14:12:43 > Downloaded [ 1 ] rows from a total of [ 10001 ].
i 2021-12-09 14:12:43 > All data downloaded, total of [ 10001 ] - download time:  4.678494 secs

all time same result 10k rows.  antisampling didn't turn on

**Comment by MarkEdmondson1234** [comment]
Its not that `anti_sampling` isn't working, its that including `clientId` runs you into this issue https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/283

See that thread for background and possible work arounds.

**Comment by egkasatkin** [comment]
thank you so much!)
