### ISSUE TITLE
GA4/ga_data(): Error in if (grepl("^#", mm)) { : the condition has length > 1

### ISSUE THREAD

**Issue by elalbaicin** [MarkEdmondson1234/googleAnalyticsR#403]
## What goes wrong

Whenever I try to extract data from GA4 with `ga_data()`, I get the following error:

```
Error in if (grepl("^#", mm)) { : the condition has length > 1
In addition: Warning message:
In pq$concurrentRequests < 10 || verbose :
  'length(x) = 2 > 1' in coercion to 'logical(1)'
Error: API Data failed to parse.  
             Wrote diagnostic object to 'gar_parse_error.rds', use googleAuthR::gar_debug_parsing('gar_parse_error.rds') to 
             debug the data_parse_function.
```

## Steps to reproduce the problem

All session info is at the "Session Info" section; then it should suffice to run:

```r
ga_data(propertyId = propertyId,
              date_range = c("2022-10-10", "2022-10-10"),
              dimensions = c("date"),
              metrics = c("sessions"),
              limit = -1)
```

By the way, I've tried omitting the `limit` argument to see if the issue persisted, and it still threw an error.

## Expected output

A dataframe.

## Actual output

The aforementioned error message.

Running `options(googleAuthR.verbose=2)` does not yield any output.

## 'API Data failed to parse' diagnostics

I've written the output of `googleAuthR::gar_debug_parsing("gar_parse_error.rds")` on this file: 
[gar_parse_error.txt](https://github.com/MarkEdmondson1234/googleAnalyticsR/files/9756336/gar_parse_error.txt)

## Session Info

This file contains the output of `sessionInfo()`:
[session_info.txt](https://github.com/MarkEdmondson1234/googleAnalyticsR/files/9756347/session_info.txt)

**Comment by MarkEdmondson1234** [comment]
Thanks, sessionInfo will be helpful - upgraded to a new version of R? It may have caught an error that was a warning but raises an error now in new version. 

Was the same query working in a previous version of R?

**Comment by elalbaicin** [comment]
> Thanks, sessionInfo will be helpful - upgraded to a new version of R? It may have caught an error that was a warning but raises an error now in new version.
> 
> Was the same query working in a previous version of R?

I did upgrade to R 4.2.1 recently, but when I downgraded to 4.2.0 the exact same error ocurred. By the way, it stopped working on October 10, if it's any help.

**Comment by eniefaC** [comment]
> upgraded to a new version of R?

I'm on a brand new install (R, R Studio, googleanalyticsr) 

[sessionInfo.txt](https://github.com/MarkEdmondson1234/googleAnalyticsR/files/9759263/sessionInfo.txt)

Thanks for your work.

**Comment by MarkEdmondson1234** [comment]
It may be the API changed it's response, but will check it out

**Comment by XoliloX** [comment]
Hi all,

I have the same issue with same error message. The error gets triggered with `ga_data()` à but not with `google_analytics()`

[sessioninfo.txt](https://github.com/MarkEdmondson1234/googleAnalyticsR/files/9762693/sessioninfo.txt)

Thanks for your support !

Best,
D.

**Comment by MarkEdmondson1234** [comment]
Should be fixed now, it was a change in the API response related to quotas.

```r
> options(googleAuthR.verbose = 2)
> ga_data(ga_id,
+         date_range = c("2022-10-10", "2022-10-10"),
+         dimensions = c("date"),
+         metrics = c("sessions"),
+         limit = -1)
ℹ 2022-10-12 11:14:45 > Request:  https://analyticsdata.googleapis.com/v1beta/properties/206670707:runReport/
ℹ 2022-10-12 11:14:45 > Reading cache
ℹ 2022-10-12 11:14:45 > tokensPerDay: Query Cost [ 1 ] / Remaining [ 24992 ]
ℹ 2022-10-12 11:14:45 > tokensPerHour: Query Cost [ 1 ] / Remaining [ 4996 ]
ℹ 2022-10-12 11:14:45 > concurrentRequests Consumed / Remaining:  0  /  10
ℹ 2022-10-12 11:14:45 > serverErrorsPerProjectPerHour Consumed / Remaining:  0  /  10
ℹ 2022-10-12 11:14:45 > Downloaded [ 1 ] of total [ 1 ] rows
# A tibble: 1 × 2
  date       sessions
  <date>        <dbl>
1 2022-10-10       86
```

To install the fix now use `remotes::install_github("MarkEdmondson1234/googleAnalyticsR")`and I'll submit it to CRAN ASAP

**Comment by XoliloX** [comment]
Fixed, thanks a lot !!!

**Comment by elliedigitalanalytics** [comment]
Thanks for the fix!!!

**Comment by MarkEdmondson1234** [comment]
This fix is on CRAN now so you can install normally, v1.1.0

**Comment by eniefaC** [comment]
Thank you for the great software and support!
