### ISSUE TITLE
ga_data parsing error

### ISSUE THREAD

**Issue by mgahan-he** [MarkEdmondson1234/googleAnalyticsR#404]
## What goes wrong

I am getting the following error when I try to pull data using the **ga_data** function:

<img width="924" alt="image" src="https://user-images.githubusercontent.com/45569512/195180938-9c1d1dfb-b2ce-44b7-bebf-ac5b1ab2b115.png">

## Steps to reproduce the problem

This is the code I am running:

```
library(googleAnalyticsR)
library(googleAuthR)
gar_auth(email="myemailaddress@gmail.com")

# List accounts
check_all <- googleAnalyticsR::ga_account_list()

# replace with your propertyId
TodaysDate <- Sys.Date()
TodaysDate <- as.Date(TodaysDate)
TodaysDate <- as.character(TodaysDate)
my_property_id <- 332949020
basic <- ga_data(
  propertyId=my_property_id,
  metrics = c("sessions"),
  dimensions=c("date"),
  date_range = c("2022-10-03", "2022-10-03"),
  limit=-1
  )
```

## Expected output

Expected output is a two column table with "date" and "sessions" as the headers.

## Actual output

<img width="924" alt="image" src="https://user-images.githubusercontent.com/45569512/195181016-a215fc68-e4e0-4f58-9565-944a88de9650.png">

Here is the verbose output:

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/45569512/195181172-4d6debc6-66d0-4265-92a5-c4dbf918102c.png">

## 'API Data failed to parse' diagnostics

If you have an error starting with:

`API Data failed to parse.`

* Please install googleAuthR >v0.7.9000:

```r
remotes::install_github("MarkEdmondson1234/googleAuthR")
```

* Restart the R session and run your bugged code.
* It should write a file called `gar_parse_error.rds` to your working directory.
* Run the below to output some diagnostic information and paste the response here.

```r
googleAuthR::gar_debug_parsing("gar_parse_error.rds")
```

## Session Info

<img width="907" alt="image" src="https://user-images.githubusercontent.com/45569512/195181341-c8237846-05b3-4728-850c-cd1c18bb13d1.png">

**Comment by MarkEdmondson1234** [comment]
Thanks, this looks to be same issue as #403. Closing this thread to keep info in there.
