### ISSUE TITLE
PublisherAdClicks metric gives only 0 

### ISSUE THREAD

**Issue by crishski** [MarkEdmondson1234/googleAnalyticsR#405]
## What goes wrong

When i am running code ga_data() with **publisherAdClicks** i get 0 for each row in column **publisherAdClicks**. I want to see **session campaign name**, **session source medium**, **session** and  finally **publisher ad clicks**. Then I want to compare **session** with **publisher ad clicks**.

In addtion my account GA4 is connected with Google Ads.

## Steps to reproduce the problem
This is the code I am running:

library("googleAnalyticsR")
ga_auth()

webPropertyId <- "xxxxxxxxx"
date <- c(Sys.Date()-31, Sys.Date()-1)
 
ga_data(webPropertyId,
        date_range = date,
        metrics = c("sessions", "publisherAdClicks"),
        dimensions = c("sessionCampaignName", "sessionSourceMedium"),
        limit=-1)

## Expected output

Publisher ad clicks column will not have 0 for each row.

## Actual output

![image](https://user-images.githubusercontent.com/115638096/195351464-2f084d17-05c5-4d6b-b770-189172b279bf.png)

sessionCampaignName      sessionSourceMedium         sessions publisherAdClicks
   <chr>                    <chr>                          <dbl>             <dbl>
 1 xxxxxxxx                google / organic             81391                 0
 2 xxxxxxxx                google / cpc                   43245                  0
 3 xxxxxxxx                (direct) / (none)              12950                  0
 4 xxxxxxxx                google / cpc                    6313                   0
 5 xxxxxxxx                google / cpc                     5251                  0

## 'API Data failed to parse' diagnostics

-

## Session Info

Please run `sessionInfo()` so we can check what versions of packages you have installed
![image](https://user-images.githubusercontent.com/115638096/195352269-80dc6927-9331-460f-b500-3d56c133c7bf.png)

**Comment by MarkEdmondson1234** [comment]
I think this sounds like an issue with the api itself, as some dimensions or metrics can't be queried together. You can try the online tool to check if the combination is valid. If it is report back here as then that is something I can fix.

**Comment by crishski** [comment]
This metric works! It seems to me that when I created my script 2 months ago there was no this metric "advertiserAdClicks" available.

Thank you so much! :)
