### ISSUE TITLE
Auto-authentication JSON file not working / Account list parsing fail

### ISSUE THREAD

**Issue by mischa2002k2** [MarkEdmondson1234/googleAnalyticsR#41]
Hi,
maybe I'm just not fully integrating the authentication process. But as I followed the setup the only thing I need to do is to place the .json from Google APIs Admin Console and point to it with the Global variable.

Sys.setenv(GA_AUTH_FILE = "/Users/michaelsinner/rStudio/test/auth/myAuth.json")

When I try to run a simple test code I get this error:
No authorization yet in this session!
NOTE: a  .httr-oauth  file exists in current working directory.
 Run gar_auth() to use the credentials cached for this session.
Token doesn't exist
Fehler in acc_sum() : Invalid Token
Zusätzlich: Warnmeldung:
In checkTokenAPI(shiny_access_token) : Invalid local token

What am I missing? Is there an issue with the auto authentication with JSON file?

**Comment by MarkEdmondson1234** [comment]
Can you try deleting or moving the existing `.httr-oauth` file in your folder? It may be confusing the auto auth run, but I may also need to improve the logic.

**Comment by mischa2002k2** [comment]
Hi Mark,

I tried this already, the error message keeps a little bit the same. Here it is:

No authorization yet in this session!
No  .httr-oauth  file exists in current working directory.  Run gar_auth() to provide credentials.
Token doesn't exist
Fehler in acc_sum() : Invalid Token
Zusätzlich: Warnmeldung:
In checkTokenAPI(shiny_access_token) : Invalid local token

**Comment by MarkEdmondson1234** [comment]
May I see your sessionInfo:

```
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleAnalyticsR_0.3.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7                    magrittr_1.5                   googleCloudStorageR_0.2.0.9000 devtools_1.12.0.9000          
 [5] xtable_1.8-2                   R6_2.1.3                       bigQueryR_0.2.0.9000           httr_1.2.1.9000               
 [9] dplyr_0.5.0                    tools_3.3.0                    DBI_0.4-1                      googleAuthR_0.4.0.9000        
[13] withr_1.0.2                    htmltools_0.3.5                digest_0.6.10                  assertthat_0.1                
[17] tibble_1.1                     tidyjson_0.2.1                 crayon_1.3.1                   shiny_0.14                    
[21] rsconnect_0.4.3                testthat_1.0.2                 memoise_1.0.0                  mime_0.5    
```

Also try putting the file in the `.Renviron` file in your computers user's home directory.

**Comment by mischa2002k2** [comment]
Hey Mark,

this is really strange... I used this:

`googleAuthR::gar_auth_service(Sys.getenv("GA_AUTH_FILE"))
`
Now it seems to work (but not quite). Now appeared this:

```
> account_list <- google_analytics_account_list()
Error : df is not a data frame
Warnmeldung:
In acc_sum() :
  API Data failed to parse.  Returning parsed from JSON content.
                    Use this to test against your data_parse_function.
```

This is my sessionInfo:

```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] jsonlite_1.1           googleAnalyticsR_0.3.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7               magrittr_1.5              googleCloudStorageR_0.2.0 devtools_1.12.0           xtable_1.8-2             
 [6] R6_2.1.3                  bigQueryR_0.2.0           httr_1.2.1                dplyr_0.5.0               tools_3.3.1              
[11] DBI_0.5-1                 googleAuthR_0.4.0         withr_1.0.2               htmltools_0.3.5           digest_0.6.10            
[16] assertthat_0.1            tibble_1.2                tidyjson_0.2.1            crayon_1.3.2              shiny_0.14               
[21] testthat_1.0.2            memoise_1.0.0             mime_0.5                  httpuv_1.3.3   
```

**Comment by MarkEdmondson1234** [comment]
Ah, looks like you have CRAN version of `googleAnalyticsR`loaded, when you need the github version for the moment until I put it on CRAN

```r
devtools::install_github("MarkEdmondson1234/googleAnalyticsR")
```

The account parsing though looks like a different issue.  If possible could you do a `str(account_list)` to show what it returned instead of the data.frame.  The parsing fails if there is something unexpected in there, such as an account without a web-property, that I've had problems with before and thought I caught, but looks like there is still some edge case where it doesn't work ;(  you do at least get the data, just not in a user-friendly format.

**Comment by mischa2002k2** [comment]
This is still strange: I installed your version from github, when I now invoke "library(googleAnalyticsR)" it will use automatically your version? Or do I have to refer to it any other way?

str(account_list) is NULL

If the authentication is now made with my JSON (it works with googleAuthR::gar_auth_service(Sys.getenv("GA_AUTH_FILE")))

The user is my service account r-xxxxx-yyyyy@zzzzzzz.iam.gserviceaccount.com

This one is admin level in one GA account (on account level checked: manage users, etc.).

**Comment by mischa2002k2** [comment]
Hi Mark,
I played around with the account_list function, and it seems there is some issue with the number of available accounts/properties/views. When the service account user is only admin in one account with one property and one view there will be this "df is not a data frame" error.
However if I add the user to multiple accounts the functions works fine for me.

Hope this helps debugging. Really appreciate your work!

**Comment by MarkEdmondson1234** [comment]
Thanks @mischa2002k2 , this will help.  I wonder if it fails for all 1 length data.frames.

**Comment by MarkEdmondson1234** [comment]
@mischa2002k2 I think your two issues here should now be solved using the current github version, namely auto-auth and single row account summary lists.  Reopen if that is not the case.

**Comment by palooney** [comment]
Hello, I had exactly same error here and I tried all methods mentioned above but I still got the same error message (API Data failed to parse). Do you have any suggestion for this? Thanks in advance.

**Comment by MarkEdmondson1234** [comment]
@palooney could you please open it with a new issue and an example of your code, along with the output of `sessionInfo`.  Please also run the code with this option set: `options(googleAuthR.verbose = 2)` and edit out anything sensitive.
