### ISSUE TITLE
ga_auth() requests access for wrong Google API

### ISSUE THREAD

**Issue by danielaarup** [MarkEdmondson1234/googleAnalyticsR#411]
## What goes wrong

I'm currently building an ETL script that collects data from Google Search Console, Google Ads and Google Analytics and exports the transformed data to BigQuery. To do this, I'm using the `googleAuthR`, `rgoogleads`, `searchConsoleR` and `googleAnalyticsR` packages. However, when my script tries to authenticate with Google Analytics using the `ga_auth()` function, I'm initially redirected to a browser window with prompts to authenticate via the `searchConsoleR` package; that is, getting access to Google Search Console, instead of Google Analytics.

The authentication for Google Search Console is done using `scr_auth(email = "my@email.com")` from the `searchConsoleR` package earlier in the script.

Is it possible to specify which API/service I want to authenticate with, or are there any other way to solve this problem?

**Comment by MarkEdmondson1234** [comment]
If running multiple API fetches from different packages derived from googleAuthR, it's best to not use the package specific auth functions (such as scr_auth() and ga_auth()) and instead set your own client id with scopes for all packages and authenticate once with gar_auth(). You should then see one login page with GA, Search Console etc. permissions.

**Comment by danielaarup** [comment]
Thanks for the quick reply! It works. I created an app within Google Cloud Console, enabled all relevant APIs, downloaded the JSON client secret and then the following code seems to do the trick:

`gar_set_client(
  json = "/Users/ ... .json",
  scopes = c(
    "https://www.googleapis.com/auth/webmasters",
    "https://www.googleapis.com/auth/adwords",
    "https://www.googleapis.com/auth/analytics"
  )
)

gar_auth(email = "my@email.com")`

**Comment by MarkEdmondson1234** [comment]
Great :) the ga_auth() etc functions basically wraps what you are doing above.
