### ISSUE TITLE
502 timeout - Problem fetching data with version 0.3.0.9000

### ISSUE THREAD

**Issue by joseramoncajide** [MarkEdmondson1234/googleAnalyticsR#47]
The query:

```
se <- segment_element("transactionRevenue", 
                      operator = "GREATER_THAN", 
                      type = "METRIC", 
                      comparisonValue = 0, 
                      scope = "SESSION") 
sv_simple <- segment_vector_simple(list(list(se)))
seg_defined <- segment_define(list(sv_simple))
segment4 <- segment_ga4("simple", user_segment = seg_defined)

ga_conversion_paths.df  <- google_analytics_4(
  ga_id,
  date_range = as.character(date_range),
  metrics = c('hits','transactionRevenue'),
  dimensions =  c("dimension18","dimension17", "eventAction", "eventLabel","segment","dimension8"),
  filtersExpression = "ga:eventLabel!~^:;ga:dimension18!=false;ga:eventCategory==clientid",
  segments = segment4,
  anti_sample = T,
  anti_sample_batches = 15
)
```

The response:

```
anti_sample set to TRUE. Mitigating sampling via multiple API calls.
Finding how much sampling in data request...
Downloaded [10] rows from a total of [258213].
Data is sampled, based on 53.8% of sessions.
Calculated [3] batches are needed to download approx. [309856] rows unsampled.
Anti-sample call covering 14 days: 2016-10-01, 2016-10-14
Request Status Code: 502
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang=en> 
                     (right here) ------^
```

**Comment by MarkEdmondson1234** [comment]
I think this may be because a user segment will do strange results when walking data. Without the segment, does it work?

**Comment by joseramoncajide** [comment]
Same problem.

If I fetch data for two days:
```

anti_sample set to TRUE. Mitigating sampling via multiple API calls.
Finding how much sampling in data request...
Downloaded [10] rows from a total of [16138].
No sampling found, returning call
Downloaded [16138] rows from a total of [16138].
```

More than 50000 rows, still ok:

```
anti_sample set to TRUE. Mitigating sampling via multiple API calls.
Finding how much sampling in data request...
Downloaded [10] rows from a total of [63677].
No sampling found, returning call
Downloaded [50000] rows from a total of [63677].
Downloaded [13677] rows from a total of [63677].
All data downloaded, total of [63677]
```

At some moment, as I expand the dates:

```
anti_sample set to TRUE. Mitigating sampling via multiple API calls.
Finding how much sampling in data request...
Downloaded [10] rows from a total of [211073].
No sampling found, returning call
Request Status Code: 502
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang=en> 
                     (right here) ------^
```

I can't find 502 error code in the docs: https://developers.google.com/analytics/devguides/reporting/core/v3/coreErrors

Only in Google Cloud Platform: a 502 error indicates there is an issue with your network connection.

**Comment by sdoering** [comment]
I can add, that this also does happen in the v4 API version. All else being equal to @joseramoncajide 's bug-report.

**Comment by MarkEdmondson1234** [comment]
Thanks @sdoering - could I just ask what query you did to get the same error? I can't replicate this at the moment, so I'm wondering if its to do with custom dimensions lifespan.

**Comment by MarkEdmondson1234** [comment]
@joseramoncajide could I also check in that you still get the same error with the same request today - they say in some cases 500/503 errors are just due to complex/large queries running out of resources, that will be cleared up in time, but there is not much I can do this end if that's the case. 

What would also be helpful is if possible set `options(googleAuthR.verbose = 1)` and paste the output.  Ideally its the request body we need to see. 

If its still failing, it would also be useful to see if the same request does succeed if using the API explorer here:
https://developers.google.com/apis-explorer/#p/analyticsreporting/v4/analyticsreporting.reports.batchGet

**Comment by MarkEdmondson1234** [comment]
@joseramoncajide @sdoering From checking in it just may be that for complicated queries, the API will time out - which is why lowering the date range helps.  I will look at seeing if this can be added.

**Comment by joseramoncajide** [comment]
The problem seems to be related when fetching too many rows. Switching to a low cardinality dimension works perfect.

`
Error in get_data_from_country(ga_id, ga_queries[[i]]) : 
  task 5 failed - "task 2 failed - "lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang=en> 
                     (right here) ------^
""
`

Added `options(googleAuthR.verbose = 1)` but no extra info was shown.

**Comment by LindaLawton** [comment]
How long is the request running before it times out?   What happens if you send the same request again?

@MarkEdmondson1234 do you have anyway of just spitting out the pure rest you are sending?   It will be easier in the long run to debug issues related to the building of a request.

**Comment by MarkEdmondson1234** [comment]
So to help debug these, I just added to `googleAuthR` an option to write the request JSON to a file.  To use it install latest version of googleAuthR from github and set `option(googleAuthR.verbose = 0)` 

You can then read the sent JSON via something like `jsonlite::toJSON(readRDS("request_debug.rds")$body_json)`

cc @joseramoncajide

**Comment by LindaLawton** [comment]
@MarkEdmondson1234   As you know i don't have the power of R email me a file and i will see if i can help you debug it from the pure rest end.     We need to prove that its a pure GA error and not a R building request error.

**Comment by joseramoncajide** [comment]
Do you mean something like this?

`["{"reportRequests":[{"viewId":"ga:12345678","dateRanges":[{"startDate":"2016-12-01","endDate":"2017-01-12"}],"samplingLevel":"LARGE","dimensions":[{"name":"ga:date"},{"name":"ga:dimension10"},{"name":"ga:productSku"},{"name":"ga:productName"},{"name":"ga:productCategoryLevel4"}],"metrics":[{"expression":"ga:productDetailViews","alias":"ga:productDetailViews","formattingType":"METRIC_TYPE_UNSPECIFIED"}],"orderBys":{"fieldName":"ga:date","orderType":"VALUE","sortOrder":"DESCENDING"},"pageToken":"0","pageSize":10000,"includeEmptyRows":true},{"viewId":"ga:12345678","dateRanges":[{"startDate":"2016-12-01","endDate":"2017-01-12"}],"samplingLevel":"LARGE","dimensions":[{"name":"ga:date"},{"name":"ga:dimension10"},{"name":"ga:productSku"},{"name":"ga:productName"},{"name":"ga:productCategoryLevel4"}],"metrics":[{"expression":"ga:productDetailViews","alias":"ga:productDetailViews","formattingType":"METRIC_TYPE_UNSPECIFIED"}],"orderBys":{"fieldName":"ga:date","orderType":"VALUE","sortOrder":"DESCENDING"},"pageToken":"10000","pageSize":10000,"includeEmptyRows":true},{"viewId":"ga:12345678","dateRanges":[{"startDate":"2016-12-01","endDate":"2017-01-12"}],"samplingLevel":"LARGE","dimensions":[{"name":"ga:date"},{"name":"ga:dimension10"},{"name":"ga:productSku"},{"name":"ga:productName"},{"name":"ga:productCategoryLevel4"}],"metrics":[{"expression":"ga:productDetailViews","alias":"ga:productDetailViews","formattingType":"METRIC_TYPE_UNSPECIFIED"}],"orderBys":{"fieldName":"ga:date","orderType":"VALUE","sortOrder":"DESCENDING"},"pageToken":"20000","pageSize":10000,"includeEmptyRows":true},{"viewId":"ga:12345678","dateRanges":[{"startDate":"2016-12-01","endDate":"2017-01-12"}],"samplingLevel":"LARGE","dimensions":[{"name":"ga:date"},{"name":"ga:dimension10"},{"name":"ga:productSku"},{"name":"ga:productName"},{"name":"ga:productCategoryLevel4"}],"metrics":[{"expression":"ga:productDetailViews","alias":"ga:productDetailViews","formattingType":"METRIC_TYPE_UNSPECIFIED"}],"orderBys":{"fieldName":"ga:date","orderType":"VALUE","sortOrder":"DESCENDING"},"pageToken":"30000","pageSize":10000,"includeEmptyRows":true},{"viewId":"ga:12345678","dateRanges":[{"startDate":"2016-12-01","endDate":"2017-01-12"}],"samplingLevel":"LARGE","dimensions":[{"name":"ga:date"},{"name":"ga:dimension10"},{"name":"ga:productSku"},{"name":"ga:productName"},{"name":"ga:productCategoryLevel4"}],"metrics":[{"expression":"ga:productDetailViews","alias":"ga:productDetailViews","formattingType":"METRIC_TYPE_UNSPECIFIED"}],"orderBys":{"fieldName":"ga:date","orderType":"VALUE","sortOrder":"DESCENDING"},"pageToken":"40000","pageSize":10000,"includeEmptyRows":true}]}"]`

**Comment by joseramoncajide** [comment]
No problem when using v3 with google_analytics()

**Comment by LindaLawton** [comment]
@joseramoncajide  you wont see it with V3 as its a different end point and a different request structure .   Thanks for json :)

**Comment by LindaLawton** [comment]
are you really sending the same report in the same request with just different starting points?  And i thought i was mean to APIs thats just sick.  How do you know what the max is?

**Comment by MarkEdmondson1234** [comment]
@LindaLawton yes, yes I am, its sick :) but quick. The max is given in the first request of "totalRows" although its a bit unreliable so I think I add 20% to it.

**Comment by MarkEdmondson1234** [comment]
@LindaLawton but if it will work with slower paging with nextToken, then thats a fix I can put in as an option.  The majority of requests work ok though.

**Comment by LindaLawton** [comment]
Ok after Hangout conference with Mark.  My opinion is this isn't really a google error but a @MarkEdmondson1234  doing something that i don't think they intended.     Suggest mark hit up the GA team about his evil genius in this one.     I don't think this is how things were intended to be used its probably an issue with the cacheing on the server.

**Comment by joseramoncajide** [comment]
First time I see this: 

` task 5 failed - "task 2 failed - "There was a temporary error. Please try again later.""`

**Comment by MarkEdmondson1234** [comment]
There is now an option to add a `slow_fetch` TRUE to the `google_analytics_4` fetches that will fetch the API in the boring old slow standard way, so 5 times slower but more stable and should complete.

**Comment by terzieff** [comment]
The new `slow_fetch` argument lacks default value somewhere along the way.
After calling
```
query <- google_analytics_4(old_view,
                              date_range = c("2015-01-01", "2015-03-31"),
                              metrics = c("users"),
                              dimensions = c("month"),
                              anti_sample = T        
  )
```
I'm getting 
```
anti_sample set to TRUE. Mitigating sampling via multiple API calls.
Finding how much sampling in data request...
Downloaded [3] rows from a total of [3].
No sampling found, returning call

 Error in google_analytics_4(viewId = viewId, date_range = date_range,  : 
  argument "slow_fetch" is missing, with no default 
3.
google_analytics_4(viewId = viewId, date_range = date_range, 
    metrics = metrics, dimensions = dimensions, dim_filters = dim_filters, 
    met_filters = met_filters, filtersExpression = filtersExpression, 
    order = order, segments = segments, pivots = pivots, cohorts = cohorts,  ... 
2.
anti_sample(viewId = viewId, date_range = date_range, metrics = metrics, 
    dimensions = dimensions, dim_filters = dim_filters, met_filters = met_filters, 
    filtersExpression = filtersExpression, order = order, segments = segments, 
    pivots = pivots, cohorts = cohorts, metricFormat = metricFormat,  ... 
1.
google_analytics_4(old_view, date_range = c("2015-01-01", "2015-03-31"), 
    metrics = c("users"), dimensions = c("month"), anti_sample = T) 
```
The same happens if I include slow_fetch in the initial call, the problem occurs deeper when function `anti_sample` is called.

**Comment by MarkEdmondson1234** [comment]
@terzieff Thanks, I missed one :)  Should work now.
