### ISSUE TITLE
Issue with googleAnalytics Authentication

### ISSUE THREAD

**Issue by nfimmen** [MarkEdmondson1234/googleAnalyticsR#48]
Hello Mark,
I'm struggling to figure out how googleAuthR works. I've written a script to compare Google and Adobe. I'm scheduling the script for every week. When I run the script live myself in R, the authentication works (obviously as I get the pop up to authorize my Google account). However when I schedule the script to run, I have authentication issues. Not sure what I'm doing wrong or if it is the order I have the code in. 

I've ran the script and have the .httr-oauth file saved in the same folder as the R script. Do I have the order wrong? Should there be something in the gar_auth()? Did I screw up the options? Thanks. 

```
library(googleAnalyticsR)
library (googleAuthR)

gar_auth()

options(googleAuthR.client_id = "uxxxx.apps.googleusercontent.com")
options(googleAuthR.client_secret = "xxxx")
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/analytics")
```

**Comment by MarkEdmondson1234** [comment]
Hi @nfimmen 

Yes I think wahts happening is that you have authenticqted under the default project - when you run gar_auth() it looks at the googleAuthR options at the time.  As they are set after authentication, they have no effect.

Assuming you have set up your Google Project ok, with the Google Analytics API on, then you should delete your current httr token then authenticate in this order:

```
options(googleAuthR.client_id = "uxxxx.apps.googleusercontent.com")
options(googleAuthR.client_secret = "xxxx")
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/analytics")

library(googleAuthR)
library(googleAnalyticsR)

gar_auth()
```

This will then give you an auth token with your Google Project (you should see its name when you authentcate via the browser), which you can use for your script. 

Make sure this is in the same order in the script you are scheduling.  Let me know how it goes.

**Comment by nfimmen** [comment]
I just tried it. Some how I must have either my client id or secret wrong (or both). 

I re-authenticated and in the URL string, is that where the auth token should be? I see client id. Is the secret in the URL string too?

**Comment by MarkEdmondson1234** [comment]
Can you screenshot what the auth error message is?

**Comment by nfimmen** [comment]
`Error in init_oauth2.0(self$endpoint, self$app, scope = self$params$scope,  : 
  Unauthorized (HTTP 401). Failed to get an access token.`

**Comment by MarkEdmondson1234** [comment]
So you go through the browser authentication, and it comes back with that error?

**Comment by MarkEdmondson1234** [comment]
The auth URL will be something like this:

```
https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fanalytics+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fanalytics.readonly&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A1410%2F&state=ysAUPidVz3&client_id=201111148134-rm1ij8uxxxxxxx0aqver84b04r7.apps.googleusercontent.com&from_login=1&as=-d111d410af08cbd&authuser=0
```

**Comment by nfimmen** [comment]
Yes. I got that url :). Is the secret in there?

**Comment by nfimmen** [comment]
I should have explained more. I got that URL and when I re-ran the options, that is when I got the error. So I'm thinking the secret is wrong.

**Comment by MarkEdmondson1234** [comment]
You have to copy the clientID and clientSecret exactly from when you set up the Google Project.  Take out any blank spaces.  The secret isn't in the URL, broken down its the scope (which APIs to authenticate for);response_type=code;redirect_uri should be your local host, state is a random number, clientId, some other stuff.

**Comment by MarkEdmondson1234** [comment]
And make sure you delete your old auth token, either by specifying `gar_auth(new_user=TRUE)` or deleting the `.httr-oauth` file that is in your working directory - otherwise it will try to authenticate with your options vs those in your old token that was authenticated with other credentials.

**Comment by MarkEdmondson1234** [comment]
Or just use the default options :)  There is not a real need to use your own unless you plan to do thousands of calls per day.

**Comment by nfimmen** [comment]
Ok. I'll go with the default options. Dumb question - but what is the default?

**Comment by MarkEdmondson1234** [comment]
Default is when you don't set options:

```r
library(googleAnalyticsR)
ga_auth()
```

**Comment by nfimmen** [comment]
Got it. That is easy enough. I'll try that. I'll first run `gar_auth(new_user=TRUE) ` and try this all over again.
