### ISSUE TITLE
object 'out' not found

### ISSUE THREAD

**Issue by toncek87** [MarkEdmondson1234/googleAnalyticsR#50]
I tried anti-sampling query, but there was the issue:

```
ga_auth()
unsampled_data_fetch <- google_analytics_4(ga_id, 
                                         date_range = c("2015-01-01","2015-06-21"), 
                                         metrics = c("users","sessions","bounceRate"), 
                                         dimensions = c("date","landingPagePath","source"),
                                         anti_sample = TRUE)
```

....
```
anti_sample set to TRUE. Mitigating sampling via multiple API calls.
Finding how much sampling in data request...
Downloaded [10] rows from a total of [49581].
Data is sampled, based on 1.1% of sessions. Use argument anti_sample = TRUE to request unsampled data.
Finding number of sessions for anti-sample calculations...
Downloaded [172] rows from a total of [172].
Calculated [102] batches are needed to download approx. [59497] rows unsampled.
Attempting hourly anti-sampling...
Finding number of hourly sessions for anti-sample calculations...
Downloaded [24] rows from a total of [24].
Anti-sample call covering 24 hours: 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23
Error in google_analytics_4(viewId = viewId, date_range = c(the_day, the_day),  : 
  object 'out' not found
```

Do you have any ideas about the issue?

**Comment by MarkEdmondson1234** [comment]
This looks like a bug, may I see your `sessionInfo()` output?  Also you can try the latest versions on github as that may help, install via `devtools::install_github("MarkEdmondson1234/googleAnalyticsR")`

**Comment by toncek87** [comment]
probably i have old library, my version is 0.2.., but currently i  have installed new version. But there is issue about Permission

```
Request Status Code: 403
Error in checkGoogleAPIError(req) : 
  JSON fetch error: Insufficient Permission
```
I would like to reset ga_auth() and options() (clear history and reinstall libarary do not work) and try authorization again, but i dont know how can i reset auth?

**Comment by martijnvv** [comment]
@toncek87 if you delete the token from the folder, you should be able to create a new one:. Your token is called: .httr-oauth

**Comment by MarkEdmondson1234** [comment]
@toncek87 let me know if the latest release sorts it out

**Comment by toncek87** [comment]
I've deleted token .httr-oauth and used ga_auth(new_user=TRUE) ...(i use correct credentials) a still

`library(googleAnalyticsR)

options(googleAuthR.client_id = "xxxxxx")
options(googleAuthR.client_secret = "xxxxxxx")
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/analytics")

ga_auth(new_user=TRUE)

account_list <- google_analytics_account_list()`

`Request Status Code: 403
Error in checkGoogleAPIError(req) : 
  JSON fetch error: Insufficient Permission`

**Comment by MarkEdmondson1234** [comment]
@toncek87 Try for now not setting the options so the defaults are used, just so we are not dealing with two issues.  I guess you need to activate the analytics API  or something in your own project.

Restart R then:

```r
library(googleAnalyticsR)
ga_auth(new_user=TRUE)

account_list <- google_analytics_account_list()
```

**Comment by toncek87** [comment]
It works, there is a issue with my credentials probably. I'll check my GA API credentials. If i use defaults, it works. Thank you

**Comment by MarkEdmondson1234** [comment]
@toncek87 does it also solve the initial issue ('out' not found?)

**Comment by toncek87** [comment]
yes, of course, ('out' not found) has solved

**Comment by MarkEdmondson1234** [comment]
Great :)
