### ISSUE TITLE
Error when using list_goals function

### ISSUE THREAD

**Issue by martijnvv** [MarkEdmondson1234/googleAnalyticsR#53]
I run this query for generating a list of goals:

`list_goals(accountId = accountId, webPropertyId = uaCode_sb, profileId = "~all", start.index = NULL, max.results = NULL)`

It returns the following error:

```
> Error: Variables must be length 1 or 8.
> Problem variables: 'id', 'accountId', 'webPropertyId', 'internalWebPropertyId', 'profileId', 'name', 'value', 'active', 'type', 'created', 'updated', 'urlDestinationDetails.url', 'urlDestinationDetails.caseSensitive', 'urlDestinationDetails.matchType', 'urlDestinationDetails.firstStepRequired', 'eventDetails.useEventValue'
```

Similar queries for custom metrics, custom datasources, etc. work fine. Not sure this is a bug, but I don't understand how to solve this based on the error message.

**Comment by MarkEdmondson1234** [comment]
@martijnvv thanks Martin, perhaps it is the `profileId = "~all"` parameter that I didn't anticipate - does it work if you use individual `profileId`'s ?

I also notice the `urlDestinationDetails` is a nested list, that may be causing problems, will check it out.

**Comment by martijnvv** [comment]
@MarkEdmondson1234 I also tried a specific ID, no luck

**Comment by MarkEdmondson1234** [comment]
@martijnvv hmm, only now do I realise I haven't got a function called `list_goals` in this library :)  

The function `ga_goal_list()` is working ok for me.
