### ISSUE TITLE
Document single filters syntax better - Dimension filter error

### ISSUE THREAD

**Issue by dethaspagan** [MarkEdmondson1234/googleAnalyticsR#55]
When running the following code:

```
df <- dim_filter(dimension="ga:campaign",operator="REGEXP",expressions="welcome")
data_fetch <- google_analytics_4(ga_id,date_range = c("2016-01-01","2016-12-31"),
                                 metrics = c("ga:itemRevenue","ga:itemQuantity"),
                                 dimensions = c("ga:campaign","ga:transactionId","ga:dateHour","ga:productBrand","ga:productName"),
                                 dim_filters = df,
                                 anti_sample = TRUE)
```

It has the following error:

> Error in checkGoogleAPIError(req) : 
>   JSON fetch error: Invalid JSON payload received. Unknown name "dimension_name" at 'report_requests[0].dimension_filter_clauses': Cannot find field.
> Invalid JSON payload received. Unknown name "not" at 'report_requests[0].dimension_filter_clauses': Cannot find field.
> Invalid value at 'report_requests[0].dimension_filter_clauses.operator' (TYPE_ENUM), "REGEXP"
> Invalid JSON payload received. Unknown name "expressions" at 'report_requests[0].dimension_filter_clauses': Cannot find field.
> Invalid JSON payload received. Unknown name "case_sensitive" at 'report_requests[0].dimension_filter_clauses': Cannot find field.
>

**Comment by MarkEdmondson1234** [comment]
Hi @dethaspagan , for filters you need to wrap them a list and then a `filter_clause_ga4` function, here are some examples you can read at `?dim_filter`

```r
## create filters on metrics
mf <- met_filter("bounces", "GREATER_THAN", 0)
mf2 <- met_filter("sessions", "GREATER", 2)

## create filters on dimensions
df <- dim_filter("source","BEGINS_WITH","1",not = TRUE)
df2 <- dim_filter("source","BEGINS_WITH","a",not = TRUE)

## construct filter objects
fc2 <- filter_clause_ga4(list(df, df2), operator = "AND")
fc <- filter_clause_ga4(list(mf, mf2), operator = "AND")

## make v4 request
ga_data1 <- google_analytics_4(ga_id, 
                               date_range = c("2015-07-30","2015-10-01"),
                               dimensions=c('source','medium'), 
                               metrics = c('sessions','bounces'), 
                               met_filters = fc, 
                               dim_filters = fc2, 
                               filtersExpression = "ga:source!=(direct)")
                               

```

**Comment by gilliganondata** [comment]
Having recently been working with dim_filter, too, it seems like, even if I only have a single filter, it still needs to be wrapped as a list in filter_clause_ga4(), and it still needs the operator parameter. It might be worth tweaking the examples to include one for that, as it took a little experimentation (and it's possible I don't have it right).

`## create filters on dimensions
df <- dim_filter("source","BEGINS_WITH","1",not = TRUE)

## construct filter objects
fc2 <- filter_clause_ga4(list(df), operator = "AND")`

In this case, `operator` can be `AND` or `OR` -- it's superfluous, but required. 

Is that right?

**Comment by MarkEdmondson1234** [comment]
@gilliganondata its right, but perhaps not as user friendly as it should be :)

I did try to make it so if its a single filter, it would put it in the list for you, but it broke other stuff so I left it out.  Its like as it is at the moment as its an artifact to how the v4 API organises itself. 

I  will try to make it more intuitive, if you have ideas on how the function calls could look let me know.  I don't want to encourage bad habits if people then want to add multiple filters then suddenly be surprised about the list() call, but I can see the utility of it.

**Comment by gilliganondata** [comment]
I'm torn. Part of me thinks it would be great if a `dim_filter()` object could be used in `google_analytics_4()` if it was just a simple filter (which it seems like is a common use case). Then, if a more advanced (2+ dim_filters) are needed, then `filter_clause_ga4()` would need to be added as an intermediate step. But, I could see that as being confusing.

Simply adding a note or example to the documentation as to how a single filter should look would make sense. I thought it through (as I'm "getting more comfortable with lists," as a wise man once advised me to do!), and I could see how/why a single-item list, where that single item was a list in its own right, made sense for that common (but unique-ish) use case.
