### ISSUE TITLE
anti_sample_batches causing an error?

### ISSUE THREAD

**Issue by gilliganondata** [MarkEdmondson1234/googleAnalyticsR#56]
This may just be a documentation tweak required, but I haven't been able to get `anti_sample_batches` to work. I've been using `anti_sample = TRUE` delightfully for months, but i had a case where that calculation is still winding up with a little bit of sampled data, so I wanted to force the sample window to be 3 days.

This query works (but has a little bit of sampling still occurring):
```
ga_data <- google_analytics_4(viewId = view_id,
                                date_range = c(start_date,end_date),
                                metrics = metrics,
                                dimensions = dimensions,
                                dim_filters = ga_filter,
                                anti_sample = TRUE)
```
I updated it to be this:
```
ga_data <- google_analytics_4(viewId = view_id,
                                date_range = c(start_date,end_date),
                                metrics = metrics,
                                dimensions = dimensions,
                                dim_filters = ga_filter,
                                anti_sample = TRUE,
                                anti_sample_batches = 3
)
```
That returns this:
```
anti_sample set to TRUE. Mitigating sampling via multiple API calls.
Finding how much sampling in data request...
Downloaded [10] rows from a total of [73].
Data is sampled, based on 8.8% of sessions.
Error in seq.default(date_range[1], date_range[2], by = 1) : 
  'from' cannot be NA, NaN or infinite
```
I also tried it without the `anti_sample` parameter, but that just then returns full-on sampled data. I think `anti_sample` has to be included if using `anti_sample_batches`, but the documentation isn't super-clear on that. And, even with that, I'm getting an error.

I thought the use of `dim_filters` might be the culprit, but, when I remove that, I still get the same error.

**Comment by MarkEdmondson1234** [comment]
@gilliganondata Can I just check you on the latest version on Github? `sessionInfo()` This may be the bug where you need to pass in `Date` objects as the date, but lets eliminate that if it isn't:

```r
ga_data <- google_analytics_4(viewId = view_id,
                                date_range = as.Date(c(start_date,end_date)),
                                metrics = metrics,
                                dimensions = dimensions,
                                dim_filters = ga_filter,
                                anti_sample = TRUE,
                                anti_sample_batches = 3
)
```

**Comment by gilliganondata** [comment]
Ah! Version looks current (0.3.0)... but I was passing in the dates as strings (and jumping through some hoops to do so!). That was, indeed, the issue! Thanks!
