### ISSUE TITLE
Problem with Sampling Avoidance and pageviewsPerSession in Month September

### ISSUE THREAD

**Issue by boris85** [MarkEdmondson1234/googleAnalyticsR#57]
~~Unfortunately I can't dig deeper into this one right now.~~ I get the doubled value (only one row) for the metric pageviewsPerSession for the month of September when using Sampling Avoidance. If I turn it off, all data is correct. My guess is that it is an issue when stitching the data back together. 

Ok, so now I had time for some extra information. Below I post the code reproducing "the" error (in my case). So for I assume that it is not the "old-school" segment causing the problem, but it is  simply there to trigger the Sampling Avoidance. 

I am using the most current version from Github: googleAnalyticsR_0.3.0.9000

```
filterSegment <- segment_ga4(name = "test",
            segment_id = paste0("sessions::condition::ga:landingPagePath!~.SOME LANDING PAGES")
)

orderYear <- order_type("year",sort_order = "ASCENDING")

thisTestData   <- google_analytics_4(viewId = gaViewID,
                                           date_range = c("2016-05-01", "2016-12-31"),
                                           metrics =  c("sessions", "avgSessionDuration", "pageviewsPerSession"),
                                           dimensions = c("month","year"),
                                           dimensions = c("segment", "month","year"),
                                           segments = filterSegment,
                                           anti_sample = TRUE,
                                           order = orderYear
)

thisTestDataNoS   <- google_analytics_4(viewId = gaViewID,
                                     date_range = c("2016-05-01", "2016-12-31"),
                                     metrics =  c("sessions", "avgSessionDuration", "pageviewsPerSession"),
                                     dimensions = c("month","year"),
                                     dimensions = c("segment", "month","year"),
                                     segments = filterSegment,
                                     anti_sample = FALSE,
                                     order = orderYear
)
```

**Comment by MarkEdmondson1234** [comment]
Thanks @boris85 , this is most likely related to the fix I recently rolled out for https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/49 

Could you confirm which version of package you are using?  And when you say double you mean literally twice what it should be, rather than two rows.

Whats happening is an aggregation at the end of sampling is summing instead of averaging. I shall look at fixing it.

**Comment by MarkEdmondson1234** [comment]
@boris85 Thanks, this should be caught now, I was missing all metrics with "Per" in the name.

**Comment by MarkEdmondson1234** [comment]
https://github.com/MarkEdmondson1234/googleAnalyticsR/commit/fd2a5a94e38382638f1ccb81676323c59e6cb8be
