### ISSUE TITLE
Errors trying to use ga_custom_upload_file

### ISSUE THREAD

**Issue by CurtisGreenland** [MarkEdmondson1234/googleAnalyticsR#58]
I am trying to upload data to Google Analytics Data Import using the ga_custom_upload_file function.  Getting errors both ways I attempt. 

First, when using a data frame formatted like:
![image](https://cloud.githubusercontent.com/assets/8622307/22485208/54183550-e7ca-11e6-8ecb-9aabb86504b3.png)

ga_custom_upload_file(accountid,
                           webpropertyid, 
                           datasourceid,
                           results)

I get the error: 
Error: Tried to unbox a vector of length 518231

Second, when trying to upload via a csv file:

ga_custom_upload_file(accountid,
                           webpropertyid, 
                           datasourceid,
                           path_to_file)

I get the following error:
Error : No method asJSON S3 class: form_file
In addition: Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  restarting interrupted promise evaluation
All attempts failed.

**Comment by MarkEdmondson1234** [comment]
@CurtisGreenland sorry I missed this until today.  Could you include the output of your `sessionInfo()` as this may be related to you needing the most recent version of `googleAuthR`

**Comment by CurtisGreenland** [comment]
@MarkEdmondson1234 here is the output requested:

R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleAuthR_0.4.0.9000      googleAnalyticsR_0.3.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9               magrittr_1.5              googleCloudStorageR_0.2.0 devtools_1.12.0          
 [5] xtable_1.8-2              R6_2.2.0                  bigQueryR_0.2.0           httr_1.2.1               
 [9] dplyr_0.5.0               tools_3.3.2               DBI_0.5-1                 withr_1.0.2              
[13] htmltools_0.3.5           digest_0.6.12             assertthat_0.1            tibble_1.2               
[17] tidyjson_0.2.1            crayon_1.3.2              shiny_1.0.0               testthat_1.0.2           
[21] memoise_1.0.0             mime_0.5                  jsonlite_1.2              httpuv_1.3.3

**Comment by MarkEdmondson1234** [comment]
Great thanks, and would you have a screenshot of a `str()` of the data.frame you had problems with?  Obscure the values if you want, I'm just interested in the classes, etc.

**Comment by CurtisGreenland** [comment]
@MarkEdmondson1234 Here is the output of str().

'data.frame':	336384 obs. of  6 variables:
 $ ga:productSku  : chr  "XXXXXXXXX" "XXXXXXXXX" "XXXXXXXXX" "XXXXXXXXX" ...
 $ ga:dimension17 : chr  "XXXXXXX" "XXXXXXX" "XXXXXXX" "XXXXXXX" ...
 $ ga:dimension18 : chr  "XXXXX" "XXXXX" "XXXXX" "XXXXX" ...
 $ ga:dimension16 : chr  "XXX - XXXXXXXXXXXXXX" "XXX - XXXXXXXXXXX" "XXX - XXXXXXXXXXX" "XXXXXXXXXXXXX" ...
 $ ga:dimension15 : chr  "XXXX - XXXXXXXX" "XXXX - XXXXXXXXXXXX" "XXXX - XXXXXXXXXXXXX" "XXXX - XXXXXXXXXXXXXXX" ...
 $ ga:productBrand: chr  "XXXXX" "XXXX" "XXXXXXXXX" "XXXX" ...

**Comment by MarkEdmondson1234** [comment]
This looks to be a problem related to https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/40

**Comment by MarkEdmondson1234** [comment]
@CurtisGreenland I have reverted an earlier fix for names that seems to break some uploads

**Comment by CurtisGreenland** [comment]
@MarkEdmondson1234 Perfect. Everything works as expected now.

**Comment by MarkEdmondson1234** [comment]
@CurtisGreenland may I just ask if the issue from #40 is back - the uploads have no name in the UI?  The official documentation is weak for this so its a bit trial and error.

**Comment by CurtisGreenland** [comment]
@MarkEdmondson1234 Yes, the uploads have no file name. 
![image](https://cloud.githubusercontent.com/assets/8622307/22978480/7aaf1988-f358-11e6-8423-e90a3509a9a6.png)
