### ISSUE TITLE
MCF API Data failed to Parse

### ISSUE THREAD

**Issue by moyken** [MarkEdmondson1234/googleAnalyticsR#59]
I ran the following code: 

`mcf_data <- google_analytics(id = my_id,
                        start = "2016-01-01", end="2016-12-31",
                        metrics = "totalConversions",
                        dimensions = "sourcePath",
                        type = "mcf")`

But it results in the error:

> Error in `colnames<-`(`*tmp*`, value = "totalConversions") : 
  attempt to set 'colnames' on an object with less than two dimensions
Warning message:
In ga(pars_arguments = ga_pars) :
  API Data failed to parse.  Returning parsed from JSON content.
                    Use this to test against your data_parse_function.

Please Help! Thank you!

**Comment by MarkEdmondson1234** [comment]
I think the problem here is the error message is misleading, its saying it can't assign names to effectively no data.

**Comment by moyken** [comment]
I just tried using another view ID that I knew had conversions and it worked! Thank you!

However, I wanted to see if there was a way to also pull path data that didn't lead to conversions. Do you happen to know of a way? My goal is to use markov modeling and removal effect to see how the probability of conversion might be effected.

**Comment by MarkEdmondson1234** [comment]
Hi @moyken glad it worked.  You can set up a goal that is configured for all users who see more than 0 pages, that way every session is a goal and the multi-channel funnels will apply.  You may want to do this in another View though as it will mess up metrics like AllGoalCompletions.

There was a recent walk through on applying a markov model to GA data you may or may not have seen, here: http://stuifbergen.com/2016/11/conversion-attribution-markov-model-r/

**Comment by moyken** [comment]
Looked at the code and in the link you provided and its brilliant. Haven't set up a goal to capture all visits yet but when I do, I'll be sure to run the code then.

Thank you so much. Big fan of Dartistics!
