### ISSUE TITLE
Update documentation for installing dependencies on Ubuntu

### ISSUE THREAD

**Issue by postman31** [MarkEdmondson1234/googleAnalyticsR#65]
Run into some troubles when installing package on Ubuntu.
plain install.package("googleAnalyticsR") didn't work. After all I'd managed to get things working with pre-installing 
```
libssl-dev
libcurl4-openssl-dev
```
and then running 
`install.package("googleAnalyticsR", denendencies = TRUE) `

I suppose some README update for installation process would be helpful

**Comment by MarkEdmondson1234** [comment]
Cool thanks - yes I think `httr` or `curl` needs those dependencies. I'll update docs.
