### ISSUE TITLE
You can use shortcuts for dates

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAnalyticsR#67]
today|yesterday|[0-9]+(daysAgo)

e.g.

```r
google_analytics_4(868768, date_range = c("3daysAgo", "yesterday"), metrics = "sessions")
Downloaded [1] rows from a total of [1].
  sessions
1   294654
```

**Comment by sdhaus** [comment]
Awesome! I was just talking to my colleagues that this was literally my only drawback for the package.

**Comment by MarkEdmondson1234** [comment]
Nice, it was always in there but undocumented in the v4 API.  I was just using `Sys.Date()-1` etc. but this is obviously easier on the eye :)
