### ISSUE TITLE
Warn if using metrics in dimension filters and vice versa

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAnalyticsR#68]

**Comment by j450h1** [comment]
Hey Mark. I can work on this one. I've already done some webscraping to compile a list of all dimensions and metrics in GA (even though I feel like I've either done that before or you probably already have a list somewhere).

**Comment by j450h1** [comment]
Here is a little preview, will submit PR shortly.
```
df <- dim_filter("source","BEGINS_WITH","1",not = TRUE)
mf <- met_filter("bounces", "GREATER_THAN", 0)

df <- dim_filter("bounces","BEGINS_WITH","1",not = TRUE)
#>Error: Oops..looks like you have used a metric in a dimension filter!

mf <- met_filter("sources", "GREATER_THAN", 0)
#>Error: Oops..looks like you have used a dimension in a metric filter!
```
You can only have 1 metric or dimension per each filter object. Correct? I noticed you were doing:

```
dimension <- sapply(dimension, checkPrefix, prefix = "ga")
```
Was wondering why you didn't just apply the checkPrefix function directly instead of using sapply?

**Comment by MarkEdmondson1234** [comment]
Thanks!  See pull comment as there is a table imported already that calls the metadata API that could be used.

I guess it was copy-paste from the another function, you're right in this context not much point having the `sapply()`:) - would work with just `checkPrefix(dimension)`  (and it should be `vapply()` anyway from where its copy-pasted from, as `vapply()` is more type-stable than `sapply()`...)

**Comment by j450h1** [comment]
I guess I should have asked before... Oh well, I got some practice with webscraping. I'll see if I can get the dimensions and metrics using the metadata API approach.

**Comment by j450h1** [comment]
I mean before I started web scraping that page for the list of all metrics and dimensions, I could have asked if you knew a way to get this data.

**Comment by MarkEdmondson1234** [comment]
I could have put it in the issue, but thought it would be me :)  Anyhow, time learning something is never wasted ;)  If it includes multi-channel funnel metrics it would be useful to keep a version of it as those are not available in the meta API

**Comment by j450h1** [comment]
Nope, doesn't include multi-channel funnel metrics.
