### ISSUE TITLE
Recovering from a 503

### ISSUE THREAD

**Issue by ghost** [MarkEdmondson1234/googleAnalyticsR#72]
Every so often - typically when testing a parallelized data pull from many sources - I hit a 503 error. The API then exponentially backs off as I expect it to, but none of the retries succeeds. However halting the script and starting it over again works fine, even if I don't wait for the backoff to be over.

I might be mistaken, but my impression is that if I can query the GA API by starting a new call to `google_analytics_4`, a retry should succeed?

The nature of this bug makes a reproducible example kinda hard to recreate, here is my best attempt. 
``` r
library(googleAnalyticsR)
library(googleAuthR)
library(future)
plan(multiprocess(workers = 8))

#Auth here
ga_id <- 12345678

sampled_long_query <- function() {
  google_analytics_4(ga_id,
                     date_range  = c('2011-01-01', '2017-01-01'),
                     metrics     = "pageviews",
                     dimensions  = c("date", "hour", "region"),
                     max = -1,
                     anti_sample = T,
                     anti_sample_batches = 1)
}

res1 %<-% sampled_long_query() #run in background
res2 %<-% sampled_long_query()
res3 %<-% sampled_long_query()
res_print <- sampled_long_query() 
```

**Comment by MarkEdmondson1234** [comment]
Hmm, nice approach - I use future's for other stuff but not yet tried it for GA calls.

You will need to watch out for the GA API limits though, which I suspect you are running into with the 503s - in particular the 10 concurrent calls per view which for big fetches (which in themselves carry multiple batch calls) you may be hitting. 

For big complicated queries, you may be able to avoid some 503's by using the `slow_fetch` flag.  This is related to this issue https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/47

However, I must admit I've never seen the retry working, and with your evidence I will take a look to see if perhaps some kind of caching is going on that makes it not.  As you say its hard to test though as you need to trigger a 500 error (which is the API request at Google's end failing)

**Comment by MarkEdmondson1234** [comment]
If you're looking for a quick fix though, wrapping the call in a `try()` yourself, is an error pausing and retry the call should work, although this is supposed to be what is happening. 

```r
sampled_long_query <- function() {
  out <- try(
  google_analytics_4(ga_id,
                     date_range  = c('2011-01-01', '2017-01-01'),
                     metrics     = "pageviews",
                     dimensions  = c("date", "hour", "region"),
                     max = -1,
                     anti_sample = T,
                     anti_sample_batches = 1))
  if(inherits(out, "try-error")){
    Sys.sleep(5)
    .....try again.....

  }
}
```

**Comment by MarkEdmondson1234** [comment]
As an update on this, I've seen that the native retries of `googleAuthR` seem too frequent as when the above was tried with a 60 second gap between tries a 500 error was recovered from.

**Comment by MarkEdmondson1234** [comment]
My answer for this will be to enable caching once that is ironed out, and then to just rerun the fetch again as the cached calls will be super quick and it will pick up the rest where it broke before.

**Comment by olivia-icivics** [comment]
I was thinking about this recently. Do you have thoughts on using `purrr::safely`?

**Comment by MarkEdmondson1234** [comment]
Its a nicer syntax, but essentially the same as a `tryCatch` block above.

**Comment by MarkEdmondson1234** [comment]
I finally got this in https://github.com/MarkEdmondson1234/googleAnalyticsR/commit/3051c62126cb2585f58e6cc08234cecfd752a703 - give it a go, if you have a  503 then it should a) be better at the RETRY and b) cache the previous calls so will quickly get to where it was if you need to run the call again

**Comment by MarkEdmondson1234** [comment]
Caching should handle this very nicely now.
