### ISSUE TITLE
JSON fetch error

### ISSUE THREAD

**Issue by dkskin** [MarkEdmondson1234/googleAnalyticsR#73]
Dear all,

when i try to run the following script:

gadata <- google_analytics(id = ga_id, 
                           start="2017-01-01", 
                           end="2017-01-02", 
                           metrics = "sessions", 
                           dimensions = "date", 
                           max = 5000)

R studio returns this error:

Request Status Code: 403
Error in checkGoogleAPIError(req) : 
  JSON fetch error: User does not have sufficient permissions for this profile.

I'm using Google Analytics demo account with the dataset from Google Merchandise Store. 

Thank you.
Best
Silvia

**Comment by MarkEdmondson1234** [comment]
You can't use the API with the Google Merchanise Store, sorry :)  Details here: https://support.google.com/analytics/answer/6367342?hl=en
