### ISSUE TITLE
Error in anti-sampling when querying user based metrics

### ISSUE THREAD

**Issue by AgentKaminsky** [MarkEdmondson1234/googleAnalyticsR#74]
Hi, @MarkEdmondson1234 !

I use 1 query where If I use date range for one date data is incorrect, but if I set only one date it is correct.

**Example:**
Query
```
ga_data <- google_analytics_4(ga_id, 
                               date_range = c(start_date,end_date),
                               dimensions=c('landingPagePath','date','country','medium'), 
                               metrics = c('newusers'), 
                               dim_filters = fc,
                               anti_sample = TRUE)
```
1) If I set date_range = c("2017-04-28","2017-04-28")

> ga_data <- ga_data[ga_data$landingPagePath=="/", ]
> sum(ga_data$newusers)
[1] 64

2) If I set date_range = c("2016-12-06","2017-05-03")

> ga_data <- ga_data[ga_data$landingPagePath=="/", ]
> ga_data <- ga_data[ga_data$date=="2017-04-28", ]
> sum(ga_data$newusers)
[1] 82

**Comment by MarkEdmondson1234** [comment]
Ah yes, if you query for user based metrics when using anti sample it will be different figures, as they are linked to the date range you are querying (e.g. New users for that date period) and anti sampling splits out the call into lots of different dates. It's on the website somewhere but I guess I should include a warning when using the anti sampling function as well.

**Comment by S-UP** [comment]
Hi Mark,

Have you considered doing an intelligent batch procedure for dates? I have realized that there is quite a discrepancy when relying on sampling. Hence, I really want to use non-sampling data.

However, I also happen to work weekly performance data. My question for you: Could you add a procedure that tries to sample on complete dimensions whenever possible. E.g. when having 'yearWeek' selected, that it tries to sample based on complete weeks?

If that is too much of a hassle, what would be your suggestion to mitigate such issues?

Many thanks, in particular, for your lovely package!

**Comment by MarkEdmondson1234** [comment]
@S-UP sounds interesting, have you an example on how it would work in practice?  You can set your own sampling length of days if you use the `anti_sample_batches` flag, you could perhaps set that to 7 days for your weekly example?

**Comment by S-UP** [comment]
Hi Mark,

Thanks for pointing out the '''anti_sample_batches''' option! It seems to work for what I need.

Question: how do you calculate the number of batches needed? I just wonder if there is a rule of thumb I could use to estimate how many multiples of a week I can run per batch.

**Comment by S-UP** [comment]
Hi Mark,

Can you maybe look into how the `anti_sample_batches` sets starting values?

I am collecting data starting from 2015-12-28, which is a Monday. I am running a 14-days batch. The data collection should always generate complete weeks from Monday to Sunday. The problem is that even when setting Monday as a starting value and specifying `isoYearIsoWeek` your batch algorithm defaults to 13 days for the first window so that all subsequent batches run starting on Sunday to Saturday.

**Comment by MarkEdmondson1234** [comment]
I'll have to check it, it sounds like it should work as you expect. What happens if you set a 15 day batch?

**Comment by S-UP** [comment]
The funny thing is that only for the first week it defaults to 13 days, after the first week it loops over 14 days. To me it seems as if it would force the 14 day window to start from Sundays.

**Comment by MarkEdmondson1234** [comment]
This is the logic from here:
https://github.com/MarkEdmondson1234/googleAnalyticsR/blob/master/R/anti_sample.R#L96

...which will indeed do as you describe.  I'll think about how to change it for this not anticipated use case :)

```r
> asb <- 3
> as.factor((1:3 %/% asb) + 1)
[1] 1 1 2
Levels: 1 2
> as.factor((1:6 %/% asb) + 1)
[1] 1 1 2 2 2 3
Levels: 1 2 3
> as.factor((1:9 %/% asb) + 1)
[1] 1 1 2 2 2 3 3 3 4
Levels: 1 2 3 4
```

**Comment by MarkEdmondson1234** [comment]
Ok I have to use 0 indexes, which is strange in R world :)

```
## asb is the anti_sample_batch you set
> asb <- 3

> as.factor((0:2 %/% asb) + 1)
[1] 1 1 1
Levels: 1
> as.factor((0:5 %/% asb) + 1)
[1] 1 1 1 2 2 2
Levels: 1 2
> as.factor((0:8 %/% asb) + 1)
[1] 1 1 1 2 2 2 3 3 3
Levels: 1 2 3
```

I'll put that in the github version

**Comment by MarkEdmondson1234** [comment]
Try that now, with the Github version 

```r
devtools::install_github("MarkEdmondson1234/googleAnalyticsR")
```

**Comment by S-UP** [comment]
Thanks a lot for the quick fix! I'll check in when I am back at the office as I am currently traveling. Will get back to you in about 10 days if it does not work as expected.

**Comment by MarkEdmondson1234** [comment]
@S-UP did this work?

**Comment by S-UP** [comment]
Hi Mark,

Sorry for the delay. Just tested it and seems to work fine! 

Thank you!
