### ISSUE TITLE
Add more documentation on setting up your own Google Project

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAnalyticsR#80]
Now the limit has been hit, more pressing people use their own

https://cloud.google.com/resource-manager/docs/creating-managing-projects

**Comment by MarkEdmondson1234** [comment]
This is a good link for it https://cloud.google.com/storage/docs/authentication#generating-a-private-key

**Comment by lgroger** [comment]
Hi @MarkEdmondson1234 , we appreciate you building this library and making it available to us!  We are suddenly getting the error below.  I'm assuming we need to create our own google project which I see instructions for above.  If we create a new project,do you have a instructions on how to hook it up to the R library to use? Thanks!
Error : API returned: Quota exceeded for quota group 'AnalyticsDefaultGroup' and limit 'CLIENT_PROJECT-1d' of service 'analyticsreporting.googleapis.com' for consumer 'project_number:289759286325'.

**Comment by MarkEdmondson1234** [comment]
Hello, yes the limit has been hit again for the default project.  Its been extended to 100k a day but its now being hit.  The best solution is for you to authenticate using your own Google Cloud Project, as detailed on the website [here](http://code.markedmondson.me/googleAnalyticsR/articles/setup.html#authentication-method-2-your-own-google-project).  Long term I'll apply for another quota increase. 

Here is a view of the API hits for the default project. 

<img width="877" alt="Screenshot 2019-06-19 at 18 53 27" src="https://user-images.githubusercontent.com/3155884/59785107-44fa2400-92c4-11e9-8c28-eef063505b73.png">

**Comment by MarkEdmondson1234** [comment]
And actually the best way would be to use this googleAuthR function so you don't need to set lots of options:

https://code.markedmondson.me/googleAuthR/reference/gar_set_client.html

**Comment by NateMietk** [comment]
@MarkEdmondson1234 I am running into this error again.  

`Error: API returned: Analytics Reporting API has not been used in project 912530219989 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/analyticsreporting.googleapis.com/overview?project=912530219989 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.`
