### ISSUE TITLE
duplicating transactions within hourly anti samling request

### ISSUE THREAD

**Issue by postman31** [MarkEdmondson1234/googleAnalyticsR#83]
Hi. There is the code I'm using to fetch transaction data:
```{r}
my_id <- 17804254
se2 <- segment_element("pagePath", 
                      operator = "PARTIAL", 
                      type = "DIMENSION", 
                      expressions = "/deposits/bonus/")

sv_simple2 <- segment_vector_simple(list(list(se2)))
seg_defined <- segment_define(sv_simple2)
segment4 <- segment_ga4("simple", user_segment = seg_defined)
order_option <- order_type("sessions","DESCENDING")

web_data_seg <- google_analytics_4(my_id,
                               date_range = c("2017-05-12", "2017-05-13"),
                               segments =  segment4,                               
                               metrics = c("sessions", "transactions"),
                               order = order_option,
                               dimensions = c("dimension1",
                                              "sourceMedium",
                                              #"dimension2",
                                              "sessionCount",
                                              "transactionId",
                                              "nthDay",
                                              "segment"),
                               anti_sample=TRUE,
                               max = -1)
```
This request  is sampled so i'm using anti_sample = true. However. I'm getting wrong data with transaction = 2 instead of 1. here is the snapshot
![smpl_0512](https://user-images.githubusercontent.com/4282229/26880865-794599ca-4b9e-11e7-892f-e12084f6df63.png)

while fetching data day by day everything is correct despite hourly splitted data:
![smpl13](https://user-images.githubusercontent.com/4282229/26881125-2892b944-4b9f-11e7-8321-0e1e1fe1ba9b.png)
![smpl12](https://user-images.githubusercontent.com/4282229/26881124-2888119c-4b9f-11e7-896a-32cc068f435b.png)

can't get if it's a bug or some wrong using.
I'm sending transaction data through measurement protocol from CRM system with clientID
and dimension1 is custom dim for clientID

**Comment by postman31** [comment]
caused by segment definition, no bug indeed

**Comment by MarkEdmondson1234** [comment]
Best kind of issues, these :)

**Comment by postman31** [comment]
The only drawback is that I still didn't manage to configure the request I
need )))) v4 segments are piece of magic
I hope I didn't throw you into debugging.
And thanks for this package
