### ISSUE TITLE
samplingLevel="WALK" limiting returned rows despite max=99999999 param

### ISSUE THREAD

**Issue by papageorgiou** [MarkEdmondson1234/googleAnalyticsR#84]
FYI Mark
> startDate <- "2017-06-01"
> endDate <- "2017-06-02"
> multi_gadata <- google_analytics(id = c("4770581"), 
+                                  start=startDate, end=endDate, 
+                                  metrics = c("transactionRevenue", "sessions"),
+                                  dimensions = c("date", "landingPagePath", "Country") , 
+                                  max=99999999, samplingLevel="WALK")

The above returns 20K rows only
removing the  samplingLevel="WALK" (which I used it just in case) returns the right number of rows. 

Maybe some conflict between the samplingLevel and max params ?  Not sure, will let you know if I discover anything more with respect to this.

**Comment by MarkEdmondson1234** [comment]
Its better to use `google_analytics_4` for this, I stopped supporting this in v3 as it needed more refactoring, which when there is a more modern alternative was a low priority :)

**Comment by papageorgiou** [comment]
Ok, thanks for  clarifying, I used the v3 code to be able to get data for either one or multiple ids, I believe last time I check this possibility wasn't available with the google_analytics_4 call. Anyway, will have a look at the latest updates in case I have missed something

**Comment by MarkEdmondson1234** [comment]
Yes that is a feature of v3 thats not possible with v4, half the reason its still there.  But as of now, the v3 doesn't support WALK over 10,000 rows per day.
