### ISSUE TITLE
max_results documentation not up to date?

### ISSUE THREAD

**Issue by rwutzke** [MarkEdmondson1234/googleAnalyticsR#9]
The documentation for google_analytics() states the default value for max_results is -1:
https://github.com/MarkEdmondson1234/googleAnalyticsR_public/blob/master/man/google_analytics.Rd#L10
However, looking into the code, it is 100:
https://github.com/MarkEdmondson1234/googleAnalyticsR_public/blob/master/R/getData.R#L35
Explicitly setting max_results to -1 doesn't lead to the described behaviour of automatically querying all data:
https://github.com/MarkEdmondson1234/googleAnalyticsR_public/blob/master/man/google_analytics.Rd#L29
It leads to an error:
``JSON fetch error: Invalid value '-1' for max-results parameter. Valid values are between 0 and 10000.``
Which makes absolutely sense, because no special behaviour for max_results = -1 seems to be implemented.

Another thing I noticed is that for values > 10000 automatically all data is fetched. I just saw that this is documented as a TODO in the code ;) https://github.com/MarkEdmondson1234/googleAnalyticsR_public/blob/master/R/fetch_functions.R#L2

But also for 10000 batching is used, so the following condition could probably be safely changed to max_results <= 10000 (ie not < 10000):
https://github.com/MarkEdmondson1234/googleAnalyticsR_public/blob/master/R/getData.R#L83

**Comment by MarkEdmondson1234** [comment]
Yes this hasn't caught up yet, sorry :)  

Use `max_results` set to what you need, if you don't know set it to something like 999999 or something.  It _should_ then auto-batch fetches of 10000 - but will ignore any limit you set over 10000 (so I guess set it to 10001 and it will fetch all every time).  However, hopefully it fetches fast enough (as it can do 10 batches at once) that you can fetch then filter it yourself afterwards.  That is what I tend to do.

**Comment by MarkEdmondson1234** [comment]
In `google_analytics_4`, you can now set `max = -1` and it will fetch all rows.
