### ISSUE TITLE
Update dplyr functions to use new 0.7.0 abilities

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAnalyticsR#90]
Stuff like `aggregateGAdata` can be parsed to be more elegant:
https://blog.rstudio.org/2017/06/13/dplyr-0-7-0/

**Comment by kiendang** [comment]
I can work on this. Agree that you should change since the underscore version of those `dplyr` functions (`select_`, `group_by_`, ...) are going to be deprecated.
But you need to add `rlang` as dependency in order to use `!!!`.
