### ISSUE TITLE
How to pull Custom Channel Groupings

### ISSUE THREAD

**Issue by S-UP** [MarkEdmondson1234/googleAnalyticsR#91]
Hi,

Our company has set up Custom Channel Groupings. I could not find a note in the documentation but would like to pull data based on this rather than the standard channel grouping.

Should this not be supported, would any of you have a good approach how to get a custom grouping done? Would I have to pull data on the campaign level and do the grouping myself?

Many thanks!

**Comment by MarkEdmondson1234** [comment]
Sadly, custom channel groupings aren't in the API.  The best you could do is to pull the source/medium yourself, then make your own following the same rules as you specified in the GA UI.
