### ISSUE TITLE
Management API & oAuth

### ISSUE THREAD

**Issue by postman31** [MarkEdmondson1234/googleAnalyticsR#93]
Hi, 
I failed to find any way to call Analytics Management API with googleAnalyticsR. Is it possible? (I need uploadData method to load calculated custom dimension back into alanytics). 

If not, is it possible to pass OAuth credentials with system(...) to call Management API from another app/script?

**Comment by MarkEdmondson1234** [comment]
For custom uploads, its implemented via `ga_custom_upload_file` - will that suit?

There are a lot of management API functions implemented, but if above doesn't help it sounds like you are asking for more low level stuff that perhaps `googleAuthR` can help you with if its not supported currently in `googleAnalyticsR`.

**Comment by postman31** [comment]
`ga_custom_upload_file` seems to be the thing I was looking for. Thank you for pointing me in the right direction
