### ISSUE TITLE
Ability to run User level V3 segments

### ISSUE THREAD

**Issue by sdhaus** [MarkEdmondson1234/googleAnalyticsR#98]
Currently, only session level v3 segments are accepted. User level v3 segments are treated as segment ID's and have gaid:: prefixed to it.

This is leading to errors such as: 

```
2017-08-21 10:40:29> segment_id passed but doesn't begin with gaid:: - adding it: gaid::users::condition::ga:landingpagePath=~/home$
Request Status Code: 400
Error in checkGoogleAPIError(req) : 
  JSON fetch error: Invalid value 'gaid::users::condition::ga:landingpagePath=~/home$' for segment parameter.
```

Can segment_ga4 be updated to included user level v3 segments?

```
  if (!is.null(segment_id)) {
    if (grepl("^sessions", segment_id)) {
      myMessage("Segment v3 dynamic segment", level = 1)
    }
```

**Comment by MarkEdmondson1234** [comment]
Thanks, I have just had another example asking about v3 segments so will take a look at this too:
![pasted image at 2017_08_19 02_31 pm](https://user-images.githubusercontent.com/3155884/29514145-c15399e8-8667-11e7-908c-63b0f4617c4d.png)
 > If I do c(segment1,segment2) it sums them. E.g. so that the data table would have each segment in a different column. I know that V4 is supposed to allow for multiple segments in one data pull, but feeling really dense and much googling hasn’t helped (yet)

**Comment by MarkEdmondson1234** [comment]
@sdhaus could you try the GitHub version now?

**Comment by sdhaus** [comment]
its working now. Thanks!

**Comment by sdhaus** [comment]
Hey, Looking like this is not working again.
Installed the latest version from GitHub, but it appears that the update is no longer live.
Looks like travis raised a warning on the commit.

**Comment by MarkEdmondson1234** [comment]
Can I see your `sessionInfo()`?  The fix is still live on GitHub: https://github.com/MarkEdmondson1234/googleAnalyticsR/blob/master/R/segments.R#L152 - perhaps need to reload R session?

**Comment by sdhaus** [comment]
You are correct. I just needed to reload my R session. Thanks!
