### ISSUE TITLE
Documentation: Multi-select

### ISSUE THREAD

**Issue by sdhaus** [MarkEdmondson1234/googleAnalyticsR#99]
multi_select documentation does not match error.

```
multi_select(input, output, session, type = c("METRIC", "DIMENSION"),
  subType = c("none", "segment", "cohort"), default = NULL)
```

subType should be: `subType = c("all", "segment", "cohort")`, as per error: `Warning: Error in match.arg: 'arg' should be one of “all”, “segment”, “cohort”`

**Comment by MarkEdmondson1234** [comment]
Thanks!  But I am having trouble finding where it is documented as `c("all", "segment", "cohort")` - can you point me to where?

**Comment by MarkEdmondson1234** [comment]
Ahhh ok I have found it
